### ISSUE TITLE
Talk Proposal: Exploring async/await using jQuery 2

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [seattlejs/seattlejs#100]
# Exploring async/await using jQuery 2

Many of us have started using the `async` and `await` keywords, and some of us have ventured into the untested waters of `yield` and `*` generators, but did you know they're actually closely related? As a case study, we'll look at how we can hack around TypeScript's generated helpers to get them to work with jQuery 2's old non-standards-compliant pseudo-promises. This talk will start on the basics of how an asynchronous function translates to a state machine, then dive into the details of how awaiting generator yields achieves `async`/`await`.

*Notes*:
* This feels like it would be better as a lightning talk.
* I'm drafting an equivalent Medium article that goes into the details of what the talk will be on: https://medium.com/@joshuakgoldberg/hacking-typescripts-async-await-awaiter-for-jquery-2-s-promises-60612e293c4b

I'm Josh Goldberg, a front-end dev on [Office Sway](https://sway.com) focusing on the web client. My passion is the modern web but I also enjoy branching out to [weird meta-languages](https://github.com/highschoolhacking/gls), helping bring CS education to everyone, crafting unnecessarily fancy cocktails, and remaking old GameBoy games for the web.

* Josh Goldberg
* [Twitter](https://twitter.com/joshuakgoldberg)
* [Github](https://github.com/joshuakgoldberg)
* [Website](http://joshuakgoldberg.com)

*(If you're ok with the GitHub profile photo, I am too!)*

**Comment by codefoster** [comment]
@JoshuaKGoldberg, topic looks great. How about **July 13**? Also, please read our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and confirm that you accept.

**Comment by JoshuaKGoldberg** [comment]
Confirmed!

**Comment by EmmaBroback** [comment]
@JoshuaKGoldberg Hello Joshua! 
We're excited for you to present this week. 
I'm in contact with the venue and they would like to know what machine you're presenting off of so they can be prepared with the appropriate adapters. 
Let me know-- see you Thursday!

**Comment by JoshuaKGoldberg** [comment]
Hey @EmmaBroback - I'm excited too! Expect a Lenovo X1 Carbon with a Mini Displayport adapter.

Btw, the mostly-done talk is up at https://github.com/JoshuaKGoldberg/async-await-generators-typescript-and-jquery/blob/.
