### ISSUE TITLE
Talk Proposal: Making a Game with Pixi.JS

### ISSUE THREAD

**Issue by fritzy** [seattlejs/seattlejs#101]
# Making a 2D Web Game with Pixi.JS

You know some JavaScript, and you want to try your hand at making a game, but where to start? You could write it using direct canvas calls, and I encourage people to play with it, to know it. Pixi.js brings with it a lot of optimizations, structure, gpu acceleration with software fallbacks, not to mention ease of use.

You'll be surprised at how quickly we can put together a simple game with Pixi.js that is playable anywhere there is a modern browser, phones and tablets included.

---
I'm the CTO and Architect at &yet. &yet is responsible for talky.io, the Node Security Project (through our security group ^Lift), Realtime Conf, etc. I personally like to make games on the side like [talkylander.com](https://talkylander.com) and [Pet Rescue](http://www.sagebrush.games/bouncingpets). I've got a new game that would be perfect for this talk.

* Nathan Fritz
* [Twitter @fritzy](https://twitter.com/fritzy)
* [Github](https://github.com/fritzy)
* [andyet.com](https://andyet.com)

![boxing match](http://i.imgur.com/cl8VPVS.gif)

**Comment by fritzy** [comment]
I would give a tour of the code for this game. https://twitter.com/fritzy/status/871632861215940609

**Comment by codefoster** [comment]
@fritzy, would you like to deliver a lightning presentation (~10 min) on Sept 14? Also, please confirm that you agree with our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md).

**Comment by codefoster** [comment]
Actually, @fritzy, there's an opening for next month on July 13 too if you can take that.

**Comment by fritzy** [comment]
@codefoster I may be on a family trip on July 13th, but I'll take the Sept 14th slot! Also, I just launched the game that we'll be doing a code dive in at https://spacewar.pro ... next step is to pick a license and open source it.

**Comment by codefoster** [comment]
Great. Confirm the code of conduct and we'll call this confirmed for Sept 14.

**Comment by fritzy** [comment]
@codefoster I will follow the code of conduct and help others follow it as well.
