### ISSUE TITLE
Talk Proposal: Building React components in isolation with Storybook 

### ISSUE THREAD

**Issue by TimMikeladze** [seattlejs/seattlejs#102]
# Building React components in isolation with Storybook

_(and some patterns for writing awesome React components)_

## Problem

Let's imagine for a few sentences a scenario which developers encounter everyday. 

You're working on a project under heavy development. Its got multiple feature areas and lots of different ui components. The feature area that you've been working on is page to display a user's profile with consists of a set of components such as "recent posts" or "bookmarked items". A new set of requirements arise which ask for a new component which displays "suggested posts" for the user. 

Oh and to make it a bit more interesting, let's say that there is currently a bug which prevents you from logging into the app and by that same token navigating to the user profile. In other words you can't even run the app and see the React component you're supposed to be designing while running the app. Not only that but the backend for the data the "suggested posts" component needs to display won't be ready for a few more days. 

So how do you approach this problem and build your component without being blocked by other outstanding tasks?

## Solution

Say hello to [React Storybook](https://storybooks.js.org/).

> Storybook is a development environment for UI components. It allows you to browse a component library, view the different states of each component, and interactively develop and test components.

![](https://raw.githubusercontent.com/storybooks/storybook/master/app/react/docs/demo.gif)

## Talk details

Throughout the talk I will go through the entire process of using Storybook for designing and writing a React component from inception to deploying a prototype while highlighting the major points below

1. Getting started with Storybook
1. Why should react components be written in isolation
1. Writing functional components and higher order components
1. Leveraging `recompose` to manage component state and other useful react utilities through composition.
1. Showcasing Storybook in action by building an example ui component
1. Connecting your component to mocked data
1. Testing your React components with Storybook and Jest

## About me

Hello. My names Tim. I work within the JS ecosystem and React a lot. This talk is a culmination of my experiences using Storybook and a few insights I've picked up along the way to writing React components which I'd like to share with the community. 

- [Github](https://github.com/TimMikeladze)
- [Twitter](https://twitter.com/timmikeladze) (not really active, maybe I'll post my third tweet one of these days 😛 )

_(I accept the code of conduct 👍 )_

**Comment by TimMikeladze** [comment]
It's been a while since I submitted this talk and haven't received any feedback, is there any interest in this or should I close the issue? Thanks.

**Comment by codefoster** [comment]
Not for lack of interest, I just let this slide. Your topic is very much in line with the group's interests and we'd love to have you share it. How does a feature presentation (~25 min) on November 9 sound? Also, do you agree to our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)?

**Comment by TimMikeladze** [comment]
Alright cool. That date and time sounds good. 

I do accept the code of conduct, is there something I need to explicitly submit saying I've accepted it?

**Comment by codefoster** [comment]
Just stating that you accept is plenty. Thanks. Consider us confirmed for the date.

**Comment by ebrillhart** [comment]
Hi @TimMikeladze, just confirming that you're still set to give this talk November 9th! Meetup will be at Avvo. Right now, you're the only speaker, but I'm trying to get another feature or a couple of lightning talks.

**Comment by TimMikeladze** [comment]
Confirmed. Looking forward to it.

**Comment by TimMikeladze** [comment]
@ebrillhart I'm stuck in traffic, will be a few minutes late, so sorry!

**Comment by TimMikeladze** [comment]
Thanks for having me.

Closing this issue.
