### ISSUE TITLE
Talk Proposal: IoT PWA + AMP (is it 😎 yet?)

### ISSUE THREAD

**Issue by tzmanics** [seattlejs/seattlejs#103]
#  IoT PWA + AMP (is it 😎 yet?)
Progressive Web Apps are not replacing native mobile applications any time soon. Don’t disregard them just yet! We can take our web applications that we already have running and make them better. Even if you can't currently take advantage of service workers, it is progressive so you won't negatively effect your app.

But wait, there’s more! One of the biggest drawbacks of using web apps on mobile is the speed (or lack there of). Accelerated Mobile Pages (AMP) works to provide a better user experience across many platforms.

I'd like to show you the journey I took creating my app with Node, Angular and Kendo UI to take more control of my Philips Hue lights. Then how and why I made it into a PWA and used AMP to make it more performant an engaging.
 
---
I'm Tara Z. Manicsic, a developer advocate for [Progress](https://www.progress.com/) and am traveling the west coast in my 77' [Apache camper](https://littlehousesbigdogs.files.wordpress.com/2015/06/img_5753.png) to join, learn and support as many JS communities as humanly possibly ;) I had a great time at your meetup in May and it was great meeting @codefoster & Wale! We talked about me speaking in **July** and if you still have a spot I would be very appreciative & excited 👍

- [@tzmanics](twitter.com/tzmanics)
- [some posts](http://developer.telerik.com/author/tmanicsi/)
- [ngConf talk](https://www.youtube.com/watch?v=j2S5OrMUj9g) & [Women Techmakers Montreal talk](https://www.youtube.com/watch?v=njsvP3x_WS0&index=11&list=PLHq0FpphrOrCvSYyy27JZYI56k2HUKGbP)
- my dog typing up this issue for me:
![toshmagosh](https://github.com/tzmanics/deploy-for-dogs/blob/master/images/toshi-01.gif?raw=true)

**Comment by codefoster** [comment]
Hey, @tzmanics. How about a feature presentation (~25 min) on Oct 12? If that works for you, please confirm that you agree with our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md).

**Comment by tzmanics** [comment]
Hi @codefoster 👋 Sorry! I should have specified, I'm only in Seattle for July. If you even have any small spots open for the July meeting, I would love to present! Hope the planning for SeattleJS is going well!!

**Comment by codefoster** [comment]
I _do_ have an opening for July. I'll put you down for a lightning presentation (~10 min) for July 13. Please agree to the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and let me know what to use for your avatar and we'll be set.

**Comment by tzmanics** [comment]
🎉 awesome! and I definitely agree to the code of conduct! Thanks!! I'll be heading up in my camper (#KendoCamperTour 😉 ) at the beginning of July! Excited to see you all again 👍

**Comment by EmmaBroback** [comment]
@tzmanics Hi Tara! 
We're excited for you to present this week. 
I'm in contact with the venue and they would like to know what machine you're presenting off of so they can be prepared with the appropriate adapters. 
Let me know-- see you Thursday! 

(ps: your dog is great)

**Comment by tzmanics** [comment]
@EmmaBroback haha thanks, she thinks so too.
I'm on a mac, an HDMI connection would be great!

**Comment by EmmaBroback** [comment]
Fantastic! I'll let them know.
