### ISSUE TITLE
Talk Proposal: Diving Into Decorators

### ISSUE THREAD

**Issue by cmgriffing** [seattlejs/seattlejs#104]
# Diving Into Decorators

Decorators are coming to JS via spec proposal. It might be a little while before browsers implement them natively, but they are already available via TypeScript and, to a lesser extent, Babel. Several libraries and frameworks are already using them to great effect such as Angular and MobX.

Lets go on a tour of what they are and what they can do while examining some basic and real world examples. We will also touch on metadata and how some decorators are using metadata hide away details that don't matter as much when implementing business logic and features.

## Short Bio
Chris Griffing is a developer at Fresh Consulting in Bellevue. Lately, he has been spending a lot of time working with TypeScript and Angular on various client projects. On an unrelated note, he thinks it has been getting entirely too hot outside and can't wait to be back in the mountains this winter.

* Chris Griffing
* [Twitter](https://twitter.com/cmgriffing)
* [Github](https://github.com/cmgriffing)
* [Website](http://chrisgriffing.com)

## Source code and live presentation
(currently a draft. I am open to suggestions and critiques)
Source - https://github.com/cmgriffing/decorators-presentation
Live - https://cmgriffing.github.io/decorators-presentation/?notes
I recommend allowing the popup to show the presenter notes to get a better idea of what I will be saying for each slide.

## Duration
I believe this to be a lightning talk (15 mins or so). I will be giving a rendition of this presentation internally at a dev meeting at the company I work for and will be able to give a more concrete estimate of the time needed soon.

## Scheduling
I am wide open to letting you decide which month this would be best for.
I would also like to mention that I am willing to present at the SeattleJS Conference if we are not yet past the cutoff for lightning talks.

Thanks.

**Comment by cmgriffing** [comment]
I am open to any and all suggestions to improve the content of this presentation.
I have a list of Issues on my repo for this: https://github.com/cmgriffing/decorators-presentation/issues

Feel free to add suggestions here or there. If added here, I will make sure to update the Issues on my repo to make sure I do not miss them.

**Comment by codefoster** [comment]
Chris, thanks for the submission. This looks like a great presentation. Do you think you'd rather do a feature presentation (~25 min) or a lightning (~10 min)?

**Comment by cmgriffing** [comment]
My current thinking is that this is about 15 minutes of content. As I add more content for the sake of completeness, it may increase. I will have a better grasp of the exact time it takes after presenting at my workplace next Monday.

Also, to save you some time, I hereby agree to the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md). Thanks.

**Comment by cmgriffing** [comment]
I just gave a trial run at work today. It took me about 12 minutes after one small question was asked but I talked pretty fast. Blocking out 15 minutes is probably on the safer side of things, if possible.

**Comment by codefoster** [comment]
Sounds good. How about 15 minutes on October 12?

**Comment by cmgriffing** [comment]
Sounds great. Thanks Jeremy.

**Comment by codefoster** [comment]
Consider this confirmed. Thanks.
