### ISSUE TITLE
Talk Proposal: OAuth2 for Browser Clients

### ISSUE THREAD

**Issue by krotscheck** [seattlejs/seattlejs#105]
# OAuth2 for Browser Clients

This talk will cover the OAuth2 authorization protocol, as it applies to browser-based JS clients. If you're building a browser-based application and you would like to authenticate against many different clients

The topic will cover (as quickly as possible):
* The difference between Authn/Authz
* The difference between HTTP status 401 and 403
* OAuth2 RFC6749's Implicit, Authorization, Client Credentials, and Owner Credentials flow.
* What's in a token (JWT)
* What's in a scope.
* An overview of the broader ecosystem, including supporting RFC's, error code registries, OpenID Connect, with documentation links.

## Michael Krotscheck
* [Twitter](https://twitter.com/krotscheck)
* [Github](https://github.com/krotscheck)
* [Website](https://krotscheck.net)

**Comment by krotscheck** [comment]
This would be a feature talk.

**Comment by codefoster** [comment]
How does December 14 work for you?

**Comment by krotscheck** [comment]
Works for me! Leaving for Ixtapa the next day though :)

**Comment by codefoster** [comment]
FYI, we're confirmed on this. Thanks, Mike.

**Comment by krotscheck** [comment]
Alrighty. I hope you like super technical talks :)

**Comment by EmmaBroback** [comment]
@krotscheck Hi Mike! 
Can I get a short bio from you for our meetup page? 
Thanks!

**Comment by krotscheck** [comment]
Sure!

```
Michael Krotscheck is a crusty old software engineer who's survived the first, second, and third browser wars with only minimal scars. He currently leads all UI engineering efforts in VMware's Cloud Management Business Unit, serving his peers by encouraging consistency, quality, and velocity. In his free time he implements IETF RFC's for fun, and practices dad jokes on his toddler.
```
