### ISSUE TITLE
Talk Proposal: Demystifying HTTP Status Codes

### ISSUE THREAD

**Issue by krotscheck** [seattlejs/seattlejs#106]
# Demystifying HTTP Status codes

You've successfully built an `XMLHttpRequest` or `fetch` client, but now your api is returning weird numbers. What do they all mean?! This lighning talk will cover all of the weird -- but useful! -- http status codes that you're likely to encounter during everyday API usage. The talk will answer questions like:

* Success doesn't always mean the same thing: 200, 201, 202, 204
* Redirecting with 300, 301, 302, 307 and 308
* Caching status codes (304)
* What is the difference between 401 and 403?
* What's in a 404?
* Conflict resolution (409)
* Why twitter is full of stoners (status code 420, 429).
* The importance of coffee (418)

## Michael Krotscheck
* [Twitter](https://twitter.com/krotscheck)
* [Github](https://github.com/krotscheck)
* [Website](https://krotscheck.net)

**Comment by codefoster** [comment]
Feature or lightning for this one?

**Comment by krotscheck** [comment]
Lightning- super quick, more fun than serious.

**Comment by ebrillhart** [comment]
Ah, sorry, I see you're giving the feature at the December meetup! Let me know if there's another date you'd be interested in giving this lightning talk, even if it's later in the spring.

**Comment by krotscheck** [comment]
Hey Emilia! Anything after December, with the exception of April :)

**Comment by ebrillhart** [comment]
Awesome! Would you be interested in the February 8th meetup?

**Comment by krotscheck** [comment]
Let's do it!

**Comment by ebrillhart** [comment]
Since you've already confirmed that you agree to the CoC for your December talk, I'll mark this as confirmed :)

**Comment by krotscheck** [comment]
Well, I agreed to the CoC back when I presented on headless browser testing in July. But, yeah, I agree :)
