### ISSUE TITLE
Talk Proposal: Package Quest

### ISSUE THREAD

**Issue by jefflembeck** [seattlejs/seattlejs#107]
Ever wonder what happens when you `npm install` something? Follow an odyssey across the wires as our hero client embarks on an adventure to bring you the software that you need, right when you ask for it. After this talk you'll have a better understanding of the course a package takes - helping you understand architecture that works at scale as well as being able to troubleshoot package installation problems.

Two versions of this talk: 25min and 45min

I'll be available to give this talk in November (and forward from there)

**Comment by codefoster** [comment]
How about Jan 11, 2018?

**Comment by jefflembeck** [comment]
@codefoster I'm in. How long are you hoping for?

**Comment by codefoster** [comment]
How about we call it 35 minutes and we only take one lightning preso that month?

**Comment by jefflembeck** [comment]
👍🏻
