### ISSUE TITLE
Talk Proposal: Using SVG from JavaScript without losing a finger

### ISSUE THREAD

**Issue by thomaswilburn** [seattlejs/seattlejs#108]
Although support for SVG in browsers has been relatively stable for years, it's still a bit of an enigma to many developers. It has also suffered from neglect, compared to the improvements made to the HTML DOM over the last few years, and the attention lavished on Canvas for dynamic graphics.

But working with SVG from JavaScript doesn't have to be mysterious or painful, and you don't have to be a designer to find it useful. Simple techniques and new tools can make it a fundamental problem-solving skill for any web developer. Let's make ourselves a `<group>`, find our `<path>`, and get `<rect>` with some vector graphics!

In this 25-minute talk, we'll discuss the following:
* What is SVG, how do I include it in my page, and why would I want to?
* Generating and manipulating shapes using a React-style API
* Tracing lines and moving the "camera" to art-direct SVG
* Common pitfalls in using the SVG DOM directly
* Working with SVG in modern front-end frameworks like Vue

**Comment by ebrillhart** [comment]
Hi @thomaswilburn! Are you still interested in giving this talk? It sounds super interesting. Would you be available to give it at our December 14th Meetup or our February 8th meetup?

**Comment by thomaswilburn** [comment]
December 14th would be great!

**Comment by ebrillhart** [comment]
@thomaswilburn awesome! I know you've spoken before, so I'm sure you know the drill, but if you just say that you agree to our code of conduct (https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md), I will count this as confirmed!

**Comment by thomaswilburn** [comment]
Absolutely, I agree to the code of conduct. I'll add it to my calendar.

**Comment by EmmaBroback** [comment]
@thomaswilburn Can I please get a short bio from you to add to our meetup event? Thanks!

**Comment by thomaswilburn** [comment]
Sure, let's go with the old standby:

> Thomas Wilburn is the news developer for The Seattle Times. Before that, he built web-based UI for Guild Wars 2 at ArenaNet, and ran the Multimedia Team at Congressional Quarterly. He’s also the developer of the Caret text editor for Chrome OS.
