### ISSUE TITLE
Talk Proposal: Accessibility Testing for Web Developers

### ISSUE THREAD

**Issue by alexlande** [seattlejs/seattlejs#109]
Accessibility advice has a tendency to boil down to a list of rules. Use real button elements! Don't hide focus outlines! Provide alt text! Rules are OK, but it's a lot easier to build accessible websites if you can see first-hand why the rules matter. This talk will give you the tools to confidently and comfortably test accessibility in your projects. Let's demystify accessibility!

We'll cover:

- Keyboard navigation, including common gotcha's on OSX.
- How to use a screen reader and where to find one.
- Automated tools to check for color contrast, alt text, and more.

---

👋  This is a 25 minute talk, but I could also probably do a 10 minute version that's just the screen reader portion.

**Comment by ebrillhart** [comment]
@alexlande yes this would be an excellent talk!! Want to do the 25-min talk Nov. 9th, February 8th, or March 8th?

**Comment by alexlande** [comment]
Can't do November, but either of the other days would work for me.

**Comment by ebrillhart** [comment]
Okay, I'll put you down for March then! If you "verbally" agree to our CoC https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md then I'll mark you as confirmed! Thanks!

**Comment by alexlande** [comment]
Hooray! I absolutely agree to follow the CoC 🤘

**Comment by alexlande** [comment]
@ebrillhart I forgot to ask, can I use audio for this talk? Would be helpful for screen reader demos. I can get by if not though.

**Comment by EmmaBroback** [comment]
Hey @alexlande, can I get a brief bio from you? Thanks!

**Comment by alexlande** [comment]
Yeah!

> Alex is a developer at Formidable. He spends way too much time thinking about pattern libraries, accessible user interfaces, and responsive design. He wants to make the web work for everyone.
