### ISSUE TITLE
Lightning! Talk Proposal

### ISSUE THREAD

**Issue by lbingle** [seattlejs/seattlejs#111]
# Javascript & Automation in Adobe Creative Suite

Graphics are a key component of the online experience. Tweets with images are more likely to receive clicks. Brands such as Dropbox and Slack are hiring illustrators to produce one of a kind graphics for their brands. Maintaining quality images collections though requires frequent changes in image size, file types, etc. This can quickly exceed the capacity of a collection manager. 

This talk will explore how you can automate common digital collection management tasks in Adobe Creative Suite using Adobe's extended version of Javascript.

Bio
Logan Bingle is a content manager and information professional with a background in design. From 2013 to 2015, he served as a guest correspondent for the Seattle Urban Sketchers, sharing images of Seattle's urban landscape online. He recently worked for the University of British Columbia on copyright issues while earning a Masters of Library and Information Studies.   He continues to publish sketches, managed with Adobe Creative Suite, on his website.

@SketchyTraveler
https://github.com/lbingle
www.binglestudios.com

**Comment by ebrillhart** [comment]
Hey @lbingle this seems really interesting! Would you be free to give this talk at our January 11 or March 8 meetup? Anything after that is currently open as well, if you'd like to present later in the spring or summer!

**Comment by lbingle** [comment]
January 11th would work for me

**Comment by ebrillhart** [comment]
Great! If you "verbally" confirm our CoC (https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) I'll mark this as confirmed!

**Comment by lbingle** [comment]
I agree to the SeattleJS COC. I am looking forward to giving the presentation and attending this month's meetup:)

**Comment by lbingle** [comment]
Hi @ebrillhart, my apologies but I will not be able to make this talk. I just received a great job offer that will require me to  be out of town on the 11th. Again, apologies for the short notice.

**Comment by jefflembeck** [comment]
Hey @lbingle will April work for you?

**Comment by jefflembeck** [comment]
@lbingle are you available for Thursday Feb 8?

**Comment by lbingle** [comment]
@jefflembeck I have recently moved to Oregon to take a job so I will not be able to give this talk until the summer (July, August). I will need to check on my availability to take time off before I can make a commitment. I will update once I know more.

**Comment by bniedermeyer** [comment]
Hi @lbingle - I'm going to close this for now but if you are ever going to be in town and would like to give this talk feel free to re-open this issue or file a new one.
