### ISSUE TITLE
Talk: The Winding Trail of Thought on Coding Challenges: A Story of Getting It Done

### ISSUE THREAD

**Issue by Adron** [seattlejs/seattlejs#112]
*The Talk:* In this talk, I will walk through several JavaScript coding challenges. The mental flow and anguish between choices and implication of those choices as I move through and grow the code base. After a few challenges I'll expand on and turn those challenges into some real life implementations for services and apps. I'll also involve the audience in improving the ideas, ruminate on code for brainstorming, and show a flow between coder mind and the cohort. In the end, I hope to bring a little bit of the joy of coding to people.

*Me:* I’m a jovial, proactive, test & code, code & test, get things done well, software architect, engineer, code monkey, coder, and distributed systems advocate. Some of the things I’ve enjoyed doing over the years; coder, founder, tech recon, and messenger.

* Me: Adron Hall
* [Twitter](https://twitter.com/adron)
* [Github](https://github.com/adron)
* [Website](http://blog.adron.me)

Note: I'll also post slides, addition information, and the prospective code repo and talk notes [here](http://blog.adron.me/talks/the-winding-trail-of-thought-on-coding-challenges).

**Comment by ebrillhart** [comment]
Hey @Adron! Would this be a 15 or 30 min talk (I'm assuming 30?)

**Comment by Adron** [comment]
Hey @ebrillhart your assumption is correct!  :+1: 

It may even push a little past 37 minutes.  ;)

**Comment by ebrillhart** [comment]
@Adron cool! We're getting fairly booked up for the next few months, but we could slot you in as our second speaker for March or later in the spring! Let me know what would work best for you.

**Comment by jefflembeck** [comment]
@Adron Will April work?

**Comment by Adron** [comment]
Hey @jefflembeck sounds good, I'm game for April.  :+1:

**Comment by jefflembeck** [comment]
Hey @Adron for your talk on Thursday, can I get a confirmation that you agree to the code of conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md
