### ISSUE TITLE
Talk Proposal: why npm built a REST framework and how can you

### ISSUE THREAD

**Issue by chrisdickinson** [seattlejs/seattlejs#113]
In November 2015, npm launched a new feature: paid organizations. In the
background, we worked feverishly to support that launch, and it revealed
opportunities for improvement in how we structure our REST services.

Flash forward to December of 2017, and we've applied what we learned from that
launch to 11 of our internal services. These services power everything from
static file queueing to access control lists to billing and more. I'd like to
share the lessons we've learned, how & why we've implemented them as we have,
and how you can benefit from them as well!

By the end of this 30-minute talk you will:

- Get insight into how the npm registry works
- Hear project-level design insights that help a team of 11 people support the
  JS ecosystem (both where we've been right as well as where we've been wrong!)
- Learn how a small team supports 11 million users.
- Get the first look at the tools npm uses to build the registry and its website

* * *

* Chris Dickinson
* [Twitter](https://twitter.com/isntitvacant)
* [GitHub](https://github.com/chrisdickinson)
* [Website](https://www.npmjs.com/)

**Comment by jefflembeck** [comment]
@chrisdickinson can you give me a 👍 here to confirm you've read and agree to the CoC: https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by jefflembeck** [comment]
Thanks @chrisdickinson, it was an amazing talk!
