### ISSUE TITLE
Talk: Alice in Web Animations API Land

### ISSUE THREAD

**Issue by jefflembeck** [seattlejs/seattlejs#114]
Animation is back in the web development tool chest! We know of declarative CSS Animations and Transitions and fully featured JavaScript animation libraries like GreenSock, but there's another option: the Web Animation API!

In this talk Rachel Nabors will take you on a magical journey with Alice from Wonderland to show you how this new API is used to run the CSS Animations in your browser and how you can use it to generate and manipulate animations in your project. Colorful, interactive, useful fun for all disciplines.

Bio:

[Rachel Nabors](rachelnabors.com) began telling stories online as a teenager with her [award-winning web comics](rachelthegreat.com). Her love of web technologies transformed into a career in front end development, where she has worked with Mozilla, the W3C, and Microsoft to build the web forward. She tends the web animation community via the [Animation at Work Slack](slack.animationatwork.com) and her [web animation newsletter](webanimationweekly.com). When she isn't traveling the world, giving talks and kissing puppies, she can be found perched in Seattle, sipping a cup of fancy tea! She recently launched [Animation at Work with A Book Apart](bkaprt.com/animationatwork), a book on the science and challenges of using animation in web and app design to create experiences users will love

![rachel-nabors-color_preview](https://user-images.githubusercontent.com/109699/33899382-30c6078c-df20-11e7-8bd7-0b4e48474fa5.jpeg)

**Comment by jefflembeck** [comment]
@rachelnabors can you give me a 👍 here to confirm that you agree to our CoC: https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by rachelnabors** [comment]
That's a big thumbs up 👍

**Comment by jefflembeck** [comment]
Thanks @rachelnabors !!! It was amazing.
