### ISSUE TITLE
Talk: Dependency injection in JavaScript with InversifyJS

### ISSUE THREAD

**Issue by remojansen** [seattlejs/seattlejs#115]
Hi, I would love to speak at the [upcoming event in March](https://www.meetup.com/seattlejs/events/dczsvkyxfblb/). I can only join the event in March because I live in Ireland but I will be in Seattle at the Microsoft MVP Global Summit. 

I would like to talk about dependency injection in JS powered by [InversifyJS](https://github.com/inversify/InversifyJS) which is an open source library that I've been developing over the past two years. 

Please note that this is meant to be a long talk (**60 minutes**).

Please find more details below:

## Title
Dependency injection in JavaScript with InversifyJS

## Abstract
In this talk, we will learn about dependency injection and dependency inversion and why they are important in JavaScript (and in particular in TypeScript). We will also see some code demos powered by [TypeScript](https://github.com/Microsoft/TypeScript), [InversifyJS](https://github.com/inversify/InversifyJS) and [ZafiroJS](https://github.com/ZafiroJS/zafiro). The demos will demonstrate how the dependency inversion principle can help us to improve the architecture and development experience of our applications.

## Speaker bio
**Remo H. Jansen** is Senior Web Engineer at Stellwagen Technology with several years of experience in web-based technologies. Remo has been awarded the Microsoft Most Valuable Professional (MVP) award in 2016 and 2017 and he is the author of “Learning TypeScript” and the technical reviewer of “Mastering TypeScript” by Packt Publishing. Remo is also an active member of the TypeScript and Open Source communities and the organizer of the Dublin Open Source and Dublin TypeScript user groups.

* [Twitter](https://twitter.com/RemoHJansen)
* [Github](https://github.com/remojansen)
* [Website](http://www.remojansen.com/)

**Comment by jefflembeck** [comment]
@remojansen March it is!

**Comment by remojansen** [comment]
Hi @jefflembeck I can try to get it down to 40 minutes would that be OK?

**Comment by jefflembeck** [comment]
@remojansen Perfect. Thank you.
