### ISSUE TITLE
Talk: Postgres, JSONB and you!

### ISSUE THREAD

**Issue by toddself** [seattlejs/seattlejs#116]
Hi!

I'd love to give a talk on how you can use the JSONB column in Postgres to store denormalized data but still have access to all the wickedly powerful tools that SQL gives you.

Things to cover:
* creating a jsonb schema
* bulk updating jsonb columns
* joining tables via jsonb identifiers
* indexing jsonb

It's not very "javascript" directly -- but the examples will be done in javascript using the node-psql library.

**Comment by jefflembeck** [comment]
@toddself Rad. Will April work?

**Comment by jefflembeck** [comment]
Also, 10 min or 25?

**Comment by ebrillhart** [comment]
Hi @toddself, is this a talk you'd still be interested in giving at some point?

**Comment by bniedermeyer** [comment]
Hi @toddself. I'm going to close this for now - but if you ever feel like you'd like to give this talk in the future feel free to reopen it or file a new issue. We'd love to have you present!
