### ISSUE TITLE
Talk Proposal: A Journey to the Center of the ECMAVerse

### ISSUE THREAD

**Issue by jacobdfriedmann** [seattlejs/seattlejs#117]
## Talk
ES6, ES2018, TC39, stage-3, Test262…what does it all mean!? In this talk, I’ll take you along my journey of just trying to define an acronym. It started with an innocent Google search, it ended in the forums where the future of JavaScript is dreamed up. We’ll look at:
- Define all the acronyms
- Who names these things, anyway?
- How we got here
- The life of a language feature

Plus! Some fun side trips:
- Famous disagreements
- Forgotten features

Do you need to know this stuff to write excellent code? No. However, when I started down this path I felt like JavaScript was something thrust upon me. Now I feel like I am part of the conversation. So can you!

## Me
Jacob Friedmann
Software Engineer @ Rover
- [GitHub](https://github.com/jacobdfriedmann)

**Comment by jefflembeck** [comment]
@jacobdfriedmann _awesome_ . How long of a talk are you thinking? Wanna come in for April or May?

**Comment by jacobdfriedmann** [comment]
Great! Yea, either April or May would work for me. Probably would need 25min to do the topic justice.

**Comment by jefflembeck** [comment]
@jacobdfriedmann another option! How do you feel about doing this talk this week? :D we had a cancellation that I missed

**Comment by jacobdfriedmann** [comment]
Ah if I had seen this at the beginning of the weekend, I would take you up on that! I still need to put the finishing touches on it and I'm not confident I'll have time to do that before Thursday :/

**Comment by jefflembeck** [comment]
@jacobdfriedmann no worries at all!

**Comment by jefflembeck** [comment]
@jacobdfriedmann I'm putting you down for April! Let me know if that doesn't work!

**Comment by jacobdfriedmann** [comment]
👍

**Comment by jefflembeck** [comment]
Hey @jacobdfriedmann for the talk on Thursday, can I get a confirmation that you agree to our Code of Conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by jacobdfriedmann** [comment]
Yes, I agree to the code of conduct 👍
