### ISSUE TITLE
Talk: Why I Was Wrong About TypeScript

### ISSUE THREAD

**Issue by tjvantoll** [seattlejs/seattlejs#118]
# Why I Was Wrong About TypeScript

In 2014, I made a strong argument that TypeScript was destined to be irrelevant and that my company should not use it in any of our projects. I was wrong. In 2018, TypeScript is taking over the JavaScript world, and we now use TypeScript for pretty much everything we build. In this talk we’ll talk a look at why TypeScript succeeded where other compile-to-JavaScript languages like CoffeeScript and Dart have languished. Hopefully the lessons I learned will help you decide whether TypeScript is a good fit for your next project.

* TJ VanToll (Here’s [my bio](https://gist.github.com/tjvantoll/a261e89f28e1362d1c66).)
* [Twitter](https://twitter.com/tjvantoll)
* [GitHub](https://github.com/tjvantoll/)
* [Website](https://www.tjvantoll.com/)

**Comment by jefflembeck** [comment]
So excited to have you, @tjvantoll. Let's put you on for March
