### ISSUE TITLE
Talk: JavaScript Authoring and Debugging in VS Code

### ISSUE THREAD

**Issue by auchenberg** [seattlejs/seattlejs#119]
The way we use and write JavaScript has changed as JS is now running everywhere. I'll walk you through a journey of how we think about JavaScript Authoring and Debugging in VS Code, and hopefully make the case for why VS Code should be your future choice of tool.

Kenneth is a Program Manager at Microsoft on the VS Code team.

https://kenneth.io/about
https://twitter.com/auchenberg
https://github.com/auchenberg

**Comment by auchenberg** [comment]
Should I take the silence as a rejection? 😢

**Comment by ryan-roemer** [comment]
@auchenberg -- I wouldn't 😄. It's a volunteer group of organizers that sometimes get backed up. I'm guessing they'll reach out in due time.

(For reference, I'm one of the organizers of the sister Node.js meetup https://www.meetup.com/Seattle-Node-js/ -- come hit us up at https://github.com/seanode/meetup/blob/master/request-to-speak.md if your team has anything Node.js specific you'd like to chat about!)
