### ISSUE TITLE
Talk: Stop Bickering - The Web is Winning!

### ISSUE THREAD

**Issue by KyleMcNutt** [seattlejs/seattlejs#120]
# Stop Bickering - The Web is Winning!

I can't go one day without reading a new "React Has Won!" or "Angular Has Won!" or "Vue Has Won!" article. In my opinion, we as developers need to stop bickering about who "won" and instead focus on the fact that the web is winning. These technologies are Web based, and that means they can take advantage of each other. Once I finally decided to start practicing this ideal I worked on how to easily integrate React Components with Angular, and got amazing results. Not only is it super easy to take advantage of the awesome React Components out there today in Angular apps, you can build re-usable libraries out of them for the rest of the Angular community to take advantage of, and I’m going to show you how. Stop the in-fighting, and let's integrate so that the web will win!

### Bio:
Hi my name is Kyle, I'm a Software Engineer working at Microsoft to develop the next generation of UX for our Cloud and Enterprise customers. I'm an avid student, who thinks that the web is the ever expanding classroom. I'm also a teacher at North Seattle College where I do my best to pass on what I've learned to the next generation of Software Engineers.

### Links:
* [Slides](http://slides.com/kylemcnutt/deck-1#/) -- From when I gave this talk at the Angular Seattle meetup.

* Kyle McNutt
* [Twitter](https://twitter.com/NuttGuy)
* [Github](https://github.com/KyleMcNutt)

**Comment by jefflembeck** [comment]
@KyleMcNutt awesome. How's May sound?

**Comment by KyleMcNutt** [comment]
@jefflembeck May sounds fantastic!
