### ISSUE TITLE
Talk: Discovering the native JavaScript Audio API

### ISSUE THREAD

**Issue by meslater1030** [seattlejs/seattlejs#121]
# Discovering the native JavaScript Audio API

Have you ever wanted to handle audio related features from within the browser? Did you even know you could? This talk covers the basics on how to create, visualize, record and manipulate sound using native JavaScript. We’ll walk through the creation of a voice modulator and also put together a simple audio visualization. This information will be helpful to JavaScript developers at all levels who are curious about the Web Audio API or who would like to get started on their own audio project but don’t quite know how to get set up.

Megan Slater is an application developer at GeneralUI in Seattle. She has spent the past 2 years as a front-end dev and spent time in an earlier life working as a classically trained musician. Megan leverages her experience in multiple fields to encourage alternate modes of problem solving.

* Megan Slater
* [Twitter](https://twitter.com/meslater1030)
* [Github](https://github.com/meslater1030)

**Comment by jefflembeck** [comment]
OH AWESOME. @meslater1030 how's May sound?

**Comment by meslater1030** [comment]
@jefflembeck Sure! June sounds fine.

**Comment by jefflembeck** [comment]
@meslater1030 WOO!

**Comment by jefflembeck** [comment]
@meslater1030 just a reminder, the talk is on June 14th.

We'll be updating here: https://www.meetup.com/seattlejs/events/dczsvkyxjbsb/

Do you agree to the code of conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by meslater1030** [comment]
@jefflembeck Yup! Looking forward to it. And I absolutely agree to the code of conduct.
