### ISSUE TITLE
Talk: DevTools for Gain and Glory

### ISSUE THREAD

**Issue by AlexLakatos** [seattlejs/seattlejs#122]
# DevTools for Gain and Glory

No, Firefox DevTools are not Firebug. The web came a long way since Firebug, and so have the DevTools baked into Firefox. So let's go exploring! As the complexity of the web apps you build keeps moving, so do the Firefox DevTools. In this session, Alex will give you the latest tips and tricks on Firefox DevTools. We'll explore new and less commonly known features in performan

_Bio:_ Alex Lakatos is a JavaScript Developer Advocate for Nexmo. In his spare time he is a Mozilla Tech Speaker and has been a contributor to the Mozilla project for the past six years, based in London. JavaScript developer building on the open web, he has been pushing its boundaries every day. You can check out his github profile or get in touch on twitter. When he’s not programming, he likes to travel the world, so it’s likely you’ll bump into him in an airport lounge.

* Alex Lakatos
* [Twitter](https://twitter.com/lakatos88)
* [Github](http://github.com/alexlakatos/)
* [Website](http://alexlakatos.com/)

**Comment by jefflembeck** [comment]
Awesome. We spoke about you being in town. Let's get you in as our third for May!
