### ISSUE TITLE
Talk: Building scalable and maintainable web and mobile applications with AWS Amplify

### ISSUE THREAD

**Issue by mlabieniec** [seattlejs/seattlejs#123]
## Overview
Building web and mobile applications, backed by a serverless backend can be challenging using modern JavaScript frameworks. AWS Amplify greatly enhances front-end development experience. Amplify codifies best practices through a programmatic interface to help developers effortlessly interact with cloud resources and modern web APIs.

## Abstract
The Amplify library exposes to you WHAT things do and then HOW best to do them. The WHAT is at a functional use case with HOW being an opinionated implementation that you can override with “escape hatches.” This will allow you to have higher velocity and build better applications by focusing less on implementation choices. Amplify provides developers with a modular and declarative approach to things like authentication and authorization that condenses hundreds of lines of code into single digits.

●	Opinionated implementations: Amplify programmatically helps optimize for cost and performance through library decisions.
●	Declarative actions: Amplify provides you a reference to a generic client object and ability to perform common actions. “RegisterUser”, “Login”, “SendObject”, “UpdateObject”, “StreamData”. 
●	Cascading service interaction: With an opinionated implementation we can decide which Services are "primary" and which are "secondary" depending on what is configured. 
●	Simple, standard data objects: Sending & Receiving data to AWS Services can have many parameters, which tend to show up in the SDKs. These are abstracted and inferred, where possible, with simple JSON that the implementation can reason about. 

## Target Audience
New to intermediate developers building (or maintaining) web and/or mobile hybrid or React Native applications.

## What you'll learn
The audience will learn how to develop web and mobile JavaScript applications using modern frameworks (React, React Native, Ionic/Angular, TypeScript) and AWS Amplify. The talk will provide information and demonstration on how to develop with AWS Amplify within these modern frameworks using mechanisms like Angular providers and subject subscriptions and React / React Native using AWS Amplify UI components and HOCs (Higher Order Components). We will also cover how to instantly update and manage your serverless backend with the AWS Mobile CLI as well as best practices when developing JavaScript or TypeScript based web and mobile applications with a serverless backend, including developing and deploying progressive web applications (PWA).

## Bio
Michael Labieniec
https://www.youtube.com/watch?v=42ouBvpvjBo
https://www.youtube.com/watch?v=unOEnvnsjv4
https://www.youtube.com/watch?v=iZws_5qzfD4

Michael has over 20 years of diversified technology, system architecture, and information technology experience functioning as an Architect, Engineer, Chief Technology Officer, Consultant, Project Manager and other technology development and R/D roles in the insurance, retail, utilities, financial, healthcare, manufacturing, and parking industries. Michael was an innovator and founder of several startups including seedup.io and ParkNow, an engineering consultant for Morgan Stanley and T-Mobile, and joined AWS in February of 2016 as a Sr. Solutions Architect Specialist for AWS Mobile and is now the Software Development Manager for the AWS Amplify and App Development Team.

**Comment by jefflembeck** [comment]
@mlabieniec awesome. How does June sound?

**Comment by mlabieniec** [comment]
@jefflembeck works for me thanks!

**Comment by jefflembeck** [comment]
@mlabieniec just a reminder, the talk is on June 14th.

We'll be updating here: https://www.meetup.com/seattlejs/events/dczsvkyxjbsb/

Do you agree to the code of conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by mlabieniec** [comment]
@jefflembeck thanks. Yes, I agree.
