### ISSUE TITLE
Talk Proposal: Internet Explorer is a Wonderful Browser and an Absolute Pleasure to Work With

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [seattlejs/seattlejs#125]
# Internet Explorer is a Wonderful Browser and an Absolute Pleasure to Work With

_(just kidding, it's terrible)_

In an era dominated by evergreen browsers such as Chrome, Edge, Firefox, and Safari, it's easy as web developers to assume our users are all on modern platforms. Unfortunately, there are quite a few users stuck with IE for reasons out of their control, such as underfunded school districts without the IT resources to migrate or businesses with legacy IE ActiveX plugins. 

After complaining about the prevalence of outdated systems, this talk will go over several strategies for dealing with IE issues. In summary:
* Wrap everything in a try/catch
* Log things
* Don't modify globals
* Stress test
* Sometimes give up
* Enjoy the challenge

[Medium article draft](https://medium.com/@joshuakgoldberg/investigating-internet-explorer-exclusive-bugs-in-javascript-62d43b246a40) (though I'll give the talk with a PowerPoint presentation).

* Name: Josh Goldberg
* [Twitter](https://twitter.com/JoshuaKGoldberg)
* [GitHub](https;//github.com/JoshuaKGoldberg)
* [Website](https://joshuakgoldberg.com)

I'm Josh Goldberg, a front-end dev on [Office Sway](https://sway.com) focusing on the web client. My passion is the modern web but I also enjoy branching out to [weird meta-languages](https://github.com/highschoolhacking/gls), helping bring CS education to everyone, crafting unnecessarily fancy cocktails, and remaking old GameBoy games for the web.

**Comment by jefflembeck** [comment]
@JoshuaKGoldberg how's July's meetup sound?

**Comment by ebrillhart** [comment]
Hi @JoshuaKGoldberg! July 12 still work for you for this talk? If so, can you please note whether you agree to our CoC? Thanks! https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by JoshuaKGoldberg** [comment]
Agh sorry @ebrillhart I _just_ got an email today that I'll be unavailable then! So sorry! Can I jump to the August meetup instead, then?

If this is horribly inconvenient for you I can instead try to get a team member to fill in for me?

**Comment by ebrillhart** [comment]
We'll be holding our annual social in August, but would September work for you? It'll be Thursday the 13th :) No worries, I know schedules change!

**Comment by JoshuaKGoldberg** [comment]
That's my birthday 😦 ... October?

**Comment by ebrillhart** [comment]
Haha no problem. October 11th work?

**Comment by JoshuaKGoldberg** [comment]
Works for me!

**Comment by ebrillhart** [comment]
Awesome! Since you already agreed to our CoC I'll mark you as confirmed and touch base about a month before. Thanks!

**Comment by JoshuaKGoldberg** [comment]
That was fun!

Slides, article link, and associated code snippets here: https://github.com/JoshuaKGoldberg/internet-explorer-is-wonderful/
