### ISSUE TITLE
Learning Redux-Saga

### ISSUE THREAD

**Issue by fraziermork** [seattlejs/seattlejs#126]
Redux-Thunk is a library for managing asynchronous control flows in Redux apps, but it can often lead to deeply-nested callbacks that are difficult to reason about, maintain, or test. Redux-Saga is an alternative based on ES6 generator functions that makes those complex tasks substantially more manageable. That power comes at the cost of a higher learning curve, but don't worry! I'll walk through an introduction to Redux-Sagas and generator functions, explain a bit about how the library works under the hood, and demonstrate some patterns that simplify common tasks.

Bio:
Frazier is a software engineer working to develop the future of writing at Textio. Formerly an experimental condensed matter physicist, Frazier switched careers and learning programming at Code Fellows in Seattle. His other interests include data science, education, and visual art. 

[Github](https://github.com/fraziermork)

**Comment by jefflembeck** [comment]
@fraziermork Hi! I assume you're in for June?

**Comment by jefflembeck** [comment]
@fraziermork  just a reminder, the talk is on June 14th.

We'll be updating here: https://www.meetup.com/seattlejs/events/dczsvkyxjbsb/

Do you agree to the code of conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by fraziermork** [comment]
@jefflembeck I agree--thanks for the info!
