### ISSUE TITLE
Firmware 101: How to Talk to Hardware in Javascript (and have it talk back!)

### ISSUE THREAD

**Issue by Frijol** [seattlejs/seattlejs#127]
# Firmware 101: How to Talk to Hardware in Javascript (and have it talk back!)

## Talk Description
We know that programming comes down to ones and zeroes in the hardware. But how does that translation from human-readable code to electronics actually occur? How do we take an inert off-the-shelf sensor and program it to wake up and produce useful information? As a JavaScript programmer, how do you take the leap from web into working with sensors and interfacing with the physical world through code?

In this 25-minute talk, Kelsey introduces hardware communication as a how-­to-walkthrough from digital signals up to a practical application. In a hands-on demonstration, Kelsey connects a Tessel microcontroller and an accelerometer, decodes their interaction with a logic analyzer, and combs through a datasheet to show the groundwork a firmware engineer does to start two devices talking to each other– all in JavaScript.

### Audience prerequisites: newbies welcome
* No hardware experience is required.
* Relative newbies at JavaScript should be fine with the level of code used here.
* Curiosity encouraged! Please ask questions.

## Bio
Kelsey Breseman is co-inventor of the JavaScript-on-hardware board [Tessel](http://tessel.io) and author of [Node.js for Embedded Systems](http://shop.oreilly.com/product/0636920041504.do) (O'Reilly published). A neural engineer by degree, Kelsey is deeply interested in how people work (from neurons to community creation to organizational structures) and how people work with technology (including the application of open source and work in UX design). She has spent several years speaking around the world about Javascript on hardware and open source. She currently spends most of her time [reading, writing, and thinking about how engineers and entrepreneurs can make a difference in climate change](http://ifoundthemeaningoflife.com/climate-change-book).

* Name: **Kelsey Breseman**
* [Twitter](https://twitter.com/ifoundtheme)
* [Github](https://github.com/frijol)
* [Website](http://ifoundthemeaningoflife.com)

## Extra notes
* June 2018 monthly meetup would be a good time
* This should be a feature-length talk
* This will be essentially the same talk I gave at JSConf Singapore: [see the presentation](https://www.youtube.com/watch?v=H52HezWtmm4&feature=youtu.be)

**Comment by ebrillhart** [comment]
Hi Kelsey! So sorry for the delayed response. I realize you said that June 2018 would be the best time, but would July 12th work for you instead? If not, let me know, and we can hopefully figure out a date later in 2018!

**Comment by Frijol** [comment]
Hi @ebrillhart! It was good to check out the scene & meet you at the June meetup anyway :)

Yes, I'm interested in speaking this fall– October might be better, since I'm traveling until mid-September. Do you have a date for it yet?

**Comment by ebrillhart** [comment]
October's meetup is the 11th, and we'd love to have you if you're free! Let me know if that date works for you.

**Comment by Frijol** [comment]
Yes, October 11 is good! I've marked it on my calendar. See you there!
