### ISSUE TITLE
Lightning! Talk proposal: What is Node.js and why it became so popular?

### ISSUE THREAD

**Issue by trivikr** [seattlejs/seattlejs#128]
# What is Node.js and why it became so popular?

In this talk, I plan to explain how Node.js became possible and how it became extremely popular. It’ll explain what additions JavaScript language needed to have to manage a server and compete with other scripting languages like Perl, Python, Java etc.

A [30-second pitch video](https://youtu.be/iFc_A596nfc) for this talk which I'd shot for another conference.

I'm an SDE with Amazon and have been working on Node.js for last two years
I've been contributing to Node.js core (support for HTTP/2) [since October 2017](https://github.com/nodejs/node/commits?author=trivikr) and became Node.js core collaborator in [March 2018](https://github.com/nodejs/node#collaborators).

* Trivikram Kamat
* [Twitter](https://twitter.com/trivikram)
* [Github](https://github.com/trivikr)

EDIT: Updated title to from "WTF is..." to "What is..."

**Comment by trivikr** [comment]
The [Monthly Meetup on Thursday, June 14, 2018](https://www.meetup.com/seattlejs/events/dczsvkyxjbsb/) doesn't list any speakers.
I would like to give this talk for that Meetup, if possible.

**Comment by ebrillhart** [comment]
Hi @trivikr! Would you be able to give this talk at our July 12th meet up? If not, would September 13th work for you?

**Comment by ebrillhart** [comment]
@trivikr We're having a social/happy hour instead of a regular meet-up in August - would September 13th or October 11th work for you instead?

**Comment by trivikr** [comment]
Yes. September 13th will work for me.

**Comment by ebrillhart** [comment]
Great! If you can note whether you agree to our CoC, then I'll mark you as confirmed for September! https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by trivikr** [comment]
Hi @ebrillhart, I just updated title from "WTF is..." to "What is..." as swearwords are not required/advisable to catch attention of target audience.

Can you please update it in the meeting invite in the description of [September Meetup](https://www.meetup.com/seattlejs/events/dczsvkyxmbrb/)?

**Comment by ebrillhart** [comment]
@trivikr updated!

**Comment by trivikr** [comment]
Thanks!

**Comment by trivikr** [comment]
This lightning talk happened during September Meetup ([event](https://www.meetup.com/seattlejs/events/dczsvkyxmbrb/), [slides](https://slides.com/trivikram/what-is-nodejs), [tweet](https://twitter.com/seattlejs/status/1040413669459468289))
Closing this issue.
