### ISSUE TITLE
Logux: Redux Actions On The Server

### ISSUE THREAD

**Issue by ai** [seattlejs/seattlejs#129]
# Logux: Redux Actions On The Server

What if we can remove all our code for AJAX and instead of AJAX just synchronize Redux actions between client and server and between clients? Or what if our server could create Redux action for the client and client will receive it next online?

Andrey Sitnik, the creator of PostCSS and Autoprefixer will speak about his new open source project, which mixes ideas from Redux, CRDT, and distributed systems to bring you a replacement for AJAX and GraphQL.

* Andrey Sitnik
* [Twitter](https://twitter.com/sitnikcode)
* [Github](https://github.com/ai)
* [Website](https://sitnik.ru)

**Comment by ai** [comment]
I will visit Seattle in July and will be very happy to speak

**Comment by ebrillhart** [comment]
Hi @ai! Does July 12th work for you to give this talk? Also, how long do you expect it to be? Thanks!

**Comment by ai** [comment]
@ebrillhart agreed
