### ISSUE TITLE
CORS Doesn't Hate You

### ISSUE THREAD

**Issue by andryanmiller** [seattlejs/seattlejs#130]
# CORS Doesn't Hate You

CORS (Cross-Origin Resource Sharing) is subject tinged with dread for many web developers, but it doesn't have to be! In this lightning talk, I'll explain both the history of CORS and the logic behind its implementation, as well as a few tips for debugging common CORS errors. (Blog form of this talk [is here](https://frontendian.co/cors).)

Ryan Miller is lead frontend engineer at @algorithmia. Prior to @algorithmia, Ryan built hybrid mobile applications at @chefsteps, and loves learning about the nooks and crannies of the internet.

* Ryan Miller
* [Twitter](https://twitter.com/andryanmiller)
* [Github](https://github.com/andryanmiller)
* [Blog](https://frontendian.co/)

**Comment by ebrillhart** [comment]
Hi @andryanmiller thanks for submitting! How long do you expect this talk to be?

**Comment by ebrillhart** [comment]
Also, would you be available to give this talk at the July 12th meetup?

**Comment by andryanmiller** [comment]
Hey @ebrillhart! Ten minutes or so should work fine, would plan on it being a lightning talk. And if that works, the 12th is great!

**Comment by ebrillhart** [comment]
Awesome! I'll put you down for July 12th. If you can just note whether you agree to our CoC, I'll mark you as confirmed! https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by andryanmiller** [comment]
I agree to the CoC! ⚡️

**Comment by ebrillhart** [comment]
Hey @andryanmiller, just confirming that Thursday still works for you!

**Comment by andryanmiller** [comment]
Yes indeed! See you all then.
