### ISSUE TITLE
Talk Proposal: Functional Programming in JavaScript

### ISSUE THREAD

**Issue by ignu** [seattlejs/seattlejs#135]
Functional programming confers many benefits that can help us write clean code. And much of the power of functional programming is available to us in vanilla JavaScript.

In this talk, we'll explore what functional programming concepts are and how they help us clean up our JavaScript code, as well as looking at FP libraries like Ramda.js.

**Bio** Len Smith has been writing software professionally for eighteen years. A Pennsylvania native, he currently lives in Seattle with his husband and their dog where he writes software and plays board games.

**Length**: I gave a 40 minute version of this talk at Liberty.JS and a 50 minute version at a work lunch-n-learn, but I could also narrow it down to just talk about Ramda for 15 to 20 minutes.

* Name: Len Smith
* Twitter: [twitter.com/ignu](https://twitter.com/ignu)
* Github: [github.com/ignu](https://github.com/ignu)
* Website: [ignu.me](https://ignu.me)

**Comment by ebrillhart** [comment]
Hi @ignu! Would November 8 or December 13 work for you? A 25-30 min version would be awesome if that would work.

**Comment by ignu** [comment]
November 8 works for me!

**Comment by coopy** [comment]
@ignu we're looking forward to having you next week! Could you please comment back saying you've read and agree to our code of conduct?

https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md
