### ISSUE TITLE
MSON Lang: Building An App Using JSON

### ISSUE THREAD

**Issue by redgeoff** [seattlejs/seattlejs#136]
# MSON Lang: Building An App Using JSON

Software continues to eat the world and software development tools are evolving at lightning speeds, but it stills takes an in-depth knowledge of a programming language to develop software. Sure, there are millions of open-source projects that can be mashed together and robust cloud platforms that make the process easier, but it takes considerable skill to get all of these technologies working together. When I envision the future, I imagine the average person being able to make software, just like how the average person can create a spreadsheet today.

This line of thinking has given birth to MSON, an extensible declarative language that can be easily manipulated by a UI. MSON is a subset of JSON and comprised of just a few building blocks, yet it is as powerful as its non-declarative counterparts.

# Bio

Geoff Cox is the creator of [MSON](https://hackernoon.com/creating-a-new-programming-language-that-will-allow-anyone-to-make-software-7a8c73238dc2), a new declarative programming language that will serve as the foundation of a UI that will allow anyone to make software. He’s been self-employed for the greater part of the last 15 years and loves taking on ambitious, yet wife-maddening, projects like creating a database and distributed data syncing system. You can reach him [@redgeoff7](https://twitter.com/redgeoff7) or at [GitHub](https://github.com/redgeoff).

Geoff Cox
[@redgeoff7](https://twitter.com/redgeoff7)
[github.com/redgeoff](https://github.com/redgeoff)
[medium/@redgeoff](https://medium.com/@redgeoff)
[CouchDB Developer Profile](https://blog.couchdb.org/2017/09/20/couchdb-developer-profile-geoffrey-cox/)

**Comment by bniedermeyer** [comment]
Hi @redgeoff - I'm excited to see this. Does November work for you?

**Comment by redgeoff** [comment]
Sure, November works!

**Comment by bniedermeyer** [comment]
@redgeoff Great! Comment back saying you've read and agree to our code of conduct and I'll get you on the calendar. 

https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by redgeoff** [comment]
I've read it and agree
