### ISSUE TITLE
Talk proposal: How can you contribute to Node.js

### ISSUE THREAD

**Issue by trivikr** [seattlejs/seattlejs#137]
# How can you contribute to Node.js

In this talk, I plan to explain how Node.js works!
We'll go through internals of Node.js core, to understand what makes Node run.

Tentative plan:
* We'll go through Node.js HTTP API and write a simple server
* Using time travel debugging, we'll understand the code flow through Node.js internals when an HTTP server is created.
* Then we'll go through how Node.js core code is structured, and find some task where we can contribute.
* And we'll cut a Pull Request with Node core live on stage! :-)

I'm an Software Development Engineer and have been working on Node.js for last 2.5 years
I've been contributing to Node.js core (support for HTTP/2) [since October 2017](https://github.com/nodejs/node/commits?author=trivikr) and became Node.js core collaborator in [March 2018](https://github.com/nodejs/node#collaborators).

* Trivikram Kamat
* [Twitter](https://twitter.com/trivikram)
* [Github](https://github.com/trivikr)

**Comment by bniedermeyer** [comment]
Hi @trivikr! Does November 8th work for you?

**Comment by trivikr** [comment]
Hi @bniedermeyer, Nov 8th doesn't work for me.
If the slot is available, I can do it on December 13th.

**Comment by bniedermeyer** [comment]
Sounds good!

**Comment by trivikr** [comment]
Details about the talk:
* Slides: https://slides.com/trivikram/how-to-contribute-to-node
* Video: https://www.youtube.com/watch?v=GuVEuz_pD5k
