### ISSUE TITLE
Talk Proposal: All About Apps Script

### ISSUE THREAD

**Issue by grant** [seattlejs/seattlejs#138]
# All About Apps Script
Ideally December 13th or January's meetup.

## Description
Google Apps Script is a scripting language based on JavaScript that lets you do new and **cool things** with G Suite products like Docs, Sheets, Slides, and Forms. There's nothing to install — we give you a code editor right in your browser, and your scripts run on Google's servers. In this session, you will learn how to increase the power of your favorite Google apps — like Calendar, Docs, Drive, Gmail, Sheets, and Slides – with Apps Script, a JavaScript platform in Google Cloud.

---

**WHY it's interesting:** Learn how to use JS to automate you're life within Google/G Suite. Apps Script is relatively unknown.
**HOW it'll make you better:** Apps Script is a different way to build an application. 0 OAuth code, serverless, free. Use it casually to automate your business, or simply learn about the unique language design benefits of Apps Script and apply these benefits in your current tech stack.

## Bio
Grant is a developer platform engineer at Google where he leads open source for G Suite APIs. He loves Node, GitHub, and plays the alto saxophone in his spare time.

* Name: Grant Timmerman
* https://twitter.com/granttimmerman
* http://github.com/grant
* http://grant.cm

**Comment by bniedermeyer** [comment]
Hi @grant. This sounds great. If you can confirm you read and agree to our Code of Conduct we'll be good to go for December 13th.

**Comment by grant** [comment]
I agree and appreciate the existence of the CoC.

**Comment by grant** [comment]
@bniedermeyer Can you update https://www.meetup.com/seattlejs/events/dczsvkyxqbrb/?
I will include this event in [G Suite's monthly newsletter](https://developers.google.com/gsuite/newsletters/).

**Comment by bniedermeyer** [comment]
Yep. I'll chat with the person who makes those changes.

**Comment by bniedermeyer** [comment]
@grant yep! We just nailed down the last few details in regards to the location today. It should be updated by the end of the week at the latest.

**Comment by bniedermeyer** [comment]
@grant event description is updated! See you then

**Comment by grant** [comment]
@bniedermeyer Questions:
- How long should the talk be?
- USB C is fine?

**Comment by bniedermeyer** [comment]
@grant we have a USB C to HDMI converter we can use but if you have any converters of your own feel free to bring them. We are following up with the host to see if they've handled such things before.

**Comment by bniedermeyer** [comment]
@grant We just heard back that they do support USB C for their AV system. You should be good to go!
