### ISSUE TITLE
Talk Proposal: Server-side React

### ISSUE THREAD

**Issue by charliewilco** [seattlejs/seattlejs#140]
Server-side rendering a React application can have a lot of moving pieces. We'll look at the basics of server rendering those applications and the needs our applications would have from starting on the server.

**WHY this topic is interesting** most people work on applications that use React and a lot of the bootstrapping of those applications involves using React almost exclusively on the client-side, negating the benefits of server-side rendering.
**HOW it will help** it will give a practical look at the complexities that go into building a React application that renders both client and server.

Charles is a UI Engineer currently working on a large server-side rendered application at Microsoft.

* Charles Peters
* [Twitter](https://twitter.com/charlespeters)
* [Github](https://github.com/charliewilco)
* [Website](https://charlespeters.net/)

**Comment by bniedermeyer** [comment]
Hi @charliewilco Does Nov 8th work for you? 

Also please confirm you read agree to our Code of Conduct. 
https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by charliewilco** [comment]
yes and yes 👍
