### ISSUE TITLE
Lightning! Talk Propsal

### ISSUE THREAD

**Issue by Brandoncyu** [seattlejs/seattlejs#141]
# T.V.O.D. - Sharing your favorite shows in the era of "Peak TV"

T.V.O.D. is a full-stack web platform for users to track what television programs they are watching during this era of "Peak TV." Users can mark what shows they consider their favorites, leave comments and ratings for each episode, and receive a schedule of all episodes upcoming and recently aired. They also have the ability to follow other users and receive updates on what their friends are currently watching.

This app was built primarily using React.js and Express.js. It makes heavy use of the TVMaze API. The talk will focus on how the app was created. It was create as a capstone project for Galvanize Web Development Immersive program. It was recently showcased at the Seattle React.js event to a warm reception.

Bio 
After two-and-a-half years of experience in the non-profit sector, Brandon is excited to transition his career to the growing field of tech. Having learned the languages, frameworks, and computer science fundamentals essential to web development, he looks forward to applying his new skillset and exploring the possibilities it will bring! 

* Brandon Yu
* [Twitter](https://twitter.com/brandonYu)
* [Github](http://github.com/brandoncyu/)
* [Website](http://brandonyuportfolio.com)

**Comment by bniedermeyer** [comment]
@Brandoncyu Does our December 13th meetup work for you? If so, please indicated that you've read and agree to our Code of Conduct and we'll get you on the calendar! https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md
