### ISSUE TITLE
Request to host

### ISSUE THREAD

**Issue by rardoz** [seattlejs/seattlejs#142]
* BCGDV - Seattle (Boston Consulting Group Digital Ventures)
* 411 108th Ave NE, Suite 2100. Bellevue WA 98004
* Downtown Bellevue

I've attended a few meetups with this group and there is a lot of talent and knowledge. After going to the last meetup in November, I heard that Seattle JS is looking for a December host. I thought BCGDV would be a great candidate to host. I've spoken with my recruiting team and they thought that would be a great idea and a good opportunity to recruit some talent and share our identity with the rest of the Seattle dev community.

## Contact Info

robert.greene@bcgdv.com

**Comment by coopy** [comment]
Hi Robert, we are interested! I will email you.
