### ISSUE TITLE
Talk Proposal: Open Source Licenses

### ISSUE THREAD

**Issue by nathandpeterson** [seattlejs/seattlejs#143]
**Everything You Wanted To Know About Open Source Licenses But Were Too Afraid To Ask**

Open source modules have become ubiquitous in the javascript community but the ease and benefits of incorporating packages into software has the potential to hide the real risks of using open source modules in production. This talk discusses the challenges that we have faced with using open source in the context of developing proprietary software.

Our talk describes the pain that we faced by not knowing enough about the world of OSS licenses and lays out what we learned in the process. We discuss why developers should care about licenses, resources available to check the licenses of the packages in their projects, and how those resources fell short of our needs. Finally, we talk about how we resolved the gap between existing solutions and our needs by building a tool for checking software licenses that can be used in a continuous integration pipeline.

This talk was organized by Dan Villa, who will deliver the talk, and Nathan Peterson (me).

Dan Villa has been developing software for eight years in an enterprise setting. He left Boeing 4 years ago and joined the consultant team at Collinear Group. He has worked on the front and back end over the years and now usually does application architecture or project management.
Nathan Peterson has been working as a Software Engineer at Collinear Group for the last nine months.

Here is a link to the project that we have been working on:
https://github.com/CollinearGroup/license-validator

**Comment by bniedermeyer** [comment]
@nathandpeterson Sounds great. Does our Jan. 10th event work for you? Also can you and Dan confirm that you have read and agree to our Code of Conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by nathandpeterson** [comment]
I have read and agree to the Code of Conduct.

**Comment by bniedermeyer** [comment]
Great, does Jan. 10th work?

**Comment by nathandpeterson** [comment]
Yes, that works perfectly. Thanks.

**Comment by bniedermeyer** [comment]
If you two can join or slack I'll add you to our channel for organizing the event. 

http://bit.ly/SeattleJSslack

Just ping me on there after you join and I'll add you to the channel. It's easier for us to keep in touch that way if anything comes up or if you have questions

**Comment by kingnebby** [comment]
Done!
