### ISSUE TITLE
Talk proposal: code-splitting with Webpack

### ISSUE THREAD

**Issue by davidmjiang** [seattlejs/seattlejs#144]
# Code-splitting with Webpack

According to httparchive.org, the median number of kbs of scripts requested by a page has increased from under 100kb in 2011 to over 400kb in 2018.  Including so much JS into our bundle can make our pages slow and give the user a poor experience. One way to help improve our page's performance is code-splitting. We can separate our code into different bundles, sending down only what we need on first load and dynamically loading other bundles when necessary. 

This talk will cover why code-splitting is important, how to implement it with webpack, and then look under the hood to see how dynamic importing works. 

I've been a software engineer at Microsoft for 1.5 years. Currently working on a single page application written with React, Typescript and Webpack that appears as part of the Windows out-of-box-experience.

* David Jiang
* [Github](https://github.com/davidmjiang)

**Comment by bniedermeyer** [comment]
Hi @davidmjiang! Does our Jan 10th meetup work for you? Also can you please read and state you agree to our Code of Conduct? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by bniedermeyer** [comment]
We will be at Boston Consulting in Bellevue I believe. I'll get you an address as soon as everything is finalized. 

If you can join our slack I'll add you to our channel for organizing the event.

http://bit.ly/SeattleJSslack

Just ping me on there after you join and I'll add you to the channel. It's easier for us to keep in touch that way if anything comes up or if you have questions.
