### ISSUE TITLE
Talk Proposal: Comparing Server-side Rendering (CSR) and Client-side Rendering (SSR)

### ISSUE THREAD

**Issue by trivikr** [seattlejs/seattlejs#145]
# Comparing Server Side Rendering (CSR) and Client Side Rendering (SSR)

As defined in the title, in this talk I plan to explain differences between CSR and SSR to identify which one to choose.

Tentative plan:
* We'll examine an isomorphic JavaScript application which can be rendered both Server-side as well as Client-side
* First, we'll understand how SSR works and render the App on the server-side
* Second, we'll understand how CSR works and render the same App on the client-side.
* Then we'll compare the two approaches, and understand in which circumstances you should use SSR/CSR

I'm a Software Development Engineer and have been working on NodeJS for last 3 years
I've been contributing to NodeJS core (support for HTTP/2) [since October 2017](https://github.com/nodejs/node/commits?author=trivikr) and became NodeJS core collaborator in [March 2018](https://github.com/nodejs/node#collaborators).
I'd worked with React and ReactNative back in 2016, and resumed using it in mid-2018.

* Trivikram Kamat
* [Twitter](https://twitter.com/trivikram)
* [Github](https://github.com/trivikr)
* [Website](http://trivikr.github.io)

**Comment by bniedermeyer** [comment]
Hi @trivikr! We generally don't have speakers present at back to back events but would still really like to have you give this talk. Can you do our February 14th event?

**Comment by bniedermeyer** [comment]
March is available as well

**Comment by trivikr** [comment]
February sounds good!

**Comment by bniedermeyer** [comment]
Hi @trivikr. There is a chance that the date may be changed to the following week (2/21). Does that still work for you?

**Comment by bniedermeyer** [comment]
Great!

**Comment by bniedermeyer** [comment]
@trivikr I can't remember if you are on our Slack team or not but if you are I can invite you to a organization channel for February's event. You can join here if you'd like. 
http://bit.ly/SeattleJSslack. Just ping me on there and I can add you to the channel

**Comment by trivikr** [comment]
Thanks for invite @bniedermeyer, but I don't use Slack
