### ISSUE TITLE
Developer Bootcamps - The Good, the Bad, and the Ugly 

### ISSUE THREAD

**Issue by fredricklou523** [seattlejs/seattlejs#146]
With the explosion of developer boot camps, programs like Hack Reactor @ Galvanize are playing a direct role in introducing freshly minted developers into the workforce.  These new developers come from a diverse array of backgrounds, and some of these graduates may end up being your co-workers, develop into leaders when they find their space, or just end up being your statistical competition in an ever-expanding industry.  I want to offer a first-person perspective of the boot camp experience and give you some insight into the folks you may soon be calling your colleagues.  

My name is Fredrick Lou.  I graduated from Texas A&M in 2011 with a degree in Finance.  Over the last 6 years, I’ve worked in management consulting around the IT spaces, helping manage technology software and processes for giants like Exxon Mobile and The Gap, to developing lean project management dashboards for NASA.  This last year, after identifying and struggling with mental stagnation, I took the reins of my personal development and made a sharp left turn in leaving my job in San Francisco and jumping into the Hack Reactor program.  I graduated in October of 2018, and was offered the opportunity to work as an associate instructor and class lead for the cohort graduating in Feb 2019.  

Name: Fredrick Lou
Twitter:  Comming Soon
Github: https://github.com/fredricklou523
Website: Comming Soon

**Comment by bniedermeyer** [comment]
Hi @fredricklou523. This sounds great! Can you make our meetup on Jan 10th?

**Comment by bniedermeyer** [comment]
Also can you please let us know that you have read  and agree to our code of conduct? 
https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by fredricklou523** [comment]
Hi @bniedermeyer.  I can make the meetup on Jan 10th and I've read and agree to the code of conduct!

**Comment by bniedermeyer** [comment]
@fredricklou523 Awesome! Please join our Slack and I'll add you to our dedicated channel for the event. http://bit.ly/SeattleJSslack
