### ISSUE TITLE
Talk Proposal: Dive into Javascript Serverless with Apache Openwhisk

### ISSUE THREAD

**Issue by lidderupk** [seattlejs/seattlejs#147]
# Dive into JavaScript Serverless with Apache Openwhisk

Lets dive into Serverless concepts including Actions and Triggers on the OpenWhisk Serverless open source platform. We will use the wsk command-line tool to create and organize JavaScript functions in packages that can be run on demand. Apache OpenWhisk (Incubating) is an open source, distributed Serverless platform that executes functions (fx) in response to events at any scale. OpenWhisk manages the infrastructure, servers and scaling using Docker containers so you can focus on building amazing and efficient applications.

Upkar Lidder is a Full Stack Developer and Data Wrangler with a decade of development experience in a variety of roles. He can be seen speaking at various conferences and participating in local tech groups and meetups.  He is currently curious about magic behind Machine Learning and Deep Learning, specifically use of NLP in chatbots. Upkar went to graduate school in Canada and currently resides in the United States.

* Upkar Lidder
* [Twitter](https://twitter.com/lidderupk)
* [Github](https://github.com/lidderupk)
* [Website](http://upkarlidder.com/blog/)

**Comment by bniedermeyer** [comment]
Hi @lidderupk does our event on Feb 14th work for you?

**Comment by lidderupk** [comment]
Thanks @bniedermeyer. I am at a conference Feb 12-15. I am open March onwards. Looking forward to presenting to the group. 🙏🏽

**Comment by bniedermeyer** [comment]
@lidderupk March works great! Please confirm that you have read and agree to our Code of conduct and we'll be all set. 
/code-of-conduct.md@master

**Comment by lidderupk** [comment]
Thank you @bniedermeyer. I have read and understand the code of conduct. Looking forward to presenting on March 14. I will confirm once again in mid February.

**Comment by lidderupk** [comment]
Hi @bniedermeyer, is a venue finalized for the 03/14 event ? Thank you !

**Comment by bniedermeyer** [comment]
@lidderupk Yes! It will be at the Indeed offices. Russell Investments Center - 13th Floor
1301 2nd Ave, Seattle, WA 98101

**Comment by bniedermeyer** [comment]
Hi @lidderupk - Can you join our Slack (bit.ly/SeattleJSslack)? I'll add you to our speakers channel so we can keep in contact this week prior to the event. Thanks!
