### ISSUE TITLE
Feb 14 talk proposal: Fantastic fields and how to see them

### ISSUE THREAD

**Issue by anvaka** [seattlejs/seattlejs#148]
# Fantastic Fields and How to See Them

I'd like to prove that boring and scary term `vector field` is, in fact, fantastically beautiful construction that can be seen with help of javascript. 

The topic overlaps concepts from machine learning, javascript and art. I promise to explain math behind it in engaging way and not let anyone fall asleep :). At the end of the talk people will have at least one more powerful tool in their toolset. 

Part of the talk will explain everything beneath https://anvaka.github.io/fieldplay/

My name is Andrei Kashcha. I am passionate about building beautiful visualizations in the browser. 

* [Twitter](https://twitter.com/anvaka)
* [Github](https://github.com/anvaka)
* [Website](https://www.yasiv.com/)

**Comment by bniedermeyer** [comment]
Hi @anvaka sounds great. Can you please confirm you've read and agree to our Code of Conduct and we'll be set!

/code-of-conduct.md@master

**Comment by bniedermeyer** [comment]
Also there is a chance that the date may be changed to the following week (2/21). Does that still work for you?

**Comment by anvaka** [comment]
Read your code of conduct and 100% agree with it.

Unfortunately the following week wouldn't work for me. I have only week with Feb 14 available. And then every other week after that.

**Comment by bniedermeyer** [comment]
Ok! Does our March 14th event work for you?

**Comment by bniedermeyer** [comment]
@anvaka just checking in again. Does our event on March 14th work for you?

**Comment by anvaka** [comment]
Yes! March 14th works for me
