### ISSUE TITLE
Talk Proposal: Designing Data-Driven Visualizations using D3.js

### ISSUE THREAD

**Issue by ahoak** [seattlejs/seattlejs#149]
**Designing Data-Driven Visualizations using D3.js**

There comes a point when drawing data visualizations with simple charting libraries where they no longer suit your needs. Suppose you need to add a median line or add a subcategory on your bar chart. Simple operations like these may not be supported. D3.js is drawing library  that allows you to explicitly define SVG implementations and is a powerful tool in creating complex visuals like graphs. This allows you greater freedom to design custom visuals. D3 has a nontrivial learning curve but this interactive presentation will go over D3 design patterns, working with SVG, and making it sparkle with animation. These are  concepts that you will be able to incorporate into future projects to create custom data visuals.

My name is Amber and I am a Software Engineer at Microsoft Research. My work focuses on data management, analysis, and visualization. I mainly work on creating custom interfaces to show the intersection between artificial intelligence and business intelligence. I design data visualizations to provide insight in large scale datasets and user-experience flows.

https://www.microsoft.com/en-us/research/people/amhoak/
https://github.com/ahoak

**Comment by bniedermeyer** [comment]
Hi @ahoak! Does our event on 2/21 work for you?

**Comment by ahoak** [comment]
Perfect! 2/21 works.

**Comment by bniedermeyer** [comment]
Great! Just take a look over our code of conduct and let us know that you agree and you'll be all set!

https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

Also if you join our slack I can add you to our speaker channel so the organizers can keep in touch with you there. Just use the below link and ping me once you have joined!

http://bit.ly/SeattleJSslack
