### ISSUE TITLE
Lightning Talk Proposal: Office JavaScript APIs

### ISSUE THREAD

**Issue by dmahugh** [seattlejs/seattlejs#150]
# Extend Office 365 with the Office JavaScript APIs

Did you know that you can build solutions that extend Microsoft Office applications and interact with content in Office documents, using the web technologies you already know and use every day? In this talk, we’ll look at how you can use JavaScript to build an Office add-in that’ll run on Windows, Mac, Office Online, iOS, or Android. Topics to be covered include add-in architecture, how to learn the Office JS APIs with Script Lab, and how to create an add-in project using the Yeoman Generator for Office Add-ins.

Doug Mahugh and Kim Brandl are content developers on the Office Platform team at Microsoft, where they’re responsible for creating samples, demos, tutorials, and technical guidance to help JavaScript developers build Office Add-ins. They have spoken on Office development and related topics at Microsoft Ignite, Build, and other developer events.

* Doug Mahugh - [Twitter]( https://twitter.com/dmahugh) -  [Github]( https://github.com/dmahugh)
* Kim Brandl - [Twitter]( https://twitter.com/kbrandl22) - [Github]( https://github.com/kbrandl)
* [Website]( https://developer.microsoft.com/en-us/office)

**Comment by dmahugh** [comment]
Hey @bniedermeyer! Yes, 2/21 works for us - want to plan on that?

**Comment by bniedermeyer** [comment]
Great! If both of you could read/agree to our Code of Conduct we'll get you on the schedule. 

https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

Also feel free to ping me on our slack and I'll add you to the speaker's channel for the event. 

http://bit.ly/SeattleJSslack

**Comment by dmahugh** [comment]
I've read the Code of Conduct and that looks great, and pinged you on Slack. CC @kbrandl to make sure she sees this. Looking forward to the event, thanks!

**Comment by kbrandl** [comment]
Thanks, @dmahugh! @bniedermeyer I've also read (and agree to) the Code of Conduct. I'll ping you on Slack momentarily, so you can add me to the speaker's channel as well. Thanks -- looking forward to speaking on the 21st!
