### ISSUE TITLE
Talk Proposal: A MicroService approach to Modern User Interfaces 

### ISSUE THREAD

**Issue by bencripps** [seattlejs/seattlejs#151]
# Indeed's UI Platform: A MicroService approach to Modern User Interfaces 

At Indeed we're building a platform to help job seekers find jobs, and we've got hundreds of engineers working on that problem. Historically, that's meant we've had a lot of engineers working in monolith applications. And that's meant slower velocity than we'd like.

In this talk, we'll discuss how Indeed is pivoting from monolith web apps to a new approach, where each piece of content is a independent application. We'll cover the high level architecture, and what that means for our users, and our engineers.

* Benjamin Cripps
* [Twitter](https://twitter.com/itsBenCripps)
* [Github](https://github.com/bencripps/)
* [Website](http://www.benjamincripps.com/)

**Comment by bniedermeyer** [comment]
Hi @bencripps - This sounds awesome. I'm assuming you'd like to do this at next weeks meetup right? Just confirm that you've read and agree to our Code of Conduct and you'll be set!

https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by bencripps** [comment]
Yep, and I've read through the code of conduct :)

**Comment by bniedermeyer** [comment]
Hi @bencripps - Can you join our Slack (bit.ly/SeattleJSslack)? I'll add you to our speakers channel so we can keep in contact this week prior to the event. Thanks!

**Comment by bencripps** [comment]
Done!
