### ISSUE TITLE
Talk Proposal: Go Serverless with Google Cloud Functions

### ISSUE THREAD

**Issue by grant** [seattlejs/seattlejs#152]
# Go Serverless with Google Cloud Functions
(Note to @bniedermeyer: Hoping to come back to SeattleJS for another talk!)

> Meetup: [April 11th](https://www.meetup.com/seattlejs/events/dczsvkyzgbpb/)

## Description
Your development agility comes from building systems composed of small, independent units of functionality focused on doing one thing well. Cloud Functions lets you build and deploy services at the level of a single function, not at the level of entire applications, containers, or VMs.

In this session, you will learn the fundamentals about Google Cloud Functions, some use-cases, and how to write Cloud Functions in TypeScript!

## Bio
Grant is a developer platform engineer at Google where he works on developer tools for serverless runtimes. He loves Node, GitHub, and plays the alto saxophone in his spare time.

* Name: Grant Timmerman
* https://twitter.com/granttimmerman
* http://github.com/grant
* http://grant.cm

**Comment by bniedermeyer** [comment]
Hi @grant - sounds great. Looks like April works for you?

**Comment by grant** [comment]
Yeah, April would be great!

**Comment by grant** [comment]
@bniedermeyer 
Can we reschedule this talk for June 13th?
The April and May dates conflict with Google events Next and I/O respectively, which I recently found out I need to attend.

**Comment by bniedermeyer** [comment]
Sure thing

**Comment by bniedermeyer** [comment]
Hi @grant , Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack

**Comment by grant** [comment]
I've joined the Slack group. I'll try to keep it open, but forgive me if I miss a message. I do read GitHub!

**Comment by bniedermeyer** [comment]
@grant just in case you didn't see on Slack our location for 6/13 has changed. We'll be at Galvanize - 111 S Jackson St, Seattle, WA 98104

**Comment by grant** [comment]
Got it, thanks!

**Comment by grant** [comment]
Coming, eta 7!

**Comment by grant** [comment]
@bniedermeyer Before publishing the video, we need to remove the couple frames at the end of the talk of the video where I show this screen:

<img width="410" alt="Screen Shot 2019-06-14 at 10 01 06" src="https://user-images.githubusercontent.com/744973/59525514-62298f80-8e8b-11e9-8544-98c15fa4e7ee.png">

...

**Comment by bniedermeyer** [comment]
@grant yep! I gave Rob a heads up about it last night. How's this?
https://drive.google.com/open?id=1ARGPelOKoQ3L2xrbDe9whL_ueaYDbUMq

**Comment by grant** [comment]
Looks good, thanks!
Could be just 1 second, but it's good as-is too!

**Comment by grant** [comment]
@bniedermeyer If you're sending a follow-up email to attendees, you can send this:

---
Thanks so much for coming! 💖💕💗

👨‍💻👩‍💻TRY our open-source Functions Framework:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs

🎥WATCH our great introductory videos:
https://www.youtube.com/watch?v=1w2t3EWmlVU

🐦TWEET your questions about Cloud Functions:
https://twitter.com/granttimmerman

**Comment by bniedermeyer** [comment]
Got it, Thanks!
*Brenden Niedermeyer*
brenden.niedermeyer@gmail.com
