### ISSUE TITLE
Talk Proposal: Getting Started with GraphQL

### ISSUE THREAD

**Issue by hingham** [seattlejs/seattlejs#153]
#### GraphQL is swell. 
Like REST, graphQL is stateless, cacheable, and will fetch data from a backend server. But GraphQL is also different: unlike REST, graphQL allows the client to shape the data, has a single endpoint, and can fetch all data needed to render a view with one query. 

In this talk, we’ll look at how to get started using graphQL from a new user's perspective. We will see examples of how to use this client friendly query language to build single page apps, and consider how GraphQL can simplify data needs for both frontend and backend developers. 

Hannah Ingham
* [portfolio](hannahingham.com)
* [github](https://github.com/hingham)

**Comment by bniedermeyer** [comment]
Hi @hingham! Can you make our April 11th event? Also please confirm you've read and agreed to our Code of Conduct: https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

Thanks!

**Comment by hingham** [comment]
Hi bneidermeyer,
Yes, I can do April 11! And I can confirm I've read and agree to the code of conduct.
Thanks!
Hannah

**Comment by bniedermeyer** [comment]
Great!
