### ISSUE TITLE
Talk proposal: Dredd is the API Law

### ISSUE THREAD

**Issue by bniedermeyer** [seattlejs/seattlejs#154]
Logging this on behalf of @cmgriffing 

__Dredd is the API Law__
We have all sorts of tests we run on our APIs and applications. There is unit, integration, smoke, regression, end-to-end, accessibility and many more types of testing. But how often do you test your documentation? How would you even do that? Dredd is here to help with that process by making sure your API documentation accurately reflects the current state of the API.

Github: https://github.com/cmgriffing

**Comment by cmgriffing** [comment]
Jst confirming that I agree to the code of consuct.

**Comment by coopy** [comment]
@cmgriffing If you wouldn't mind, could you join our Slack instance so I can invite you to the speakers channel for 4/11? https://bit.ly/SeattleJSslack
