### ISSUE TITLE
Talk Proposal: Service Worker Internals: The good, the bad and the Ugly

### ISSUE THREAD

**Issue by puneetpr** [seattlejs/seattlejs#155]
Service workers are great, provides instant performance, resilience and enhances the web app user experience. But there are few gotchas, I wish I knew them before I messed up and learned. The story of Service Worker implementation, the do's and the dont's.

Twitter handle: https://twitter.com/this__puneet

**Comment by bniedermeyer** [comment]
Hi @puneetpr - Does the May 9th event work for you? Can you also  please add a bio for yourself and confirm you agree to our code of conduct? You can find that here: https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by puneetpr** [comment]
Hi @bniedermeyer, I agree to code of conduct and added the twitter handle.
yes May 9th Works for me.

Thanks,
Puneet

**Comment by bniedermeyer** [comment]
Hi @puneetpr , Can you please join our slack group if you haven't already? That way we can add you to a channel for the event. You can sign up here if you aren't already a member. bit.ly/SeattleJSslack

**Comment by puneetpr** [comment]
Joined. It has a channel q-and-a
