### ISSUE TITLE
Talk Proposal: My First npm Package

### ISSUE THREAD

**Issue by beccalee123** [seattlejs/seattlejs#156]
# My First npm Package

npm packages: we know them, love them, and use them all the time, but have you ever made your own? In this talk, Becca will discuss her experience creating an npm package for the first time (and the rollercoaster of emotions that ensued during the process).

Bio: Becca is a software developer with a background in marketing, who fell in love with the tech industry while working as the marketing manager for a JavaScript consultancy. She is a voracious learner who believes that user-centric development, collaboration, and strong communication help make better software. When she's not coding, you can find her eating ice cream, petting all the dogs, and watching pro wrestling (yes, really).

* Becca Lee
* [Twitter](https://twitter.com/the_becca_lee)
* [Github](https://github.com/beccalee123)

Note: this talk runs between 15 and 20 minutes, but can be rounded up or down as needed!

**Comment by bniedermeyer** [comment]
@beccalee123 can you please confirm you agree to the code of conduct when you have a free second? https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by beccalee123** [comment]
Yes- I agree!
