### ISSUE TITLE
Talk Proposal: EmberJS Octane

### ISSUE THREAD

**Issue by kiwiupover** [seattlejs/seattlejs#157]
[Emberjs](https://emberjs.com) is on the verge of releasing a major update to the framework called [Ember Octane](https://octane-guides-preview.emberjs.com/release/upgrading/editions/). 

I will walk through the highlights of the update. 
Some of the highlights
- New file layout for applications
- Decorators for customizing the behavior of components and other classes.
- Tracked properties, a type of decorator that simplifies keeping the DOM up-to-date with JavaScript changes.
- Native JavaScript classes
- AngleBracket components
- Very smaller component class
- Tree shaking and code splitting 

The focus of the talk would be for people that have not used EmberJS in a long time or ever before.

[@kiwiupover](https://twitter.com/kiwiupover)

**Comment by bniedermeyer** [comment]
Hi @kiwiupover! This looks great. Does our May 9th event work for you? 

Also, please confirm that you've read and agree to our code of conduct. You can find it here:  https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md

**Comment by kiwiupover** [comment]
May 9th looks great!  I have read and absolutely agree with the code of conduct.

**Comment by erichonkanen** [comment]
awesome! looking forward to it

**Comment by bniedermeyer** [comment]
Hi @kiwiupover , Can you please join our slack group if you haven't already? That way we can add you to a channel for the event. You can sign up here if you aren't already a member. bit.ly/SeattleJSslack
