### ISSUE TITLE
Talk proposal: Back To The Browser

### ISSUE THREAD

**Issue by brion-fuller** [seattlejs/seattlejs#158]
# Back To The Browser

In a world of new and ever evolving frameworks, we sometimes forget what platform we are even developing on.  We will take a small journey from static pages => jQuery => AngularJS => Bundlers/Package Managers => Current Day (React, Webpack, Vue, etc..).  We will talk about what each of these where solving that the predecessor couldn't.  Now let's see what the browsers have been up to and how they solve these same issues.

I'm Brion Fuller.  I currently work at Mercedes-Benz Research and Development in Seattle.  I have been in the industry for 5 years mostly working on web application rewrites and designs.

* Brion Fuller
* [Github](https://github.com/brion-fuller)

- [X] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @brion-fuller! This looks great. Does our June 13th event work for you?

**Comment by bniedermeyer** [comment]
Hi @brion-fuller - checking in. Does the June 13th event work for you?

**Comment by brion-fuller** [comment]
Yeah I can do June.

**Comment by brion-fuller** [comment]
I will have to move this out to July.

**Comment by bniedermeyer** [comment]
Ok, no problem!

**Comment by bniedermeyer** [comment]
Hi @brion-fuller. We are going to be skipping this month's event to give us time to focus on our big social next month. We still would love to have you come speak at the next normal event. Could you make September 12th?

**Comment by brion-fuller** [comment]
I will probably have to move this out.  I will be out beginning of September.  I will resubmit for a talk in the future.

**Comment by bniedermeyer** [comment]
Ok, sorry about that! We look forward to having you talk whenever you're available.
