### ISSUE TITLE
Request to host: BCG Digital Ventures

### ISSUE THREAD

**Issue by rardoz** [seattlejs/seattlejs#159]
* BCGDV - Seattle (Boston Consulting Group Digital Ventures)
* 411 108th Ave NE, Suite 2100. Bellevue WA 98004 #2100
* Downtown Bellevue

We had a chance to host the January meetup. Since then we have acquired a new space and we thought SeattlJS might be a great meetup to fill it! We had an amazing time hosting the January meetup, and we heard a lot of people were really excited to learn about BCGDV. We are particularly fond of hosting next months meetup if there isn't someone hosting already. If not, we are pretty flexible with when we host.

## Contact Info

robert.greene@bcgdv.com

**Comment by coopy** [comment]
Response sent in email

**Comment by bniedermeyer** [comment]
closing stale submissions
