### ISSUE TITLE
Talk proposal: "Big Data" Engineering with Node.js

### ISSUE THREAD

**Issue by serv** [seattlejs/seattlejs#160]
# "Big Data" Engineering with Node.js

Can I sign up for a talk in July 2019? Thank you.

## Description

When you think about data engineering, people usually think about using Java or Python as the primary language to work with. While they are fine languages to work with, I want to throw Node.js into the mix as a serious contender to get the job done. Node.js is performant enough to do some heavy lifting and has great NPM packages that help you develop fast. I wanted to share my experience of building data-intensive systems using Node.js.

## Bio

Jason Kim is a software engineer at Coupang. He works on developing the reporting system for Coupang's advertising platform. Outside work, Jason likes to check out restaurants, take photos and work on side projects.

* Name: Jason Kim
* [Twitter](https://twitter.com/jasoki)
* [Github](https://github.com/serv)
* [Website](http://jasonkim.ca/)

- I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @serv ! This looks great. Does our July 11th event work for you? 

Can you please join our slack group if you haven't already? That way we can add you to a speaker channel for communication when the event gets closer. You can sign up here if you aren't already a member. bit.ly/SeattleJSslack

**Comment by serv** [comment]
Hi @bniedermeyer , July 11th works for me.
I signed up for the Slack channel now.
Thanks.
