### ISSUE TITLE
Talk proposal: Interactive isoline routing with React and Leaflet

### ISSUE THREAD

**Issue by dbabbs** [seattlejs/seattlejs#161]
# Interactive Isolines with React, Leaflet, and HERE Location Services

Learn about combining isoline routing and location services into your web application. An isoline is a radius of how far one can travel (car, pedestrian, public transportation) in a given radius (time or distance) based on a road network. 

See example here: https://dbabbs.github.io/isoline-grid

* Dylan Babbs
* [Twitter](https://dbabbs.github.io/isoline-grid)
* [Github](https://github.com/dbabbs)
* [Website](https://github.com/dbabbs)

- [x ] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by dbabbs** [comment]
By the way, I would prefer to do this lightning talk at the May 9 event at Mercedes Benz.

**Comment by bniedermeyer** [comment]
Sounds great! Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack
