### ISSUE TITLE
Talk proposal: Vending Customer Experiences: Autonomy for the Frontend

### ISSUE THREAD

**Issue by goldhand** [seattlejs/seattlejs#162]
# Vending Customer Experiences: Autonomy for the Frontend

The frontend is often pigeonholed into a monolith architecture by different forces. Many technology decisions are prescribed and releases must be scheduled. Large applications with weak module boundaries are difficult to maintain and often become a big ball of mud. We need to strive for true autonomy, from end to end, from database to user interface.

We will review challenges of designing, as well as examine patterns for implementing—an architecture that allows teams to independently own features end-to-end, make their own technology decisions and manage release cycles independently.

Over 20 engineers, designers and managers working in this problem space on teams across Amazon were interviewed while researching the content of this talk.

## Bio
Will joined Amazon in 2016. As a Senior Frontend Engineer, he has lead multiple projects within Retail. He emphasizes the importance of staying on top of trends in frontend technology and has effectively introduced many new architectures to platforms at Amazon.

* Will Farley
* [Twitter](https://twitter.com/aWillFarley)
* [Github](https://github.com/goldhand)
* [Website](https://www.willfarley.org/)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @goldhand! Does our June 13th event work for you?

**Comment by goldhand** [comment]
That works for me. Do you prefer github for communication or is there a contact I can email for additional details?

**Comment by bniedermeyer** [comment]
Can you join our Slack group? That way we can add you to a channel for the event. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack
