### ISSUE TITLE
Global State in React with Hooks

### ISSUE THREAD

**Issue by JoseHerminioCollas** [seattlejs/seattlejs#164]
# Global State in React with Hooks

Min Hooks is an exploration of global state with React and Typescript. 
An application, Widget Name is used to illustrate functionality such as saving and updating state.

Hooks are built into React and will probably be around for a while. 
Typescript, a superset of JavaScript is another powerful tool for moving forward in the web world.
This application can be used as a reference or for further experimentation.

Ideally, you will walk away from this short talk with a better sense of global state in React

The Github repository for the project is here:

* [Min Hooks on Github](https://github.com/JoseHerminioCollas/min-hooks)

I am Jose Collas. I studied photography at the Rochester Institue of Technology, where I learned how to use chemistry to record data.
Since then, I have always been involved in the process of how things are made and not just the thing itself.

My web site is 
* [goatstone.com](http://goatstone.com)

My Github repositories
* [Goatstone](https://github.com/goatstone)
* [Jose Collas](https://github.com/goatstone)

- [X] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @JoseHerminioCollas ! This looks great. Does our July 11th event work for you?

**Comment by bniedermeyer** [comment]
Hi @JoseHerminioCollas - We are going to be skipping this month's event to give us time to focus on our big social next month. We still would love to have you come speak at the next normal event. Could you make September 12th?

**Comment by bniedermeyer** [comment]
Hi @JoseHerminioCollas Can you make our September 12th Event?

**Comment by bniedermeyer** [comment]
Hi @JoseHerminioCollas, I'm going to close this for now as it looks like we're having trouble connecting. Feel free to re-open it when you are available - we'd love to have you speak.

**Comment by JoseHerminioCollas** [comment]
Hello, I did not see this conversation! I can do this lightning talk this eve.

**Comment by JoseHerminioCollas** [comment]
great thanks!

**Comment by bniedermeyer** [comment]
No problem! Like I said if you need any feedback on stuff feel free to send an outline or something my way - contact@brenden.dev

**Comment by bniedermeyer** [comment]
Hi @JoseHerminioCollas, Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. http://bit.ly/SeattleJSSlack
