### ISSUE TITLE
Talk proposal: Streams in Node.js

### ISSUE THREAD

**Issue by trivikr** [seattlejs/seattlejs#165]
# Streams in Node.js

As defined in the title, in this lightning talk I plan to explain how [streams](https://nodejs.org/api/stream.html) work in Node.js
As part of this talk, we'll first understand what streams are and then go through an example application to understand how they work

I'm a Software Development Engineer and have been working on Node.js for last 3 years
I maintain [AWS SDK for JavaScript](https://docs.aws.amazon.com/sdk-for-javascript/index.html), which involves working with Node.js streams

* Trivikram Kamat
* [Twitter](https://twitter.com/trivikram)
* [Github](https://github.com/trivikr)
* [Website](http://trivikr.github.io)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @trivikr, happy to have you back! Does our October 10th event work for you?

**Comment by trivikr** [comment]
Hi @bniedermeyer, I haven't made plans for October yet.
I'll respond in this issue closer to the date, if slots are still available.

**Comment by trivikr** [comment]
Closing in favor of HTTP/3 talk in #174
