### ISSUE TITLE
Talk proposal: Humanizing Your Documentation

### ISSUE THREAD

**Issue by carolstran** [seattlejs/seattlejs#166]
# Humanizing Your Documentation

**_Abstract_**
It’s no secret that most people don’t read technical documentation for pleasure. Users often come to your docs when they are frustrated with your software, disappointed that they haven't been able to solve the problem on their own and generally feeling pretty low. This is sad, sure, but being aware of these feelings is key for developers and technical writers alike. These emotions frame the reader’s perspective and therefore, should shape the mood of our docs.

In this talk, we’ll discuss how the language we use affects our users and the first steps towards writing accessible, approachable and use case-driven documentation.

📆 _As I mentioned over Twitter DMs, I'm only available for the December meetup because that's when I'll be home for the holidays._

⚡️  _I'm also happy to give this talk as a lightning talk._

**_Bio_**
Carolyn (she/her) is a frontend developer and former journalist based in Berlin, Germany. She’s best known for her work around technical documentation, as well as that one time she built a brussel sprouts-themed browser extension. Outside of work, she’s a Mozilla Tech Speaker and co-organizer of the BerlinJS and QueerJS meetups. 

* Carolyn Stransky
* [Twitter](https://twitter.com/carolstran)
* [Github](https://github.com/carolstran)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Sounds great. We don't often have a lot of talks around testing. See you in December!

**Comment by carolstran** [comment]
Hello again! 

I have a quick question for you... would it be possible to switch my topic? Looking at my schedule the next month and considering the fact I just switched jobs, I don't think I'll realistically be able to write a new talk in time.

I have a few other talks that could also maybe fit your audience. I'll list them below and then you can let me know what you think? But of course, if none of them fit then I can give my speaking slot to someone else.

[Humanizing Your Documentation](https://github.com/carolstran/tech-talks/blob/master/abstracts/humanizing-your-docs.md)
["Intuitive" Tooling](https://github.com/carolstran/tech-talks/blob/master/abstracts/intuitive-tooling.md)
[Life is hard and so is learning GraphQL](https://github.com/carolstran/tech-talks/blob/master/abstracts/learning-graphql.md)
[A11y-Friendly Documentation](https://github.com/carolstran/tech-talks/blob/master/abstracts/a11y-friendly-docs.md)
Or I also have a [lightning talk on self-care](https://github.com/carolstran/tech-talks/blob/master/abstracts/the-most-important-ui.md)

Thank you in advance for understanding!

**Comment by bniedermeyer** [comment]
@carolstran Absolutely. Is it possible to do the humanizing documentation talk in 20-25 minutes? If not the intuitive tooling one also sounds great.

**Comment by carolstran** [comment]
Ahhhh great, thank you for being so understanding 💙

I can certainly do the docs one in 20-25 minutes! Let's plan for that then? Should I update the issue?

**Comment by bniedermeyer** [comment]
Sure, that would be great. Thank you!

**Comment by carolstran** [comment]
Hey @bniedermeyer, I've given it a lot of thought and I'd rather withdraw from speaking at the meetup entirely. While it would've been a great opportunity to speak at SeattleJS, I'm not in the US very often and I want to be able to spend as much time with friends and family as possible. I'm sorry to jerk you around, but I hope you can understand.

Closing this issue now, but maybe see you in the future 👋

**Comment by bniedermeyer** [comment]
No worries, hope something works out in the future!
