### ISSUE TITLE
Talk proposal: Get Stuff Done with Google Cloud Tasks

### ISSUE THREAD

**Issue by grant** [seattlejs/seattlejs#167]
# Get Stuff Done with Google Cloud Tasks

Google Cloud Platform has a wide array of convenient tools to help scale the technical infrastructure of your business.

In this talk, we'll talk about [Google Cloud Tasks](http://cloud.google.com/tasks), which allows you to schedule _millions_ of "Tasks" for Google Cloud to execute code asynchronously.

It's extremely scalable, configurable, cost-effective (first 1M are free), and perfect for microservice architectures.

Cloud Tasks became Generally Available at Google Cloud Next this year and is ready for production usage.

---

Constraints: I can only speak for the [August 8th meetup](https://www.meetup.com/seattlejs/events/clmbzqyzlblb/).

* Name: Grant Timmerman
* [@granttimmerman](https://twitter.com/granttimmerman)
* [github.com/grant](http://github.com/grant)
* [grant.cm](http://grant.cm)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

CC: @bniedermeyer

**Comment by bniedermeyer** [comment]
Hi @grant. Our August event is actually going to be on the 21st and will not be having any talks as it's our annual social (you're welcome to join us!). Let us know next time you're in town!

**Comment by grant** [comment]
Oh, understood, thanks for the update.
