### ISSUE TITLE
Talk proposal: JavaScript is Weird. We Love JavaScript

### ISSUE THREAD

**Issue by sevilayha** [seattlejs/seattlejs#169]
# JavaScript is Weird. We Love JavaScript

In today's JavaScript land, we often skip straight to the fun libraries like React and Vue. This leaves a few gaps in our base JavaScript knowledge. 

Let's take a step back and focus on JavaScript itself. We'll go over some of the most misunderstood parts of JavaScript like:

- hoisting
- scope
- this
- coercion

### Who is this?

Chris on Code is the founder of web dev tutorial site [scotch.io](https://scotch.io). He's a Google Developer Expert focused on performance and fighting to keep the dev life simple.

* Chris on Code
* [Twitter](https://twitter.com/chrisoncode)
* [Github](https://github.com/sevilayha)
* [Website](https://scotch.io)

- [ ✅ ] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Excited to see this. See you in September!
