### ISSUE TITLE
Talk proposal: Browser Crypto APIs

### ISSUE THREAD

**Issue by jasonnutter** [seattlejs/seattlejs#170]
# Browser Crypto APIs

_(WIP title)_

## Abstract

Did you know your web browser is capable of performing cryptographic operations, such as generating keys, encrypting and signing data, and more? In this talk, I'll give an overview of the browser `crypto` APIs, and showcase some practical scenarios by detailing how Microsoft is using these APIs to build more secure experiences for our customers.

## Biography

I am currently a software engineer at Microsoft, where I work on OSS for Azure Identity, namely the [Microsoft Authentication Libraries for Javascript](https://github.com/AzureAD/microsoft-authentication-library-for-js). I am also a guest lecturer in the University of Washington, where I teach client-side web development in the [UW Information School](https://ischool.uw.edu). 

* Jason Nutter
* [Twitter](https://twitter.com/jasonnutter)
* [Github](https://github.com/jasonnutter)
* [Website](https://jasonnutter.com)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @jasonnutter! This looks great. Does our September 12th event work for you?

**Comment by jasonnutter** [comment]
@bniedermeyer Yes, the September event works for me. Thanks!

**Comment by bniedermeyer** [comment]
Hi @jasonnutter, Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. Feel free to ping me once you join. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack

**Comment by jasonnutter** [comment]
@bniedermeyer Joined!
