### ISSUE TITLE
Talk proposal: CushionDB: a Database for Progressive Web Apps

### ISSUE THREAD

**Issue by drote** [seattlejs/seattlejs#172]
CushionDB: a Database for Progressive Web Apps

(cushiondb.github.io)
CushionDB is an open-source offline-first database that uses PWA tools in order to achieve syncing to and from the database in the background, when the app is closed. The talk includes a broad overview of the PWA Toolkit, an examinations of the data structure, syncing and authentication design patterns in the offline first world, and finally an overview of CushionDB and how it utilizes PWA tools to achieve native-like syncing abilities.

The main focus of the talk is educating and informing fellow developers about the browser tools and design patterns of the offline-first/PWA world that enable web developers create native-like apps using JavaScript, HTML and CSS.

The talk is quite dense so 20 mins would be perfect, but a 10 minute talk would, of course, be great as well.

Bio
My name is Daniel, a software engineer currently living in Seattle. I am currently working as a freelance full stack web-developer, and I have, up until recently, been working on CushionDB with 2 fellow engineers across the US.

I have been programming and expanding my programming abilities for the past 2 years, and have studied web development remotely with Launch School - an online, mastery-based, web development program.

Thank you for reading!
Daniel Roth

https://github.com/drote
cushiondb.github.io

- [X] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @drote Are you available for our November 14th or December 12th events?

**Comment by drote** [comment]
November 14th would be great!

**Comment by bniedermeyer** [comment]
Hi @drote, Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. http://bit.ly/SeattleJSSlack

**Comment by drote** [comment]
Hey Branden! I'm already a member of the slack group as Daniel Roth.
