### ISSUE TITLE
Talk proposal: Using Next.JS & Github to build static sites (and never pay for hosting again!)

### ISSUE THREAD

**Issue by evantahler** [seattlejs/seattlejs#173]
# Using Next.JS to build static sites (and never pay for hosting again!)

## Overview

Next.js is a static & dynamic site rendering tool for websites based on React.  We can use Next.js to flatten and build static sites for us using React.  We can then upload these packs to Github Pages for a freely hosted website.  This talk will focus less on the React part of things, and more on the "devops" tools we use to build and host the site - Next, Circle.CI, and Github Pages

This is how we build www.actionherojs.com, and have an open-souce example here https://github.com/actionhero/www.actionherojs.com

## Bio

Most recently, Evan was the Chief Product Officer at Voom, an Airbus Company, providing an urban air mobility to cities around the world.

Evan has deep expertise in building the technical side of B2C products as well as the teams required to do so. He’s helped companies like Disney, TaskRabbit, ModCloth, and Airbus launch new global digital initiatives. He is named on a number of patents focusing on mobile interactions and digital entertainment. Evan is an open-source innovator, and frequent speaker at software development conferences focusing on Product Managment, Node.JS, Rails, and databases.

Evan holds a Masters in Entertainment Technology and BS in Mechanical Engineering from Carnegie Mellon University.

* Evan Tahler
* @evantahler (twitter + Github)
* www.evantahler.com

---

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. Feel free to ping me once you join. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack
