### ISSUE TITLE
Talk proposal: HTTP/3: Node.js can do QUIC

### ISSUE THREAD

**Issue by trivikr** [seattlejs/seattlejs#174]
# Title of talk

The QUIC and HTTP/3 protocols are currently being developed by the IETF. While they are busy working, we've been busy working on an implementation within Node.js core. This presentation will introduce the protocol and the implementation and update on where things are at!

I'm a Software Development Engineer and have been working on Node.js for last 3 years
I maintain [AWS SDK for JavaScript](https://docs.aws.amazon.com/sdk-for-javascript/index.html)

* Trivikram Kamat
* [Twitter](https://twitter.com/trivikram)
* [Github](https://github.com/trivikr)
* [Website](http://trivikr.github.io)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by trivikr** [comment]
@bniedermeyer I know it's a little late, but is it possible to move [SeattleJS October meetup](https://www.meetup.com/seattlejs/events/clmbzqyznbnb/) to a different date?

Reason: Seattle TypeScript meetup is on [Oct 10th](https://www.meetup.com/seattle-ts/events/264757065/), and some SeattleJS fans might like to attend it.
This is a one-time exception from them as [TSConf](https://tsconf.io/) is on October 11th

**Comment by bniedermeyer** [comment]
I'll bring it up with the other organizers. It will kind of depend on our sponsor and whether their schedule allows for it.

**Comment by trivikr** [comment]
Thanks! As a speaker I'm good with most days in October
Preference for Thursday Oct 17th

**Comment by trivikr** [comment]
Hi @bniedermeyer, any update on possibility of change of dates for October meetup?

**Comment by bniedermeyer** [comment]
Still working on seeing if it's possible. I'd say until I hear otherwise assume that we are keeping the 10th.

**Comment by bniedermeyer** [comment]
We won’t be able to reschedule the event. Are you still able to make it?

**Comment by trivikr** [comment]
What's the location?
It still says TBD at https://www.meetup.com/seattlejs/events/clmbzqyznbnb/

**Comment by coopy** [comment]
The Location will be Ookla (downtown Seattle). Meetup page will be updated
this week.

**Comment by trivikr** [comment]
Thanks! I will be able to speak at the event on Oct 10th
