### ISSUE TITLE
Talk proposal: Make your applications faster by using AWS JavaScript SDK v3

### ISSUE THREAD

**Issue by ajredniwja** [seattlejs/seattlejs#176]
The AWS SDK for JavaScript enables developers to build libraries an applications that use AWS services. You can use the JavaScript API in the browser and inside Node.js applications on the server. The v3 is now modular and has been written in TypeScript. In this talk, we'll understand how to make your application faster by using this modularized version of AWS JavaScript SDK”

I am currently working as a primary developer support engineer AWS JavaScript SDK. 
I support [AWS SDK for JavaScript]( https://docs.aws.amazon.com/sdk-for-javascript/index.html)

* Ajwinder Singh
* [Github](https://github.com/ajredniwja)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @ajredniwja! This looks great. Does our October 10th event work for you?

**Comment by trivikr** [comment]
Update: @AllanFly120 will be the primary speaker for this talk, and Ajwinder would be assisting him.

* Allan Zheng
* [GitHub](https://github.com/AllanFly120)
* [Twitter](https://twitter.com/allanzhengyp)

We're waiting to get this talk approved from AWS, and will respond once we get approval.

**Comment by trivikr** [comment]
I confirm on behalf of @AllanFly120 and @ajredniwja that October 10th event works for us.

We would like to request for the following [schedule](https://www.meetup.com/seattlejs/events/clmbzqyznbnb/):
* 6:50pm to 7:15pm:
  * Title: Make your applications faster by using AWS JavaScript SDK v3
  * Speaker: Allan Zheng and Ajwinder Singh
  * Description: The AWS SDK for JavaScript enables developers to build libraries and applications that use AWS services. You can use the JavaScript API in the browser and inside Node.js applications on the server. The v3 is now modular and has been written in TypeScript. In this talk, we'll understand how to make your application faster by using this modularized version of AWS JavaScript SDK
* 7:20pm to 7:45pm:
  * Title: HTTP/3: Node.js can do QUIC
  * Speaker: Trivikram Kamat
  * Description: The QUIC and HTTP/3 protocols are currently being developed by the IETF. While they are busy working, we've been busy working on an implementation within Node.js core. This presentation will introduce the protocol and the implementation and update on where things are at!

**Comment by ajredniwja** [comment]
Thank-you for confirming @trivikr. The schedule looks great, looking forward to it.

**Comment by AllanFly120** [comment]
Hey thank you @trivikr @ajredniwja! I will give the talk with Ajwinder!

**Comment by bniedermeyer** [comment]
Sounds great, we'll update our schedule!
