### ISSUE TITLE
Sponsor request: Testim

### ISSUE THREAD

**Issue by francisadanza** [seattlejs/seattlejs#177]
# Testim

A short explanation of why you'd like to sponsor. Are you looking to hire? Want feedback from devs? 1-2 paragraphs is fine.

We have a job opening for a dev evangelist that I'd like to promote. We would also like to promote webinars and free trials of our product. 

## Contact Info
francis@testim.io 

How can we reach you? Email or Twitter is fine.

**Comment by coopy** [comment]
Hi, @francisadanza. Thank you! We will send an email to follow up.

**Comment by bniedermeyer** [comment]
closing stale submissions
