### ISSUE TITLE
Talk proposal: Client-side OAuth with PKCE

### ISSUE THREAD

**Issue by stmcallister** [seattlejs/seattlejs#178]
# Client-side OAuth with PKCE

The OAuth standard has been around for a while, but traditionally it has required a back-end server to hold a client secret, well, secret. Managing secrets can be a very hard problem to solve. Until now! By supporting Proof Key for Code Exchange, or PKCE, OAuth flows can now be accomplished entirely in the client--and still be secure. In this talk we begin the standard three-legged flow and then introduce PKCE. By the time you leave, you will understand how to implement it in your client applications and the benefits for doing so.

I have been building web applications in several industries for over a decade. Now, as a Developer Advocate for PagerDuty, I love helping others learn about a wide range of web technologies. I recently discovered PKCE, and after using it in a project, thought it would be a cool topic to share. When I’m not coding, writing or on stage speaking I enjoy long walks with my wife, skipping rocks with my kids, and is happy whenever Real Salt Lake can manage a win.

* Scott McAllister
* [Twitter](https://twitter.com/stmcallister)
* [Github](https://github.com/stmcallister)
* [Website](https://stmcallister.github.io)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @stmcallister! This looks great. Does our November 14th event work for you?

**Comment by stmcallister** [comment]
@bniedermeyer November 14th works for me! Do you have a time and location set at this point?

**Comment by stmcallister** [comment]
Just checked the meetup page. Apparently, it's 6-9pm. :)

**Comment by bniedermeyer** [comment]
Yep! We are still working out the host details. If you haven't already, join our Slack. That way we can add you to a channel for the event for better communication. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack

**Comment by stmcallister** [comment]
That slack invite link seems to have expired. :)

**Comment by bniedermeyer** [comment]
oh weird, I worked for me. Do you have an email you want me to send an invite to?

**Comment by stmcallister** [comment]
Interesting. Try stmcallister@gmail.com
