### ISSUE TITLE
Talk proposal: Making music with ToneJS

### ISSUE THREAD

**Issue by colinlgray** [seattlejs/seattlejs#180]
### Making music with tonejs

In this talk I am going to go over my favorite new library: [tonejs](https://tonejs.github.io). For a long time I have been making applications to do important work, or at least work that has concrete acceptance criteria. Recently I wanted to do something that is low stakes and would allow for creativity while coding. Then I stumbled upon tonejs.

This talk will probably not get you a promotion at your job, or even teach you a new architecture. My goal with this talk is to show that JS can be used for art and creativity along with practicality.

The talk will consist of me going step by step through creating a synthesizer, triggering the synth to make sounds, then attaching those sounds to a time signature, then making a loop of sounds to give something resembling a beat. I will finish off the talk by showing the options and possibilities that tonejs can give you for more creativity such as visualizers and oscillators.

About myself, I have written code professionally for about 7-8 years. I'm currently taking some time off of working at a tech job but am still writing code for fun in my spare time. This library has provided me with a lot of joy and I would like to share that with the rest of the community. I would say that I am qualified to do this only because I have built what I talked about above. I will warn it does have some issues, but in general it does what I want and since my goal is to just have fun I am not sweating the small things. The small app I built can be found [here](https://github.com/colinlgray/sound-board) 

* Colin Gray
* [Twitter](https://twitter.com/ColinIsOnLine)
* [Github](https://github.com/colinlgray)

- [✔️] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @colinlgray 
Our lineup is set for November already. Are you going to be available for our December 12th event? Or would January work better?

**Comment by colinlgray** [comment]
December 12 should work for me. I'll be getting back from ReactDayBerlin around then so I might be jet lagged but hopefully I'll have some cool news to share from the event
