### ISSUE TITLE
Talk proposal: Observable Notebooks

### ISSUE THREAD

**Issue by ahoak** [seattlejs/seattlejs#181]
# Observable: The magic notebook for exploring data

Observable notebooks are an exciting, new, free web-based platform that perform very similarly to Juypter notebooks for python. These notebooks allow developers to easily import and compute data in JavaScript without a framework. Observable provides a live-coding experience and is a great place for learning, sharing code or building your portfolio. They also provide features for developers to fork, edit, comment, suggest and merge on a current notebook. In this lightning talk, I will go over getting started with Observable notebooks, some gotchas, and creative examples for inspiration. 

Amber Hoak works at Microsoft Research in Special Projects group. Her work focuses on data management, analysis, and visualization. She presented a Data Visualization workshop at the largest women based technology conference, Grace Hopper Conference, in October with all content hosted on Observable ( https://observablehq.com/@project-essex/d3-workshop ). 

* Amber Hoak
* [Twitter](@amber_hoak)
* [Github](https://github.com/ahoak)
* [Website](https://www.microsoft.com/en-us/research/people/amhoak/)

- [ X] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Sounds great! Does December 12th work?

**Comment by ahoak** [comment]
Yes, December sounds good!

**Comment by ahoak** [comment]
@bniedermeyer  can I move this talk to January? I have work conflict with Dec 12th.

**Comment by bniedermeyer** [comment]
Yep no problem!

**Comment by bniedermeyer** [comment]
@ahoak - We've had to cancel this month's event. Can you make Feb 13th?

**Comment by ahoak** [comment]
Yes Feb works.

**Comment by bniedermeyer** [comment]
Great!
