### ISSUE TITLE
Talk proposal: Modern State Management for a Functional React

### ISSUE THREAD

**Issue by koryteg** [seattlejs/seattlejs#183]
# Modern State Management for a Functional React

State management in React has been difficult to get right since its inception. Over the years developers have build libraries to help with this, such as Redux, Mobx and Context API. As patterns have changed, React has become more functional in its programming style. The core team has added functional components and `hooks` to manage state for them. The `useState` hook can get you pretty far, but how do you manage state across a large Functional React app as it grows? 

In this talk I will go over: state management pitfalls and patterns I have used to keep code clean, readable and maintainable on large React applications. 

Bio: My name is Kory Tegman, I am a Senior Software Engineer at [Echobind](https://echobind.com), I have been writing full stack web applications for 8 years and JavaScript for 10. 

* Kory Tegman
* [Twitter](https://twitter.com/koryteg)
* [Github](https://github.com/koryteg)
* [Website](http://blog.korytegman.com)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
hi @koryteg. Can you make our December 12th event?

**Comment by koryteg** [comment]
yes! can make it to that date!

**Comment by bniedermeyer** [comment]
Awesome! Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSSlack

**Comment by koryteg** [comment]
Ok sounds good I joined!
