### ISSUE TITLE
Talk proposal: Microsoft Authentication Library for JavaScript - State of the Union

### ISSUE THREAD

**Issue by jasonnutter** [seattlejs/seattlejs#184]
# Microsoft Authentication Library for JavaScript - State of the Union

The Microsoft Authentication Library for JavaScript (MSAL.js) enables client-side web applications to authenticate users using Azure Active Directory for work/school accounts, personal Microsoft accounts, and social identity providers such as Facebook, Google, etc. It also enables your application to acquire access tokens for services such as the Microsoft Graph and your own custom web APIs.

In this talk, I will give an overview of the library, talk about the work we've have been doing this year, and give insight into the work we have planned for the upcoming year (e.g. Auth Code flow, updated MSAL Angular wrapper, etc.).

https://github.com/AzureAD/microsoft-authentication-library-for-js

P.S.: We're hiring!

* Jason Nutter
* [Twitter](https://twitter.com/jasonnutter)
* [Github](https://github.com/jasonnutter)
* [Website](https://jasonnutter.com)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by jasonnutter** [comment]
I noticed there isn't a third talk yet for 12/12, I'd be happy to fill that slot if it's still vacant. Thanks!

**Comment by jasonnutter** [comment]
(This could also be done as a lightning talk.)

**Comment by bniedermeyer** [comment]
Hi @jasonnutter! So sorry it took me so long to get back to you. We took January off so are now getting back into the swing of things. We have talk openings for next Thursday, or in April on the 9th. Which would work out better for you?

**Comment by jasonnutter** [comment]
@bniedermeyer No worries. I'm actually reconsidering this talk proposal, I have a couple other topics that might be more worthwhile. I'll follow up soon.

**Comment by bniedermeyer** [comment]
Sounds good. thanks for the update!

**Comment by bniedermeyer** [comment]
@jasonnutter  I'm going to close this out for now - feel free to reopen it if you decide you want to give this talk! thanks!
