### ISSUE TITLE
Talk proposal: React Native - Under the hood

### ISSUE THREAD

**Issue by sangeethaKP** [seattlejs/seattlejs#185]
# React Native - Under the hood

Often times we work with React Native applications without having to deal with it's platform level internals that are wisely tucked away under several layers of abstraction. Knowing the cogs that are triggered when your app is launched would be a invaluable tool under your belt if you desire to build performant apps. 

In this talk, we’ll deep dive into the internals of a React Native application and understand the series of steps that happen when a react native app is launched.  
I will start with an overview of how a React Native application is structure, what are the different components (native, react-native, C++ bridge) that make up the app. Next we will look at a timeline of app initialization and see how the difference components are set up and how they communicate with each other.
Finally, I will also provide some quick actionable tips that developers can use to profile and improve app cold start latency.

Sangeetha is a Software Developer Engineer with 4 years of experience working with Alexa at Amazon HQ, focusing on developing solutions for Communication using Alexa. She is a Tech enthusiast and can be seen giving talks / workshops in universities/meetups in United States.

* Sangeetha KP
* [Twitter](https://twitter.com/sangee_kp)
* [Github](https://github.com/sangeethaKP/)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)

**Comment by bniedermeyer** [comment]
Hi @sangeethaKP! Are you available to give this talk on December 12th?

**Comment by sangeethaKP** [comment]
Hi @bniedermeyer, Yes I am available to give this talk on December 12th!

**Comment by bniedermeyer** [comment]
Great! Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSSlack

**Comment by sangeethaKP** [comment]
Done, thanks! :)
