### ISSUE TITLE
Sponsor request: Wallaby Pty Ltd

### ISSUE THREAD

**Issue by smcenlly** [seattlejs/seattlejs#186]
# Wallaby Pty Ltd

We create developer productivity tools for JavaScript/TypeScript developers and would like to provide some free licenses to your monthly user group as a form of sponsorship.

We are not looking to hire at this stage but would definitely appreciate feedback on our tools from your developers.

## Contact Info

Please email us at [hello@wallabyjs.com](mailto://hello@wallabyjs.com)

**Comment by bniedermeyer** [comment]
Hi @smcenlly, This sounds great! I've sent an email out to the requested address. Look forward to chatting.

**Comment by smcenlly** [comment]
Thanks, I've replied to your email. I'll close this issue.
