### ISSUE TITLE
Talk proposal: Metis: Using Google Sheets as a Makeshift Database for React Apps

### ISSUE THREAD

**Issue by athersharif** [seattlejs/seattlejs#187]
# Metis: Using Google Sheets as a Makeshift Database for React Apps

Building web apps using React has become increasingly popular in the past few months. However, considering a short-term project, such as in civic hacking, especially when the clients are non-tech-savvy, the developers can become a bottleneck for updating the website's content. [Metis](https://github.com/athersharif/metis) is a Higher-Order Component for React that allows Google Sheets to be used as a makeshift database, enabling non-tech-savvy users to perform content addition, modification, and/or deletion with ease.

In this talk, we'll explore the integration of Google Sheets in a React app using [Metis](https://github.com/athersharif/metis). We'll discuss the use cases of when such an integration could be beneficial as well as scenarios where it would be ill-advised.

## Bio

Ather is a Ph.D. Student at the University of Washington studying Human-Computer Interaction and Accessibility. He is also a Software Engineer at Comcast, and Founder and Researcher at [EvoXLabs](http://evoxlabs.org). Ather is a civic hacker and was the 2015 Philadelphia's Geek of the Year. 

Ather prefers he/him/his pronouns.

* Ather Sharif
* [Twitter](https://twitter.com/athersharif)
* [Github](https://github.com/athersharif)
* [Website](http://athersharif.com)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the SeattleJS Youtube channel

**Comment by bniedermeyer** [comment]
Hi @athersharif ! This looks great. Does our January 9th event work for you?

**Comment by athersharif** [comment]
@bniedermeyer great! Jan 9th could work for me! quick question - is the venue wheelchair accessible? asking because i use a wheelchair. similarly for the podium (could certainly just use a table instead).

**Comment by bniedermeyer** [comment]
We are still working on confirming the venue but I will make sure that’s taken into account. Thanks!

**Comment by athersharif** [comment]
great, thanks!

**Comment by bniedermeyer** [comment]
Hi @athersharif - We've had to cancel this month's event. Can you make Feb 13th?

**Comment by athersharif** [comment]
@bniedermeyer bummer! feb 13th should work! lmk when you finalize on the venue!

**Comment by bniedermeyer** [comment]
Will do!

**Comment by bniedermeyer** [comment]
@athersharif Hello again! Next week's event will be at Galvanize (111 S Jackson St, Seattle, WA 98104). Are you on our slack? If not can you join? It makes coordination a bit easier. You can sign up here: bit.ly/SeattleJSSlack

**Comment by athersharif** [comment]
@bniedermeyer sounds good. just joined!
