### ISSUE TITLE
Talk proposal: Bot Framework Composer: A web-based IDE to build sophisticated conversational applications from Microsoft

### ISSUE THREAD

**Issue by cwhitten** [seattlejs/seattlejs#188]
# Bot Framework Composer: A web-based IDE to build sophisticated conversational applications from Microsoft

Slack, Microsoft Teams, Facebook Messenger, Cortana, WhatsApp, etc: Conversational interfaces are here to stay, and more and more companies are investing in experiences on these platforms to connect with their customers and communities.

In this talk, we'll explore the domain of conversational applications; framing some of the challenges it presents: modeling conversation using machine learning and important cross-disciplinary components of building an effective conversational app through a new tool called [Composer](https://github.com/Microsoft/BotFramework-Composer) and dive in to the technical architecture and details of this tool to show how we achieved some of the functionality it is capable of. The tech stack is primarily React, Node.js, and C#.

# Bio
Chris is an Engineering Manager at Microsoft who leads the web applications efforts of the [Bot Framework](https://dev.botframework.com/). Our tools and technologies are core to Microsoft's Conversational AI strategy. 

* Chris Whitten
* [Twitter](https://twitter.com/_chriswhitten_)
* [Github](https://github.com/cwhitten)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the SeattleJS Youtube channel

**Comment by bniedermeyer** [comment]
Hi %speaker%, Can you please join our Slack group if you haven't already? That way we can add you to a channel for the event for better communication between you and the organizers. You can sign up here if you aren't already a member. https://bit.ly/SeattleJSslack

**Comment by bniedermeyer** [comment]
Hi @cwhitten! This looks great. Does our Feb 13th event work for you?

**Comment by bniedermeyer** [comment]
hi @cwhitten  - We've had to cancel this month's event so most of the speakers will probably be pushed to feb. Can you make March 12th?

**Comment by bniedermeyer** [comment]
Hi @cwhitten - just checking in. Does our March 12th event work for you?

**Comment by bniedermeyer** [comment]
hi @cwhitten - it looks like we're having trouble connecting on this. We'd love to have you come speak at SeattleJS. Feel free to reopen this talk when it's better for you  or open a new one on a different topic if you'd like!
