### ISSUE TITLE
Talk proposal: WTH is React's experimental Concurrent Mode

### ISSUE THREAD

**Issue by trivikr** [seattlejs/seattlejs#189]
# WTH is React's experimental Concurrent Mode

[Concurrent Mode](https://reactjs.org/docs/concurrent-mode-intro.html) is a set of new experimental features that help React apps stay responsive and gracefully adjust to the user’s device capabilities and network speed. In this talk, I'll be examining an app to understand blocking vs interruptible rendering, and see how concurrent mode overcomes some limitations. While doing this, we'll go through Suspense for data fetching, visualize some UI patterns made possible by concurrent mode and suspense, and determine how to try concurrent mode in your existing React projects!

I'm a Software Development Engineer and have been working on and off React.js for last 4 years - used React and ReactNative back in 2016, and resumed using it in mid-2018.

* Name
* [Twitter](https://twitter.com/trivikram)
* [Github](https://github.com/trivikr)
* [Website](http://trivikr.github.io)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the SeattleJS Youtube channel

**Comment by bniedermeyer** [comment]
@trivikr can you do March 12th?

**Comment by trivikr** [comment]
Yeah! March 12 works for me

**Comment by bniedermeyer** [comment]
@trivikr - we are going to be cancelling this month afterall (sorry for the back and forth) as a precaution given the covid situation. Would you be available next month or possibly for a remote talk if we decide to go that direction?

**Comment by trivikr** [comment]
@bniedermeyer April 9th works for me
Event details https://www.meetup.com/seattlejs/events/clmbzqybcgbmb/

**Comment by trivikr** [comment]
@bniedermeyer The two internal company conferences where I was planning to give this talk are cancelled. So I won't be able to prepare the talk specifically for SeattleJS.

This issue can be closed.
I'll create a new issue if I plan to give talk on same or different topic.
