### ISSUE TITLE
Sharing (Typescript) Types Across the Stack

### ISSUE THREAD

**Issue by evantahler** [seattlejs/seattlejs#191]
# Sharing (Typescript) Types Across the Stack

When you dive into the Typescript deep end, you'll hopefully start to see the benefits of using complex types across all parts of your application. You can can check that the controller is accessing a model property that really does exist, and you can use union types to make sure your API responses are always valid.  

But, what if we could share our Types even further... what if we could share them with our frontend?  In this way, we could automatically be confident that the properties we were trying to display on our site really do come back with our API responses... we could know for certain if dates are returned as strings or timestamps... and more!   

In this talk, I'll share how we do that at @Grouparoo between an @actionhero backend and @reactjs frontend and some generally applicable concepts to you can too! 

---

Evan Tahler is the CTO and co-founder of @Grouparoo, a new company building tools that make it easy to sync and use your product data everywhere. 

Prior to that, he was the Chief Product Officer at Voom (an Airbus Company) providing urban air mobility to cities around the world. Evan's expertise lies in building the technical side of digital products, as well as growing the teams required to do so. He’s helped companies like Disney, TaskRabbit, ModCloth, and Airbus launch new global digital initiatives. He is named on a number of patents focusing on mobile interactions and digital entertainment. Evan is an open-source innovator, and frequent speaker at software development conferences focusing on Product Management, Node.JS, Rails, and databases.

* Name: Evan Tahler
* [Twitter](https://twitter.com/evantahler)
* [Github](https://github.com/evantahler)
* [Website](https://www.evantahler.com)

---

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the [SeattleJS Youtube channel](https://www.youtube.com/channel/UCcSA-OGuAesfDqFNdEYGTaQ)

**Comment by evantahler** [comment]
Rough outline of the content https://www.grouparoo.com/blog/typescript-frontend-backend

**Comment by JOLee83** [comment]
Thanks for speaking!

**Comment by evantahler** [comment]
Happy to do it!  

The slides, code, and demo app can all be found here: https://github.com/evantahler/pokemon-typescript
