### ISSUE TITLE
Talk proposal: MTFA (Make Testing Fun Again) with Cypress

### ISSUE THREAD

**Issue by mccataldo** [seattlejs/seattlejs#193]
# MTFA (Make Testing Fun Again) with Cypress

Writing end-to-end tests is a chore. Maintaining them is a nightmare. Cypress is replacing Selenium as the de facto standard. If you want to make writing tests fun again, then this talk is for you. I'll introduce you to Cypress and show you why you should use it to ship front-end code more confidently. 

I've been using Cypress exclusively since it came out of beta several years ago. As community interest has grown over the last few years, I've been promoting Cypress by giving talks and hosting workshops in my home state of Utah. The Cypress team recently recognized me as a distinguished contributor to the community by accepting me into their Cypress Ambassador Program. My goal for 2021 is to extend my community outreach. I just launched a new site and YouTube channel, iheartjs, where I'm currently hosting my workshop material but will be publishing more content in the coming months. 

* Mike Cataldo
* [Twitter](https://twitter.com/mccataldo)
* [Github](https://github.com/mccataldo/mccataldo)
* [Website](https://iheartjs.dev)
* [YouTube](https://www.youtube.com/channel/UCv38GNojR0CSLhYwQszG7_g)
* [LinkedIn](https://www.linkedin.com/in/mikecataldo)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the [SeattleJS Youtube channel](https://www.youtube.com/channel/UCcSA-OGuAesfDqFNdEYGTaQ)

**Comment by JOLee83** [comment]
Thanks for speaking!
