### ISSUE TITLE
Talk proposal: Tech Twitch and You

### ISSUE THREAD

**Issue by cmgriffing** [seattlejs/seattlejs#194]
# Tech Twitch and You

There is a Science and Technology section of Twitch that you might not know about. You can find streamers just starting out on their coding journey. You can find seasoned developers that write code for major companies, open-source enthusiasts, and fun communities with which to talk about tech. There are even official streams from large companies like AWS, Microsoft, and MongoDB. I would like to highlight a few of those streams for you to get you started into the wide world of Tech Twitch. (I stream and will mention in passing but the focus is on other streamers.)

I love hanging out in the Science and Tech community and I stream a little bit myself. I'm also a somewhat Senior Web Developer at Symetra and have previously done work for a number of companies through a previous agency. I also enjoy long walks in the snow and smooth synthwave.

* Chris Griffing
* [Twitter](https://twitter.com/cmgriffing)
* [Github](https://github.com/cmgriffing)
* [Website](https://chrisgriffing.com)
* [Twitch](https://twitch.tv/cmgriffing)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the [SeattleJS Youtube channel](https://www.youtube.com/channel/UCcSA-OGuAesfDqFNdEYGTaQ)

**Comment by cmgriffing** [comment]
I could have something ready in time for the Feb 11 meetup if needed and I could have a draft of slides ready for review by the end of this weekend if needed.

If not, no worries, just want to briefly highlight some of the awesome streams that are out there.

**Comment by JOLee83** [comment]
Hi Chris, I can definitely fit you as the 3rd Speaker this month. sent you a message on Seattle JS slack, we can continue the conversation on there.

**Comment by cmgriffing** [comment]
Here is a rough draft of the slides.
http://cmgriffing.github.io/presentation-tech-twitch-and-you/?notes

I will be adding more content and making proper links. But I wanted to get this up as soon as I had it to a rough draft just in case you had any comments.

**Comment by JOLee83** [comment]
Thanks for speaking!
