### ISSUE TITLE
Talk proposal: Using Hooks w/ React-Redux

### ISSUE THREAD

**Issue by DamonLC21** [seattlejs/seattlejs#195]
# Using Hooks w/ React-Redux

We will be covering the use of the React-Redux hooks API as an alternative to the connect() Higher Order Component.  Hooks have been a hot topic for quite some time and what better way to highlight them than with a commonly used library, React Redux. Hooks give us the ability to always use functions instead of juggling between classes or high order components and at the end of the day just writing cleaner code that's easy to understand.

I am an artist, creative, and developer with a passion for teaching others what they are capable of. I am currently a Lead Instructor of Software Engineering for Flatiron School Denver.

* Damon Chivers
* [Github](https://github.com/DamonLC21)
* [LinkedIn](https://www.linkedin.com/in/damon-chivers/)

- [x] I've read and agree to the [SeattleJS Code of Conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)  
- [x] I consent to my talk being recorded and posted on the [SeattleJS Youtube channel](https://www.youtube.com/channel/UCcSA-OGuAesfDqFNdEYGTaQ)

**Comment by JOLee83** [comment]
Awesome, thanks for getting this in Damon. I got you locked in for March meetup. Here is the link to event, https://www.meetup.com/seattlejs/events/dlprdsyccfbpb/, rsvp to get the Zoom Link. I will reach out to set a quick prep meeting a day or two before the event with all the speaker.
