### ISSUE TITLE
Talk proposal: Cloud IDEs

### ISSUE THREAD

**Issue by stuartpb** [seattlejs/seattlejs#23]
# MISSION ACCOMPLISHED

Slides: https://docs.google.com/presentation/d/1ckoGhFPK7mYdda58EBSKQAGz0qE2eKhRCQOUr9BOYBY/

Recorded presentation video [looks like it's not going to happen](https://github.com/seattlejs/seattlejs/issues/23#issuecomment-71269313) :frowning: 

---
## Developing on Chromebooks: Cloud IDEs and the Chrome Dev Editor

When I tell people the majority of my coding over the last two years has been within a web browser, they tend to be surprised and intrigued, with lots of questions. "Is that really viable?" "Isn't it slow?" "What does coding in your browser get you?"

In this talk, I'll do some development with my Chromebook, while addressing questions like these (especially the last one). I'll demonstrate testing and deployment with Cloud9 and Heroku, as well as local development for Chrome extensions using the Chrome Dev Editor. I'll also talk about the few areas where I need to go outside of ChromeOS for my needs, and how these can be addressed (crouton, legacy-bios booting off of a USB device).
### Bio

I'm Stuart P. Bentley, and I've been using Cloud9 almost exclusively for all my development work since December 2012. I have a mostly-green GitHub contribution graph, and a whole bunch of repos on GitHub (116 non-fork repos on my user account, plus many more kept under organizations like https://github.com/plushu).

Most of my workspaces on Cloud9 are public, so you can see my work in progress on any of my projects at https://c9.io/stuartpb
- https://stuartpb.com
- https://github.com/stuartpb
- https://twitter.com/stuartpb

**Comment by stuartpb** [comment]
Any update on the video?

**Comment by doolittle** [comment]
@stuartpb we had a problem with the audio on your video so unfortunately we can't publish it :(

**Comment by stuartpb** [comment]
What's the problem? IS it just missing? (I was hoping one of the two mics
I was wearing would have caught it :p)
