### ISSUE TITLE
Talk proposal: Automating rendering performance in browsers

### ISSUE THREAD

**Issue by axemclion** [seattlejs/seattlejs#28]
# Automating Rendering performance in browsers

Delivering web page content to users as quickly as possible is important. It is equally important to ensure that this downloaded content provides a smooth and responsive user experience. Page scrolls that are Janky, delays when typing in text boxes or choppy animations are just as bad as pages that take a long time to load. Users spend longer using the page than waiting for it to load and we should ensure that the page renders at 60 frames per second at all times. 
Most modern web browsers have tools that could help identify the various things that could slow a web page down. However, rapid release cycles make it hard to do regular performance audits.

This talk will cover tools that can help automating runtime performance for web browsers using open source tools like [browser-perf](http://github.com/axemclion/browser-perf) and [perfjankie](http://github.com/axemclion/perfjankie).
The talk would also cover how we could generate rendering performance graphs (like [this](http://nparashuram.com/bootstrap-perf) for bootstrap), and how to use it in real projects.

**Comment by doolittle** [comment]
Thanks @axemclion! Can you write talks@seattlejs.com for a few more details?

**Comment by axemclion** [comment]
Sent.

**Comment by axemclion** [comment]
Closing issue as this talk was done. Thanks SeattleJS for giving me a chance to talk.
