### ISSUE TITLE
Talk proposal: Enhanced static site generation with react, react-router, and gulp plugins.

### ISSUE THREAD

**Issue by lanceharper** [seattlejs/seattlejs#29]
# Enhanced static site generation with react, react-router, and gulp plugins.

_Proposal for the February meetup_

Piggybacking on the talk from last month around the benefits of static sites, I wanted to demonstrate an approach I've explored that feeds markdown files through a series of a combination of custom and publicly available gulp plugins leveraging ReactJS+react-router some front matter+markdown files to create "server rendered" ReactJS components/markup as static pages. 

Client side JS containing the same React components will then sync with the static markup using a check-sum that won't force a re-render on initial load. Then, utilizing react-router, one can navigate through other blogs posts/pages fetching a remote static JSON file (also generated from a gulp plugin) to load subsequent pages faster than requesting a full page reload. If JS isn't enabled in the browser, the server side rendering (navigation included) will still work with no adjustment necessary.

I can provide access to a private repo upon request. Some of my public repos have gulp plugins that I've written as a part of my workflow.

## Bio

I've been working for NBC News Digital for almost three years helping out with .NET, document databases, and JavaScript on both the server and client. Sites I've helped build include msnbc.com, nbcnews.com ([youtube video from EmberJS meetup](https://www.youtube.com/watch?v=4ixw_5keMTc)), and today.com using both EmberJS and/or Node. I have familiarity with the benefits and drawbacks with various rich client side library approaches.

* Lance Harper
* lance.harper@gmail.com
* [@royallance](http://twitter.com/royallance)
* [@lanceharper](http://github.com/lanceharper)

**Comment by doolittle** [comment]
Thanks for submitting this @lanceharper! We're booked for speakers for the February meetup; could you write us at talks@seattlejs.com to figure out another month that could work?

**Comment by eastridge** [comment]
@lanceharper do you think you could condense this to a 10 minute talk for the lightning talks event on April 16th @ FB seattle?
