### ISSUE TITLE
Lightning Talk Proposal: Building a Large React Application *Without* Flux

### ISSUE THREAD

**Issue by ghempton** [seattlejs/seattlejs#31]
# Building a Large React Application *Without* Flux

Lot's of people discuss leveraging Flux's unidirectional data flow in a React application, but very few people discuss alternative methods. This talk will discuss our architecture at [outreach.io](http://outreach.io) and how we use stateful model layer in conjunction with React.

* Gordon Hempton
* [Twitter](https://twitter.com/ghempton)
* [Github](https://github.com/ghempton)
* [Website](http://codebrief.com)

**Comment by codefoster** [comment]
@ghempton, I'm just going through old proposals. Is this one still relevant and ready? It's been long enough that I thought I should ask. Let me know.
