### ISSUE TITLE
Lightning Talk Proposal: How real is the virtual dom ?

### ISSUE THREAD

**Issue by axemclion** [seattlejs/seattlejs#32]
# How real is the virtual DOM ? 

React as a javascript framework is incredibly fast, thanks to the virtual DOM. This was demonstrated during the recent ReactJS conference with the DBMonster app. In this talk, we will objectively look at the implementations of React and other frameworks, and use performance metrics to look under the hood of each of these frameworks, how how concepts like virtual DOM or eventing influence rendering performance numbers.
We will also look at frameworks like Radium and how computing/setting inline styles can impact performance, the effect of this idea, when taken to other frameworks. 

## Links
- [Analysis of DBMonster app](http://blog.nparashuram.com/2015/03/performance-comparison-on-javascript.html)

## About me
* Name: Parashuram
* [@nparashuram](http://twitter.com/nparashuram)
* [Github](http://github.com/axemclion)
* [Website](http://nparashuram.com)

**Comment by codefoster** [comment]
@axemclion, is this talk still relevant and ready? It's been long enough that I should ask. :)

**Comment by axemclion** [comment]
@codefoster I think yes. I also did some experiments with web [workers+React](http://blog.nparashuram.com/2015/12/react-web-worker-renderer.html) and wrote a custom renderer.

More content could be added to this talk if needed.

**Comment by axemclion** [comment]
@codefoster Wanted to ping you on this talk. Are you guys still doing lightning talks at SeattleJS ?

**Comment by jefflembeck** [comment]
@axemclion not too frequently, but I'm looking for one for 5/12.  Would you be interested?

**Comment by axemclion** [comment]
@jefflembeck Sure, that would work. I also submitted https://github.com/seattlejs/seattlejs/issues/68, which is based on the lightning talk. Would doing a lightning talk void the other proposal ?

**Comment by jefflembeck** [comment]
It does not void it, but it does make it less likely to come around in the next 6 months.

**Comment by axemclion** [comment]
@jefflembeck I would rather do the longer version, I believe that there is more content. In that case, I think we can close this issue.

**Comment by jefflembeck** [comment]
Great. Thanks!
