### ISSUE TITLE
Talk Proposal: Lightning Fast, Cross Platform, Development with MeteorJS

### ISSUE THREAD

**Issue by skifaster** [seattlejs/seattlejs#33]
# Lightning Fast, Cross Platform, Development with MeteorJS

MeteorJS is one of today's hottest JavaScript platforms and is proudly a top 10 GitHub project (in terms of stars). With Meteor, developers are able to write applications 3 – 10 times faster and with much less code. The platform allows for rapid prototyping and development, which is critical for any modern day application.

Unlike some other JavaScript frameworks (Angular/React/Node), MeteorJS is a full stack JavaScript platform including server and client components. Both server and client side code is written completely in JavaScript. This presentation will quickly compare the various platforms and frameworks and where Meteor fits best.

We'll review some stories from startups in the Seattle area that have changed to Meteor over the past year and see how it affected the pace of their development. For example, one local company had a current software solution with approximately one million lines of code; when they re-wrote the app in Meteor it resulted in only 100,000 lines of code. In another case, a startup spent three years developing a mobile application; late last year they switched over to Meteor and re-wrote the entire app in about 3 months. These are just a few examples of stories we will share of local Meteor success.

The final portion of the talk will be a live coding exercise to show how fast it is to get started with MeteorJS and create projects that run across web and mobile environments.
# Bio

I am an  JavaScript and .NET developer with more than 15 years experience. For more than a year I have been developing using MeteorJS and have helped various companies in the area get started on the platform. In addition to development, I also help support the Meteor Seattle community with various events in the area. 

[@skifaster](https://twitter.com/skifaster123)
[GitHub](https://github.com/skifaster)
[Meteor Website](http://meteor.com)

**Comment by hamoore** [comment]
I'm sorry we haven't gotten back to you yet on this! I know this proposal is pretty old, but s this still relevant and are you still interested in giving this talk?

**Comment by skifaster** [comment]
Heather,

Thanks for reaching out. Yes, I am still interested in giving this talk. Please let me know any next steps.

Thanks,
Carsten

----- Reply message -----

**Comment by hamoore** [comment]
Awesome! We are currently going through proposals and figuring out the best way to group and schedule them. We will let you know what month we are thinking as soon as we can!

**Comment by hamoore** [comment]
@skifaster sorry for getting back to you so late! If you think you can pare it down to 10 minutes, we'd love you to go on for a lightening talk (if...err... you still want to and it's still relevant for you) in November. What do you think?

**Comment by skifaster** [comment]
@hamoore Sounds good. Yes, I can pare the content down to 10 minutes to introduce the core concepts. Looks like the November meeting is on the 10th?

**Comment by codefoster** [comment]
@skifaster, how about March 9, 2017?

**Comment by skifaster** [comment]
@codefoster that works for my schedule. Looking at a 10 minute lightning talk? Do you have a location yet? I don't see one on the meetup.

**Comment by codefoster** [comment]
Yep. 10 minute lightning talk. The location for March will be Galvanize. Can you take a look at the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and confirm that you agree?

**Comment by skifaster** [comment]
Yes. Reviewed and I agree with those terms.

**Comment by codefoster** [comment]
Great. Got you down. Looks like your twitter image is a bit low res. Can you drop a higher quality image into this issue thread?

**Comment by skifaster** [comment]
@codefoster sorry about the image, i don't have anything handy. Just want to confirm this is a ten minute lightning talk, it didn't specify on the meetup description - just says Topic #2 - I have short and long content I could present. Thanks again for the opportunity. Looking forward to it!

**Comment by codefoster** [comment]
It is a 10 minute lightning talk, yes. Thank you.
