### ISSUE TITLE
Talk Proposal: Building Large Scale Web Applications with TypeScript

### ISSUE THREAD

**Issue by jj09** [seattlejs/seattlejs#35]
# Building Large Scale Web Applications with TypeScript

JavaScript has evolved significantly since the time it was first introduced 20 years ago. Today, JavaScript is the most popular programming language that allows to build large scale applications both on the client and on the server side. However, maintaining large codebases becomes more, and more challenging. 

In this talk I will show how TypeScript helps to build and maintain large scale web applications. I will also present the tools to work with TypeScript, how to take advantage of TypeScript while working with AngularJS 2, and lessons learned during work on the Azure Portal.
## Bio

Jakub Jedryszek works for Microsoft as Software Engineer. Currently he is working on the <a href="https://portal.azure.com">Azure Portal</a> – the largest and most complex Single Page Web Application in the World written in TypeScript. He is a founder of <a href="http://dotnetconf.pl">dotNetConfPL</a> – online conference for .NET Developers. His blog is at <a href="http://jj09.net">jj09.net</a>.

Before Microsoft Jakub developed a Model-Driven Development and Verification Approach for Medical Devices, while working for <a href="http://santoslab.org">SAnToS Lab</a>. He was also working as Web Developer for <a href="http://www.smtsoftware.com">SMT Software</a>, <a href="http://www.k-state.edu/vpcm/">Division of Communications and Marketing at Kansas State University</a>, and <a href="http://www.pgs-soft.com">PGS Software</a>.
- [@JakubJedryszek](https://twitter.com/JakubJedryszek)
- [Github](https://github.com/jj09)
- [jj09.net](http://jj09.net)

**Comment by codefoster** [comment]
Jakub, are you still interested in doing this presentation?

**Comment by jj09** [comment]
Sure

**Comment by hamoore** [comment]
@jj09 We've got a lightning talk (10min) slot open for November that we'd love to have you for... do you think this talk could be pared down for it?

**Comment by jj09** [comment]
What about full 1h?

**Comment by codefoster** [comment]
@jj09, we don't normally do full 1h presentations. Our ideal is a 30 minute feature presentation and two 10 minute lightning presentations. Are you interested in a 30 min feature one upcoming month?

**Comment by codefoster** [comment]
@jj09, let me know if you're still interested in doing this presentation and if you're okay with a 30 min presentation.

**Comment by jj09** [comment]
@codefoster I can do 30 mins, what date?

**Comment by codefoster** [comment]
@jj09, the next available feature slot is June 8 unless a feature slot from April or May backs out.

**Comment by jj09** [comment]
Can we tentatively confirm it now, and finalize on ~April?

**Comment by codefoster** [comment]
Yep. I'll set a reminder to ping you mid-March to confirm the confirmation 👍 In the meantime, can you read the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and verify that you agree?

**Comment by jj09** [comment]
agree

**Comment by codefoster** [comment]
@jj09, just wanted to confirm that you're on for presenting a feature (~25 min) at our June 8 meetup.
/cc @eliseworthy

**Comment by jj09** [comment]
@codefoster @eliseworthy confirmed!
