### ISSUE TITLE
Talk Proposal: Speech Recognition in the Browser

### ISSUE THREAD

**Issue by jj09** [seattlejs/seattlejs#36]
# Speech Recognition in the Browser

Mouse and keyboard are not the only ways how we can communicate with our devices. We already talk to our phones, gaming consoles, and some desktop applications. However, there are very few web applications that understand our speech. The bleeding edge versions of most popular web browsers are starting to support the most natural user input. Let’s take a look at Web Speech API, and learn how to add voice commands to web applications using pure JavaScript. Maybe it would be also worth to respond to users with voice using Web Synthesis API?

What you will learn:
* What is Web Speech API
* How to add speech recognition to website
* What browsers support speech recognition, and to what extent
* How to emit voice with Web Synthesis API

## Bio

Jakub Jedryszek works for Microsoft as Software Engineer. Currently he is working on the <a href="https://portal.azure.com">Azure Portal</a> – the largest and most complex Single Page Web Application in the World written in TypeScript. He is a founder of <a href="http://dotnetconf.pl">dotNetConfPL</a> – online conference for .NET Developers. His blog is at <a href="http://jj09.net">jj09.net</a>.

Before Microsoft Jakub developed a Model-Driven Development and Verification Approach for Medical Devices, while working for <a href="http://santoslab.org">SAnToS Lab</a>. He was also working as Web Developer for <a href="http://www.smtsoftware.com">SMT Software</a>, <a href="http://www.k-state.edu/vpcm/">Division of Communications and Marketing at Kansas State University</a>, and <a href="http://www.pgs-soft.com">PGS Software</a>.

* [@JakubJedryszek](https://twitter.com/JakubJedryszek)
* [Github](https://github.com/jj09)
* [jj09.net](http://jj09.net)

**Comment by jefflembeck** [comment]
I really want to see this. How long is the talk?

**Comment by jj09** [comment]
30-45 mins

**Comment by jefflembeck** [comment]
Can you do this in February?

**Comment by jj09** [comment]
When exactly? Feb 11, 6PM?

**Comment by jefflembeck** [comment]
Yes! Sorry about that.

**Comment by jj09** [comment]
It will work. Please email/msg me when confirmed.

**Comment by jefflembeck** [comment]
@jj09 Just confirming that Feb 11, 6PM still works for you.

**Comment by jj09** [comment]
@jefflembeck Yes, putting it in my calendar now. What's the location?

**Comment by jefflembeck** [comment]
EMC Isilon.

**Comment by jj09** [comment]
@jefflembeck is this happening? I don't see any info on meetup: http://www.meetup.com/seattlejs/events/224633792/

**Comment by hamoore** [comment]
It is, yes! Sorry, we haven't gotten the meet-up page updated yet. We will get it updated soon (I actually just tried, but the website wasn't working correctly).

**Comment by jordandobson** [comment]
This sounds awesome.

**Comment by hamoore** [comment]
@jj09 I'm talking with the venue and they are wondering if you need any special set-up or if just a standard 1/8" jack will work for you?

**Comment by jj09** [comment]
@hamoore mini jack is good enough, what video output, and resolution is there?

**Comment by jj09** [comment]
what is the meetup schedule? talks start at 6? or there is pizza&connect time?

**Comment by jefflembeck** [comment]
The talks normally start about 30 minutes in.

**Comment by hamoore** [comment]
@jj09 I just heard back from EMC with this file... Is this helpful? [InFocus-IN5140-TechnicalGuide.pdf](https://files.zenhub.io/56bcd55a7ac1df253132357a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jj09** [comment]
@hamoore this is awesome! nothing is better than hardcore spec! :smile:
