### ISSUE TITLE
Talk Proposal: How to Build DOM Fast While Staying DRY

### ISSUE THREAD

**Issue by Daniel-Hug** [seattlejs/seattlejs#37]
How do you generate the new DOM necessary for your dynamic views? If you're using a templating system like handlebars, you sacrifice speed for maintainability because you have to use `innerHTML` to render. `innerHTML` is both slow and it leaves you no JS hook with which to set up a controller. If you're doing it old school with `document.createElement` it might be fast, but your code eventually gets soggy.

By abstracting the creation of new DOM into a couple of utility functions that avoid the pitfalls of templating systems, you can quickly generate new DOM faster, with less code, while maintaining your JS hooks that allow for easy controller setup.

## bio
Daniel Hug is a front end web developer who enjoys writing modular JS, making mobile friendly web applications, writing algorithms, playing ultimate frisbee, juggling, and a few other things.

* [@CSSHug](https://twitter.com/CSSHug)
* [Github.com/Daniel-Hug](https://github.com/Daniel-Hug)
* [hugwebdesign.com](http://www.hugwebdesign.com/)

**Comment by Daniel-Hug** [comment]
Didn't mean to submit this yet...

**Comment by Daniel-Hug** [comment]
Added a bio. :smile:

**Comment by hamoore** [comment]
I'm sorry we haven't gotten back to you yet on this! I know this proposal is getting a little old, but is this still relevant and are you still interested in giving this talk?

**Comment by Daniel-Hug** [comment]
I would love to! I don't have an outline yet though. How far out are you thinking?

**Comment by hamoore** [comment]
Great! We are currently going through proposals and figuring out the best way to group and schedule them. We will let you know what month we are thinking as soon as we can!

**Comment by jefflembeck** [comment]
@Daniel-Hug are you able to give this talk still? Would June work for you?

**Comment by Daniel-Hug** [comment]
I would love to @jefflembeck!

**Comment by jefflembeck** [comment]
AWESOME. June 9th. We're putting you down.

**Comment by Daniel-Hug** [comment]
Awesome! :smiley:  I'll give some thought to refining the talk. How long am I supposed to be? I'll look forward to the 9th!

**Comment by jefflembeck** [comment]
@Daniel-Hug We normally like to keep it 25 minutes, plus or minus a few.

**Comment by Daniel-Hug** [comment]
Sounds good.

On Fri, May 13, 2016 at 2:47 PM, Jeff Lembeck <notifications@github.com>
wrote:

> @Daniel-Hug <https://github.com/Daniel-Hug> We normally like to keep it
> 25 minutes, plus or minus a few.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/37#issuecomment-219167371>
>



-- 
Need God? <http://www.needgod.com/>

**Comment by Daniel-Hug** [comment]
Let me know any additional details you need from me.

On Fri, May 13, 2016 at 2:47 PM, Daniel Hug <danielthehug@gmail.com> wrote:

> Sounds good.
>
> On Fri, May 13, 2016 at 2:47 PM, Jeff Lembeck <notifications@github.com>
> wrote:
>
>> @Daniel-Hug <https://github.com/Daniel-Hug> We normally like to keep it
>> 25 minutes, plus or minus a few.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/seattlejs/seattlejs/issues/37#issuecomment-219167371>
>>
>
>
>
> --
> Need God? <http://www.needgod.com/>
>



-- 
Need God? <http://www.needgod.com/>

**Comment by hamoore** [comment]
@Daniel-Hug Do you happen to have a higher res picture we could use, rather than copying your github photo? :)

**Comment by Daniel-Hug** [comment]
@hamoore I'm on it...

**Comment by Daniel-Hug** [comment]
@hamoore Here you go: http://cl.ly/gL4Y
