### ISSUE TITLE
Talk Proposal: CouchDB: A Serious Backing Store on Serious Earth

### ISSUE THREAD

**Issue by stuartpb** [seattlejs/seattlejs#38]
So, this is a talk I want to give:

In @HenrikJoreteg's talk about six months(?) ago, he _mentioned_ you can build an app with PouchDB that works entirely in-browser. Henrik's talk was more of a general call-to-arms about building what I might term as "primarily client-side" apps - I want to give a _deep dive_ talk about one aspect of that, which I would consider the biggest hurdle to entering this paradigm right now: understanding the unconventional semantics of CouchDB, which are imitated by PouchDB.

About a week ago, when I was first starting to really give CouchDB a second look, [I tweeted](https://twitter.com/stuartpb/status/616817652804120580) that "CouchDB users are this collection of aliens that communicate telepathically to describe the mechanisms available to model data when using it", as a way of conveying my frustration with the conventional self-serving "Introduction to CouchDB"-style talk: they tend to spend a bunch of time on REST like it's a novelty (rather than a boring implementation detail that doesn't even _apply_ for PouchDB), and then jump _directly_ to _intricate details_ like what the signature of an `emit` in a map function should be. The choir who goes to this kind of talk to be preached to all nod, as if the speaker had superliminally transmitted all the slides that explain how CouchDB querying is done with views consisting of map functions defined in design documents.

(Not to get down on the CouchDB people: this is a problem I have with almost all "Introductions" in tech, which is why I've been writing [my own epic-scale Lean Notes](http://www.leannotes.com/) for years.)

I've been [writing my own guide to learning CouchDB](https://github.com/stuartpb/couchdb-in-a-hurry/blob/master/README.md) for the last four days or so: the meat of this presentation would essentially be a summary of the bullet points from that guide, one that does _not_ skip over the details that are obvious to people who already live and breathe CouchDB, along with an honest admission of the common, necessary features (like managing accounts with password recovery) that CouchDB _completely fails to account for_ (which you _can_ solve, using a partial standalone app / daemon alongside your database).

I'd also talk a bit about the history of client-side data (the not-quite-perfect evolutionary path from cookies to localStorage to WebSQL to IndexedDB), and why you'd want to use PouchDB instead of IndexedDB directly (considering I'm the kind of guy who usually _never_ reaches for an abstraction library).
### Bio

I'm Stuart P. Bentley, and I've been developing using HTML5 for three or four years (depends on how seriously you're counting). I have a mostly-green GitHub contribution graph, and a whole bunch of repos on GitHub (somewhere above 100 - it's a bunch under my personal account, and a bunch more projects under their own organizations).
- https://stuartpb.com
- https://github.com/stuartpb
- https://twitter.com/stuartpb

**Comment by hamoore** [comment]
I'm sorry we haven't gotten back to you yet on this! I know this proposal is getting a little old, but is this still relevant and are you still interested in giving this talk?

**Comment by codefoster** [comment]
@stuartpb, let me know if you're still interested in presenting this. If not, I'll close this issue off. Thanks.

**Comment by stuartpb** [comment]
Sure, I'm still interested in doing this - since @nolanlawson's moved to Seattle in the time since I originally proposed this, I'd want to run the slides past him first (as a lot of it pertains to PouchDB).

**Comment by nolanlawson** [comment]
Sure thing, feel free to send them to me via email (`nolan@nolanlawson.com`) or Twitter DM and I'd be happy to have a look. :)

**Comment by codefoster** [comment]
@stuartpb and @nolanlawson , did you guys get settled? Would this presentation be a lightning (~10 min) or a feature (~25 min).

**Comment by stuartpb** [comment]
I've actually only written about two slides for this so far; if it's okay, I think I'll start drafting my further thoughts on this out via comments in this issue, so it can be inspected and everything - anybody who's not interested in getting pinged at that level of detail should probably unsubscribe (ie @hamoore and @codefoster) and I'll explicitly @mention them when the presentation is shippable.

**Comment by stuartpb** [comment]
Also, @codefoster my feeling is that this'd be tracking a 25-minute feature form-factor, just because of the level of detail / comprehensiveness I'd want to fill for (explaining the oeuvre of the general CouchDB-compatible space, the conceptual data model it uses, the usage patterns for interacting with it, the pitfalls...)

**Comment by codefoster** [comment]
@stuartpb, does Sept 14 or Oct 12 work for you?

**Comment by codefoster** [comment]
@stuartpb, are you still game for doing this preso? How does Feb 8, 2018 work for you?

**Comment by stuartpb** [comment]
Sure, I'll take a February 2018 slot.

**Comment by codefoster** [comment]
Great. Can you confirm you agree with our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)?

**Comment by stuartpb** [comment]
Yes, I agree with the Code of Conduct.

**Comment by stuartpb** [comment]
D'oh! I just made plans to be out of town for the first full week of February 2018.

If this were moved to March, what date would that fall on?

**Comment by stuartpb** [comment]
[The event page for the February Meetup](https://www.meetup.com/seattlejs/events/dczsvkyxdblb/) says "We don't have any speakers at the moment": did the event planners forget this was scheduled too?

**Comment by stuartpb** [comment]
Worst-case scenario (if there really are no other talks lined up), I could *try* giving this presentation remotely somehow: I'd still need at least a week's notice to ready the slides.

**Comment by stuartpb** [comment]
May works for me.

**Comment by EmmaBroback** [comment]
Hey @stuartpb -- I was hoping to get an updated/concise description of the talk since the one above from two years ago is more conceptual.

**Comment by stuartpb** [comment]
In this talk, I describe the CouchDB model, how it's been unevenly pitched in the past, and how it's useful in a way that no other web-platform data-store offering in 2018 can offer.
