### ISSUE TITLE
Talk Proposal: Adding Azure search to your app

### ISSUE THREAD

**Issue by EvanBoyle** [seattlejs/seattlejs#39]
# Adding Azure Search to your app

Search is often one of the default methods of navigating in a web/mobile app. Quality of search can make or break things like engagement, return visits, conversions etc. But building an maintaining a good search experience is difficult, and the tools available are either very expensive, or have extremely steep learning curves. Azure Search is a new search SAAS offering that substantially lowers the barrier to entry. I'd like to do a live coding lab with the group where we take an application and build some cool search features step by step, like auto-complete/suggestions, faceting, visualizations, etc. I really enjoyed participating in the react workshop (in February maybe?) that followed a similar format. I'd plan on providing a github project that the group could use to follow along, and would likely build the demo application in react (although I'm open to suggestions). I've built some simple search UI in react in the past and would love the chance to expand on it:

https://github.com/AzureSearch/AzureSearchNodeJSIndexerDemo/tree/master/js/UI

I've given a meetup talk on Azure Search in the past. Here is the summary I used as well as the slide deck that went with it. When given the option, I much prefer live coding demos than PPT.

http://www.slideshare.net/EvanBoyle1/adding-azuresearch

summary used for previous meetups:

Many applications use search as the primary interaction pattern for their users. When it comes to search, user expectations are high. Users expect great relevance, suggestions, and solid linguistics that effortlessly handle spelling mistakes, near-instantaneous responses, multiple language, faceting, and more. During this presentation, Evan Boyle (Engineer on Azure Search) will take a mobile application with a SQL backend and show just how easy it is to add a rich full text search experience with Azure Search.

Speaker:

Evan Boyle is an Engineer for Microsoft's Azure Search. Evan has experience in a variety of fields including security research, data visualization, and predictive analytics. Evan is currently responsible for the management and monitoring experience in the new Azure portal.

**Comment by hamoore** [comment]
I'm sorry we haven't gotten back to you yet on this! I know this proposal is getting a little old, but is this still relevant and are you still interested in giving this talk?

**Comment by EvanBoyle** [comment]
Yes I'm still very interested in giving a talk. I've been working on a 100% react/flux search demo that provides lots of really cool features such as infinite scroll loading, suggestions/typeahead, filtering and faceted search. I thought it might be interesting to do a workshop where we build/recreate some of these features together.

**Comment by hamoore** [comment]
That sounds very cool! How long do you think you would need?

On Mon, Dec 21, 2015 at 10:14 AM, Evan Boyle <notifications@github.com>
wrote:

> Yes I'm still very interested in giving a talk. I've been working on a
> 100% react/flux search demo that provides lots of really cool features such
> as infinite scroll loading, suggestions/typeahead, filtering and faceted
> search. I thought it might be interesting to do a workshop where we
> build/recreate some of these features together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/39#issuecomment-166379717>.
>



-- 
Heather Moore
Office Manager
*Formidable Labs*

**Comment by EvanBoyle** [comment]
It depends on how in depth you'd like me to go. I'd say in half an hour I
could do an overview of the search technology and setting that up, plus a
walk through of the react/flux app. If I was doing a workshop sort of thing
I'd imagine an hour would probably be more ideal.

**Comment by hamoore** [comment]
Great! We do generally max out at 30 minutes for talks, but I'll speak with the organizers and see if they think making an exception would be beneficial! We are currently sorting out a calendar for the year, so I'll get back to you as soon as we have a better idea of the best timing!

**Comment by EvanBoyle** [comment]
Great, keep me posted!

**Comment by EvanBoyle** [comment]
Hi Heather,

Any updates?

**Comment by hamoore** [comment]
Hi Evan! We're still in discussions, but I will see if I can get any
information for you! :)

On Thu, Jan 7, 2016 at 11:14 AM Evan Boyle <notifications@github.com> wrote:

> Hi Heather,
>
> Any updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/39#issuecomment-169777841>.
>
-- 
Heather Moore
Office Manager

*Formidable*

**Comment by codefoster** [comment]
Hey, @EvanBoyle, our ideal speakers line up for an evening is 1 30 min feature presentation and 2 10 min lightning presentations. That said, there shouldn't be any trouble at all sneaking a feature up to roughly 40 min. Let me know if that works for your presentation and I'll let you know when we can suggest a month to line you up.

**Comment by EvanBoyle** [comment]
That would be great. How far in advance are you planning talks?

**Comment by codefoster** [comment]
How does March 9 sound? April 13 is also available.

**Comment by codefoster** [comment]
@EvanBoyle, actually, it's looking more like April 13, so let me know if that works.

**Comment by EvanBoyle** [comment]
Yeah that sounds great. Let's put it on the calendar

**Comment by codefoster** [comment]
Good. Can you read the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and confirm that you agree?

**Comment by EvanBoyle** [comment]
I agree to the code of conduct. The venue will likely be determined closer to the date of the presentation correct? Is there a standard time the events are hosted?

**Comment by codefoster** [comment]
@EvanBoyle, sorry for the late reply to this. Yes, the venues are sometimes chosen closer to event time. We know now that the April 13 event will be at Galvanize.
I've got you down then for April 13. Targeting 25 minutes for your presentation. Let me know if you have any more questions.

**Comment by codefoster** [comment]
@EvanBoyle, I just wanted to be sure you saw that we had a change of venue for this event. We're now going to be at Simply Measured. Details are on the [meetup event page](https://www.meetup.com/seattlejs/events/230354991/). You're still on to speak, right?

**Comment by EvanBoyle** [comment]
Got it, thanks Jeremy!
