### ISSUE TITLE
Lightening Talk Proposal: Angular D3 chart directives made with the miso d3.chart library

### ISSUE THREAD

**Issue by simplesthing** [seattlejs/seattlejs#40]
# Angular D3 chart directives made with the miso d3.chart library

The topic isn't new or groundbreaking, it's just a project that I have been working on which combines the use of AngularJS with D3.js and miso d3.chart library to create composable charts that are easily extended. The reason this pattern is interesting is because both Angular and D3 have their own DOM updating patterns which do not play well with one another out of the box. The pattern I am presenting takes advantage of Angular to create self contained configurable directives that manage DOM manipulations and data retrieval while relying on the miso d3.chart library for drawing and updating the D3 SVG's. 

You can see the project code [here](https://github.com/simplesthing/angular-d3-miso).

About me:

I currently lead the front end of an analytics application at Apollo Education Group in Seattle. For the past two years I have been working with AngularJS full time and recently added D3 to the list about 4 months ago. I also organize  the Seattle Ladies JS meetup group.

* [@simplesthing](https://twitter.com/simplesthing)
* [github](https://github.com/simplesthing)
* [simplesthing.com](http://simplesthing.com)

**Comment by jefflembeck** [comment]
This talk was given in October and was fantastic!
