### ISSUE TITLE
Talk Proposal: Getting started with Elm

### ISSUE THREAD

**Issue by ivanoats** [seattlejs/seattlejs#41]
Elm is a compile-to-javascript language that offers "the best of functional programming in your browser". 
http://elm-lang.org/

It's also one of the inspirations of the ReactJS Redux framework and Angular 2.0. 

I will talk about:
- Why I chose to learn Elm and why you might consider it, too.
- My development environment and workflow
- Demonstrate how you can get started with it
- and point to more great resources available to help.

**Comment by jefflembeck** [comment]
@ivanoats are you looking at a 10 minute or a 20-25 minute talk?

**Comment by ivanoats** [comment]
20-25 minutes

**Comment by hankyates** [comment]
+1

**Comment by jefflembeck** [comment]
@ivanoats you think you can deliver on Nov 12?

**Comment by ivanoats** [comment]
Yes, I can get this ready fairly quickly.

**Comment by codefoster** [comment]
Ivan, we're locked and loaded on this by the way. Can you attach or send a url to an avatar (unless you just want me to use [this one](https://avatars3.githubusercontent.com/u/4672). Also respond with an issue comment here with your bio and the abstract of the talk (if different from what you included above). thx.

**Comment by ivanoats** [comment]
Thanks all. 

Here's a new avatar. This one's a bit more true to life, i guess the gray is starting to show! ![ivan2013-200](https://cloud.githubusercontent.com/assets/4672/10417524/dc3fd7d0-6ff3-11e5-9cca-c88e90cd19bd.jpg)

About Ivan
Ivan Storck has been programming, teaching, and leading start-ups for 20 years. He helped found two training companies and a web hosting company. He has taught and advises curriculum at the University of Washington. Ivan enjoys staying current with the fast pace of technology trends. He focuses on an agile, open-source, and human-centered design approach to building web apps with JavaScript, Ruby, and cloud systems. Ivan lives in Seattle, and works for Aerobatic. Outside of work, you can find him on a SUP, kayaking with his wife and sons in Puget Sound, or building Legos when it rains.

**Comment by ivanoats** [comment]
Also, I'd like the event description to include installation instructions if possible:

Please download the following tools so that you can follow along during and after the talk:

`npm - g install elm brunch`  

, or go to:

http://elm-lang.org/install and then also make sure to have brunch installed. I'm using brunch so that we can quickly clone a template to get started with.

**Comment by ivanoats** [comment]
slides: http://seattlejs.elmseattle.org
