### ISSUE TITLE
Talk Proposal: JavaScript on AWS Without Servers using JAWS

### ISSUE THREAD

**Issue by boushley** [seattlejs/seattlejs#42]
# JavaScript on AWS Without Servers using JAWS

JAWS is a 100% free and open-source framework for building serverless applications using Amazon Web Services' Lambda, API Gateway, and more. Lambda's event-driven model offers tremendous cost savings and colossal horizontal scaling ability. Now, JAWS helps you build and maintain entire event-driven/serverless applications using Lambda.

This new way of running services allows you to get started with a simple and cheap infrastructure that scales to serve hundreds or thousands of requests per second without any intervention.

I'm a software engineer that has been working on the web for over ten year. I've used many different frameworks and languages on the server and in the browser. Recently I've been experimenting with and contributing to JAWS. I've also written a couple blog posts on [JAWS](http://blog.boushley.net/2015/10/02/serverless-architecture-with-jaws/) and [hosting Web Applications with JAWS](http://blog.boushley.net/2015/10/03/web-apps-without-servers/)

The presentation will be based off of the AWS Re:invent [slides for JAWS](https://docs.google.com/presentation/d/1TQhcdCIysECzNbzHWb95oypvTMGktgzCvxMrlYQkg_g/edit?usp=sharing)

* Aaron Boushley
* [Twitter](https://twitter.com/boushley)
* [Github](https://github.com/boushley)
* [Website](http://blog.boushley.net/)

**Comment by hamoore** [comment]
I'm sorry we haven't gotten back to you yet on this! Are you still interested in speaking?

**Comment by boushley** [comment]
I would still be up for doing it. The project is called Serverless now, but still relevant

**Comment by hamoore** [comment]
Great! We are currently going through proposals and figuring out the best way to group and schedule them. We will let you know what month we are thinking as soon as we can!

**Comment by jefflembeck** [comment]
@boushley I know it's a bit short notice, but would you be able to give this talk on March 10?

**Comment by boushley** [comment]
That is pretty quick. I can probably make that work though.

JAWS has renamed itself to [Serverless](https://github.com/serverless/serverless) in the mean time. And I'll probably focus on the whole serverless paradigm more than the JAWS/Serverless framework specifically. That all seem reasonable?

Do we have info on the venue? Aspect ratio of the projector (16:9 or 4:3)?

**Comment by hamoore** [comment]
@boushley March will be our final month at EMC Isilon. Attached is their projector specs! [InFocus-IN5140-TechnicalGuide.pdf](https://files.zenhub.io/56c4fd3154b11b79199fc6ea)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by boushley** [comment]
@hamoore @jefflembeck just to confirm the presentation should be 20 - 30 minutes? Or is it longer / shorter?

**Comment by hamoore** [comment]
@boushley That is correct! Somewhere between 20-30 minutes would be perfect.

**Comment by boushley** [comment]
@hamoore thanks for the quick responses!

Any idea when the Meetup page will be updated: http://www.meetup.com/seattlejs/events/221671534/

Wanting to invite some people to my talk.

**Comment by hamoore** [comment]
@boushley We'll get it updated soon! For your abstract and bio, would you like me to use the phrasing on your submission? Additionally, do you have a different photo you would like us to use or are you happy with us using your github photo?

**Comment by boushley** [comment]
GitHub Photo is fine.

For abstract lets do:

> Amazon Web Services' Lambda and API Gateway enable us to build flexible and scalable Serverless applications. Lambda's event-driven model offers tremendous cost savings and colossal horizontal scaling ability. Serverless is an open source framework that makes working with Lambda and API Gateway easy.
> 
> This new way of running services allows you to get started with a simple and cheap infrastructure that scales to serve hundreds or thousands of requests per second without any intervention.

And for bio, lets do:

> I'm a software engineer that has been working on the web for over ten years. I've used many different frameworks and languages on the server and in the browser. Recently I've been experimenting with and contributing to Serverless.

**Comment by hamoore** [comment]
Great!

**Comment by hamoore** [comment]
@boushley As I'm uploading that photo, the image quality is ending up pretty poor. Do you happen to have a larger file I could use? :)

**Comment by boushley** [comment]
Try this one: 
![aaronboushley](https://cloud.githubusercontent.com/assets/101239/13448820/e08a28a2-dfda-11e5-9e64-aca1a5981b5f.jpg)

**Comment by boushley** [comment]
@hamoore there's a bigger photo.

**Comment by hamoore** [comment]
@boushley That's perfect! The meet-up is updated and "announced"! http://www.meetup.com/seattlejs/events/221671534/

**Comment by boushley** [comment]
Great! Thanks.

**Comment by codefoster** [comment]
@boushley what video adapter do you need for your laptop?

**Comment by boushley** [comment]
I have a MacBook Pro Early 2013 model. So mini-display port / thunderbolt connector, or hdmi.
