### ISSUE TITLE
Talk Proposal: Moneyball for Performance Metrics

### ISSUE THREAD

**Issue by jefflembeck** [seattlejs/seattlejs#43]
The story behind Moneyball was centered around using metrics— newer, out-of-the-norm metrics— to build a better performing baseball team. This strategy of measurement was wildly successful, squeezing out more wins for less money. That works for baseball, why can’t it work for the web? Focusing on our most commonly measured stats only paints half the picture. In this talk, I’ll use those same ideas to give you better ways to determine the quickness at which users can access your site and help you turn up your speed.

Time estimate: 30 minutes

**Comment by jefflembeck** [comment]
This is my talk. I'm totally not picking me :grin:

**Comment by doolittle** [comment]
Sounds like a great talk though!

**Comment by hamoore** [comment]
@jefflembeck Would you be able to give this talk in June? ;)
