### ISSUE TITLE
Lightning Talk Proposal: Multi-Client Sync Strategies

### ISSUE THREAD

**Issue by toddself** [seattlejs/seattlejs#44]
# Multi-Client Sync Strategies

This talk will cover three different strategies for keeping multi-user documents in sync with each other allowing for real-time collaboration, with a specific focus on how Operational Transform works. This talk is being given tonight at BrooklynJS. 

Slides are available: https://toddself.github.io/presentations/operational-transform

Hi! I'm Todd Kennedy and I'm the CTO of a small start up called Scripto where we make multi-user editors and software for creating and producing television.

* Todd Kennedy
* [Twitter](https://twitter.com/whale_eat_squid)
* [Github](https://github.com/toddself)
* [Website](https://scripto.cc)

**Comment by hamoore** [comment]
Thanks for your proposal, @toddself! We will get back to you as soon as we have more of an idea of the best timing for your talk!

**Comment by jefflembeck** [comment]
Let's do it. May 12!
