### ISSUE TITLE
Talk Proposal: Abstract Syntax Trees

### ISSUE THREAD

**Issue by xjamundx** [seattlejs/seattlejs#45]
I recently gave a talk about abstract syntax trees at the UtahJS conference. I'd also be happy to give it at SeattleJS sometime. Here was the proposal as I originally submitted it to them:

A lot of us came to JavaScript without a strong background in computer science. Ever find yourself recoiling in fear when someone starts talking about algorithms? It turns out when building websites we don't often have to reach to these concepts to be successful. Despite this the past few years have definitely taught me that computer science has a lot to offer UI programmers. From Angular embracing dependency injection and the React world with its Immutable objects and Dom-diffing techniques, it turns out computer science has a lot to teach UI developers. One concept that's been the most influential in the last few years of JS tooling is the abstract syntax tree. 

Abstract syntax trees are everywhere. They power the JS in your browsers. They're in your minifiers. They're in your linters. They power webpack and browserify and babel and so many other tools that make up the modern web stack. And you've probably never heard of them before.

Let me show you how abstract syntax trees work.

We'll look at some simple examples of linters and babel plugins and help you envision the power that trees can bring into your programs. Come join me on an exciting journey down the AST rabbit hole and never program the same way again.

Time estimate: 30 minutes (but could go on forever...)

**Comment by jefflembeck** [comment]
I'm interested. @xjamundx could I persuade you to give this in January?

**Comment by xjamundx** [comment]
That would be so fun, what's the date?

**Comment by jefflembeck** [comment]
@xjamundx January 14th!

**Comment by xjamundx** [comment]
k let me check and get back to you tomorrow

**Comment by xjamundx** [comment]
I'm in !

**Comment by codefoster** [comment]
@xjamundx I need your bio right away for the meetup page. Also, let me know if you want me to use an avatar image other than [this](https://avatars3.githubusercontent.com/u/246143?v=3&s=400) one.

**Comment by xjamundx** [comment]
@codefoster what o you need me to say for the bio?

You can use this one:

> Jamund Ferguson is a full stack UI Engineer at PayPal. He helps his team develop best practices for both node.js and client-side frameworks and loves talking about JavaScript. He is also an active contributor to several open source projects including Kraken-js and ESLint.

As far as pictures you can use:
https://cldup.com/glpTjXPw2H-3000x3000.jpeg

**Comment by codefoster** [comment]
Just give everyone an introduction to who you are, your experiences, your job, your hobbies - whatever you want to say. 100-300 words is a good size.

**Comment by xjamundx** [comment]
That (updated version) above ok?

**Comment by codefoster** [comment]
Yep. It's live now.

**Comment by xjamundx** [comment]
woo!

**Comment by hamoore** [comment]
@xjamundx : Are there any websites you will be using for your talk? EMC would like to know ahead of time so they can get it set up for you.

**Comment by xjamundx** [comment]
Thanks Heather.

I'll just have slides, so I should be okay.

How long should I speak?

**Comment by hamoore** [comment]
30 minutes would be ideal. :)

**Comment by jefflembeck** [comment]
Great talk, thanks Jamund!
