### ISSUE TITLE
Talk Proposal - Exponent and React Native

### ISSUE THREAD

**Issue by ccheever** [seattlejs/seattlejs#46]
# Exponent and React Native - How write native stuff for iPhone and Android using just JavaScript

The talk is about Exponent, which is something I'm working on that lets developers use just JavaScript to write feeling experiences on iOS and Android. You can go from zero to having your first Exponent project running on your phone in less than 5 minutes.

Exponent is 2 pieces of software -- some desktop software you run on your computer, and a client you run on your phone. When you're running the desktop software, you can edit JavaScript in your text editor, and our software will turn it into a bundle
that the Exponent client can interpret.

Exponent is built on top of React Native, an open source project from Facebook, which targets the popular React JS framework at native views on both iOS and Android. This means you can easily take anything you write in Exponent and package it into an app you submit to the Apple App Store and/or Google Play.

[Here is an video of me giving a talk about an early version of this project at React Rally in Utah](https://www.youtube.com/watch?v=HaxZMDP6eDA)

### Reverse chronological Bio
I'm working on a startup called Exponent which I hope to talk about. Before that, I cofounded Quora which is a question-and-answer service. Before that, I worked at Facebook as an engineer and manager and worked on a bunch of things including the Facebook Platform and Facebook Connect. Before that, I lived in Seattle and worked at Amazon.com as an SDE. I went to Harvard for college and grew up in Pittsburgh.

* Charlie Cheever
* [Personal Twitter](http://twitter.com/ccheever)
* [Personal Github](http://github.com/ccheever)
* [Exponent Twitter](http://twitter.com/exponentjs)
* [Exponent Github](http://github.com/exponentjs)
* [Exponent Website](http://exponentjs.com/)

**Comment by codefoster** [comment]
@ccheever, do you want me to use your Twitter (better than your GitHub) avatar for your presenter image or would you like to provide me with a new one?

**Comment by ccheever** [comment]
![p1020391](https://cloud.githubusercontent.com/assets/56719/11205363/0d0c6894-8cbc-11e5-8f76-543afb01af02.JPG)

This one is probably clearer than either. Let me know if you think its appropriate for this context.

Also, if you were going to put my reverse bio on a website or something, I should probably revise that? It was mostly written for you guys to figure out if you'd be interested in my talk.

**Comment by codefoster** [comment]
Great. Thanks, @ccheever. Your mug is up at http://www.meetup.com/seattlejs/events/220102667/ now. Let me know if anything about your bio or abstract need to be changed.
