### ISSUE TITLE
Talk Proposal: Reducing Per-Function Development/Test Costs with Encapsule Filter library.

### ISSUE THREAD

**Issue by ChrisRus** [seattlejs/seattlejs#47]
# Summary of Encapsule/jbus-common-filter

jbus-common-fiter was designed to make it possible for single developers, or small teams, to pound out production-worthy subsystems in JavaScript to, for example, stuff into Dockerized Node.js containers. Or, into your favorite HTML5 SPA.

The library specifically targets JavaScript functions providing a mechanism to automate function I/O validation/shaping logic via declarative JSON contracts.

Filters "wrap" a function you write with automated data validation/shaping and error handling logic that bolster its defensive (input stage) and offensive (output stage) capabilities.

This "wrapping" reduces per-function development and maintenance costs by eliminating ancillary function subroutines that ensure the fidelity of data I/O to/from a function's core algorithm. And, this in turn reduces the per-function cost of test development and maintenance.

The system works by requiring developers to declare their function I/O contracts using terse JSON documents called "Filter Specs". Not only is this far more efficient than writing the equivalent logic, but it can be done before any code is written. Or, while the project is in-flight.

Runtime I/O validation/shaping is handled transparently by the Filter library for all functions processed through the library's main function factory method, create. Filter accomplishes this by using developer-specific Filter Spec JSON documents to adapt its runtime validation/shaping behavior to match each function's unique requirements.

Name: Chris Russell
Twitter: https://twitter.com/AlpineLakes (personal) https://twitter.com/Encapsule (work)
GitHub: https://github.com/Encapsule/jbus-common-filter
Website: https://encapsule.io

Bio: https://www.linkedin.com/in/chrisrussell

**Comment by codefoster** [comment]
Thanks, @ChrisRus. We'll get back to you soon when we've processed some of these proposals.

**Comment by ChrisRus** [comment]
Suppose you had to create an API endpoint that accepts only an object used as an associative array of arrays that contain numbers between 0 and 100.

```JavaScript
var FILTERLIB = require('arccore').filter;
var response = FILTERLIB.request({
    operationID: "vgBXsxTmSVaEF14HNClR8g", // Every filter has a unique ID
    inputFilterSpec: {
        ____types: "jsObject",
        ____asMap: true,
        mapEntry: {
            ____types: "jsArray"
            ____element: {
                ____accept: "jsNumber",
                ____inValueRange: { begin: 0, end: 100 }
            }
        }
    }
});
if (response.error) {
    throw new Error(response.error);
};
var filter = response.result;
```

You're done.
