### ISSUE TITLE
Host Request: Q2 at Adobe

### ISSUE THREAD

**Issue by aiko0403** [seattlejs/seattlejs#48]
## Company info
* Name of company / Adobe
* Address / 801 N 34th Street, Seattle WA 98103
* Neighborhood / Fremont

## A short explanation of why you'd like to host

We’d like to host for a variety of reasons. We are always hiring, and raising awareness of Adobe as a great place to work in Seattle is definitely one of our objectives. We would, of course, refrain from aggressively soliciting applicants during the event. 

Culturally, Adobe has a long tradition of community involvement, including open source contributions, hosting meetups and user groups, and charitable work as well. Numerous Adobe employees are SeattleJS members, and it’s only fair that we do our part by taking care of the hosting on occasion. Ideally we’d do so regularly, perhaps once per quarter.

## Contact Info
Aiko Llin
ailin@adobe.com
206-227-3014

Thanks!

**Comment by codefoster** [comment]
Just wanted to say thank you for offering to host. I believe Heather is already working on solidifying things with you. Looking forward to it.

**Comment by codefoster** [comment]
Changed the date to Feb 2016* - I think that's what you meant.
