### ISSUE TITLE
Lightning Talk Proposal: The only correct script loader ever made

### ISSUE THREAD

**Issue by exogen** [seattlejs/seattlejs#49]
Hey! I'm Brian Beck, I work at Formidable. I've got a quick talk prepared about:

* How simply loading a .js file is not a solved problem in 2015
* Yes, your code is probably broken because of this
* How this situation came to be
* What we're doing about it

Saving the more interesting links for the talk itself... it'll be a fun one!

* [Formidable](http://www.formidable.com/)
* [GitHub](https://github.com/exogen)

**Comment by codefoster** [comment]
Great talk, Brian. I've never actually seen someone do a 5 minute talk in 5 minutes. Well, 6, but it was extremely close :) little-loader looks really good too.

**Comment by exogen** [comment]
Thanks a ton for squeezing me in, Jeremy! Had a blast.
