### ISSUE TITLE
Talk Proposal: Building Command Line Apps in JavaScript

### ISSUE THREAD

**Issue by patrickkettner** [seattlejs/seattlejs#51]
Howdy folks!
I have an idea for a talk that I wanted to show you, and I think it is a lot more interesting to see than I can put into a few sentences.

[Here is a video](https://youtu.be/hhXK0Na9DQo) of the explanation and the not-at-all finished product. If this is something you find neat, I would love to come in and discuss how anyone can create powerful cli tools in javascript!

**Comment by codefoster** [comment]
Thanks, @patrickkettner. We'll get back to you when we've processed some of these. Looking forward to hearing from you.

**Comment by patrickkettner** [comment]
cheers!​

**Comment by jonathanmarvens** [comment]
This is __very__ cool, @patrickkettner.

**Comment by patrickkettner** [comment]
thanks a lot, @jonathanmarvens :D

**Comment by alrra** [comment]
![](https://cloud.githubusercontent.com/assets/1223565/11940115/1ccbc19c-a82f-11e5-98f0-37eea19f4dec.png)

**Comment by jefflembeck** [comment]
@patrickkettner you able to give this talk on March 10th, perchance?

**Comment by patrickkettner** [comment]
I would love to, but its my partners birthday and I will be several thousand miles away from Seattle that day :[

**Comment by jefflembeck** [comment]
@patrickkettner aw bummer, how does May 12th sound?

**Comment by patrickkettner** [comment]
sounds good to me!

On Mon, Feb 15, 2016 at 10:04 AM, Jeff Lembeck <notifications@github.com>
wrote:

> @patrickkettner <https://github.com/patrickkettner> aw bummer, how does
> May 12th sound?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/51#issuecomment-184328265>.
>



-- 
patrick

**Comment by hamoore** [comment]
Hello @patrickkettner! As we are getting prepared for the upcoming May meet-up happening on the 12th, I was wondering if I could get a 2-4 sentence talk description, personal bio, and photo from you for the website, as well as any sites you'd like us to link to (twitter, blog, website, etc). Thanks!

**Comment by patrickkettner** [comment]
Hey @hamoore 

I am so sorry, but work stuff came up and I will be traveling in europe during that time now :[

I would be more than happy to do a remote or prerecorded talk, but I imagine y'all would rather reschedule? Whatever you want, is fine by me.

sorry again

**Comment by hamoore** [comment]
@patrickkettner That's too bad! I mean... hopefully great that you'll be in Europe, but too bad for Seattle JS! We would like to reschedule. @jefflembeck when works best for your plans?

**Comment by jefflembeck** [comment]
June and on are good for me, @patrickkettner if you wanna pick a month, just let me know.

**Comment by patrickkettner** [comment]
Hey @jefflembeck! Is July available?

**Comment by jefflembeck** [comment]
@patrickkettner it's not, but June 9th is?

After that, we likely have September.

**Comment by patrickkettner** [comment]
june 9 works great for me

**Comment by jefflembeck** [comment]
@patrickkettner _AWESOME_

**Comment by hamoore** [comment]
@patrickkettner Would it be possible to get the blurb now for the announcement? :) (blurb on talk, bio, photo, links)

**Comment by patrickkettner** [comment]
__description__

It is not uncommon for people to think of the command line as an ancient, impenetrable and impossible interface to get any real work done. Even if you are a veteran vim user, the thought of actually creating anything other than a single line, argument based interface will probably seem like something out of reach for almost anyone. Not so! Using nothing but JavaScript, you can create rich, compelling, command line interfaces that leverage keyboard and mouse input, and more!

__bio__

Patrick Kettner a web developer, hacker, and dad from Seattle. He is the lead maintainer of Modernizr, a PM for Edge at Microsoft, and a new dad 

for photo can you use my GitHub avatar?

__links__
GitHub.com/patrickkettner
twitter.com/patrickkettner

**Comment by hamoore** [comment]
@patrickkettner Thanks! I CAN use your avatar, it just won't be very high quality. Totally up to you. :)

**Comment by patrickkettner** [comment]
how about [this](https://goo.gl/photos/SiL4i4AMNG4KE1Fp9)

**Comment by hamoore** [comment]
That is... amazing. In so many ways. ;)

**Comment by patrickkettner** [comment]
:D!

@alrra pointed out that I am a bit redundant in my dadatude in my bio

could it be

Patrick Kettner a web developer, hacker, and dad from Seattle. He is the lead maintainer of Modernizr, a PM for Edge at Microsoft

**Comment by hamoore** [comment]
Got it!

**Comment by patrickkettner** [comment]
target is ~25 minutes, right?
also, is there a venue picked for next week?

**Comment by hamoore** [comment]
Yep! And we'll be at Adobe again for our last month. :)
