### ISSUE TITLE
Talk proposal: Using web components in production at the Seattle Times

### ISSUE THREAD

**Issue by thomaswilburn** [seattlejs/seattlejs#52]
Web components have been *right on the edge* of production-readiness for several years now, to the point where many people have simply given up on them. At the Seattle Times, we've found that with a little bit of polyfilling, we can have the benefits of custom elements today, and we're using them all over our site, and on our special projects. This talk will cover the basics of web components, talk about the ones we're using currently (`<leaflet-map>`, `<responsive-frame>`, and more), create a simple component, and then discuss the possible pitfalls that come with life on the bleeding edge.

**Comment by jefflembeck** [comment]
Interesting!

How long of a talk do think think this would be?

**Comment by thomaswilburn** [comment]
I've done a variation of this in ten minutes that was just a demo of `leaflet-map`, but 30 minutes to an hours is more what I had in mind.

**Comment by jefflembeck** [comment]
@thomaswilburn that's fantastic. I'd love to see a 30 minute version of this in February or March if that works well for you.

**Comment by thomaswilburn** [comment]
Sure, sounds good to me.

**Comment by hamoore** [comment]
Thomas, how do you feel about February? The February meet-up is on the 11th at 6pm.

**Comment by thomaswilburn** [comment]
Works for me!

**Comment by jefflembeck** [comment]
Oh dang, looks like I missed the boat on updating this. I'm so sorry @hamoore and @thomaswilburn.

Does March 10 at 6pm work for you @thomaswilburn ?

**Comment by thomaswilburn** [comment]
March 10-13 I'm out of town, unfortunately.

**Comment by jefflembeck** [comment]
Damn, I really want to see this talk.

April 14th work, perchance?

**Comment by thomaswilburn** [comment]
Yes, I can make it in April.

**Comment by hamoore** [comment]
We will put you down for April then! Sorry for the confusion!

**Comment by thomaswilburn** [comment]
No worries, see you then!

**Comment by hamoore** [comment]
@thomaswilburn Do you have a headshot and bio that I can put on the meet-up site? Additionally, what websites would you like me to link to?

**Comment by thomaswilburn** [comment]
![mugshot](https://cloud.githubusercontent.com/assets/881329/13833318/f83a91b2-eba1-11e5-808c-b3239ecaaa46.jpg) <- Mugshot

Bio:

Thomas Wilburn is a news developer for the Seattle Times, where he works with reporters and editors to build interactive features and graphics. Previously, he worked at ArenaNet on the web team for *Guild Wars 2*, which uses embedded browser tech in several parts of the in-game UI.

Good links to have:

* [Live May Day updates](http://www.seattletimes.com/seattle-news/live-updates-from-may-day-seattle/)
* [Responsive frame element](https://github.com/seattletimes/responsive-frame)
* [Image slider element](https://github.com/seattletimes/component-image-slider)
* [Leaflet element](https://github.com/seattletimes/component-leaflet-map)
* [Our custom element template](https://github.com/seattletimes/component-template)

**Comment by hamoore** [comment]
@thomaswilburn Wonderful! One other thing... we will be at Adobe for April and they can get you your own wifi log-in if you would like to supply them with an email address? It won't be used for anything else.

**Comment by thomaswilburn** [comment]
I've had a wifi login at Adobe before (about six months ago), does it expire or would it still be good?

**Comment by hamoore** [comment]
Apparently it expires after a month. :/

**Comment by thomaswilburn** [comment]
Ah, that's a shame. Well, we can use twilburn@seattletimes.com then.

**Comment by hamoore** [comment]
Thanks! :)
