### ISSUE TITLE
Talk Proposal: Observables Everywhere

### ISSUE THREAD

**Issue by codefoster** [seattlejs/seattlejs#53]
# Observables Everywhere

## Abstract

Learning new syntax or even a new language is, oddly, easier than learning new paradigms. Observables are a new paradigm that overturns a lot of ceremony we've grown accustomed to. It does away with imperative event handling and it entirely obsoletes promises.

Reactive Extensions (Rx), the technology that empowers Netflix as well as Angular 2, is an observable library that has a ton to offer, and yet has an easy on-ramp. It feels small, light, and simple - the way good code should.

I'm going to show you how easy it is not only to include the Rx library, but also to start integrating it into the way you think and work.

## About Me

I studied Computer Engineering and Mathematics in school a long time ago, and have thoroughly enjoyed my career course ever since - primarily teaching and software development and primarily on the web stack. I gained experience in education, aerospace manufacturing, and insurance, and eventually joined Microsoft with the goal of informing and inspiring software developers. I authored my first book CSS for Windows 8 App Development, published a couple of courses on Pluralsight.com, and try to keep up with audiences via my blog codefoster.com and my Twitter feed @codefoster. When I’m not working, I’m working on maker projects, spending time with my wife and two sons, hiking and camping, sailing, scuba diving, or working on house projects.

* [Jeremy](http://codefoster.com/avatar)
* [Twitter](http://twitter.com/codefoster)
* [Github](http://github.com/codefoster)
* [Website](http://codefoster.com)

**Comment by jefflembeck** [comment]
Awesome. Putting this in for January.

**Comment by jefflembeck** [comment]
Thank you Jeremy!
