### ISSUE TITLE
Sponsor Request: Q2 2016

### ISSUE THREAD

**Issue by gummiskye** [seattlejs/seattlejs#54]
# Company Name: Hired

We love the Seattle tech scene and would love to have the opportunity host and support the Seattle developer community!  

Hired is on a mission to get everyone a job they love, starting with in-demand tech roles. We've built a marketplace in Seattle that has helped candidates get connected to companies such as Zillow, Moz, and Qumulo. 

Check out some of the open source stuff we've worked on: 
https://github.com/hired
https://github.com/fortitude

# Contact Info
Skye Wang
skye@hired.com

**Comment by hamoore** [comment]
This is so great! We're excited to have Hired.com as our sponsor for Q2!
