### ISSUE TITLE
Talk Proposal: Nothing Sounds Quite Like An (ng)808.

### ISSUE THREAD

**Issue by texel** [seattlejs/seattlejs#55]
# Nothing Sounds Quite Like An (ng)808.

## Abstract

Do you like JavaScript? How about music? No? Ok, you should leave now.

For the rest of you hi, thanks for sticking around! I've built a fun little sequenced drum machine using Angular 2, TypeScript, and an audio/sequencing library developed at Splice called _Shabu-shabu_.

In this talk, I'll show you how it works, and point out some of the cool new features of Angular 2 which has just officially gone beta. I'll also show you how TypeScript can make JavaScript even more fun (and safe) for everyone.

**Warning**: you may be exposed to higher than usual levels to Planet Rock during this presentation.

## About me
My name is Leigh, and I work for Splice. We make tools that help musicians around the world collaborate and stay inspired.

I'm also a musician and DJ myself, but please don't hold that against me.

* [Github](https://github.com/texel)
* [Twitter](https://twitter.com/texel)
* [Music](https://soundcloud.com/quadrant)

**Comment by jefflembeck** [comment]
This is exactly what I was looking for for February. Perfect.

Let's do this.

**Comment by hamoore** [comment]
@texel I'm talking with the venue and they are wondering if you need any special set-up or if just a standard 1/8" jack will work for you?
