### ISSUE TITLE
Talk Proposal: Code as a Design Tool

### ISSUE THREAD

**Issue by jordandobson** [seattlejs/seattlejs#56]
Hello!

I'd love to do another talk / live demo with SeattleJS. My last one was about *5 years ago* and was about building mobile web HTML5 applications and what you can do with CSS motion and animation, including where JS fits into it all: http://jrdn.io/3H350O2l462M 

Lately I've transitioned to be more of a designer and producer of custom web frameworks and design / prototype / develop componets for the web and iOS. I do a lot of prototyping with FramerJS and want to talk / share with you all what I'm learning through this... I also run a Prototying for Designers FramerJS meetup where we mentor, collaborate and teach people how they can be better designers and team mates. :smile: 

Here's an abstract on a talk I did at Refresh Seattle this past October 2015 and I would love to do later this spring (April / May / June). It was a 1hour 15min talk and we discussed for about 45min afterwards as well. Pretty fun and new for people...

# Abstract

Should designers learn to code?

The design landscape has become so dependent on motion, data, user input and context that the role of a designer has changed. It’s no longer about how a design looks but how it feels and reacts to input. Validation of interaction designs and concepts often need to be realized, tested and documented before visual design is finalized and development begins. Code as a design tool can give you the super power to do these things.

Jordan Dobson will take us through how he switched to designing with code over 10 years ago, what he does today, how to be a future thinking design leader and prepare yourself for the design landscape of today. He’ll also talk about how to save time in your design process, approaches for testing, recommended prototype tools, local meetups / mentors and how to get started using code in your workflow simply and gradually. We'll also talk about ways as a designer you better interface with your engineer 

As companies like Facebook have begun to require every designer to take a crash course in prototyping with code to validate their ideas, it won’t be long before others follow. It’s not just for small startups anymore.

Code is a very powerful design tool. A designer learning a beginner to intermediate level of coding won’t make a great developer, instead it will increase their abilities tremendously.

# My Bio

Jordan Dobson lives in Tacoma, Washington and is currently a Designer / Prototyper for the OneNote Experience Design team at Microsoft lead by Sean Wolcott. Prior to that he was the sole Design / Developer for iOS & a member of the Office Fabric UI Front End Framework Team shipping code to millions of OneDrive users. Other roles include Lead Prototyper / Designer for Sway at Microsoft, Design Prototyper for Groupon’s recent rebrand and Lead Mobile Designer / Front End Developer for Expedia’s first mobile web experience for over 20 Global markets. Before that Jordan was the Owner / Designer of the Creative Design & Development agency, Squad, for 10 years where he did everything from self funding two mobile focused startups to 100s of projects in branding, motion, animation, programming and print design for clients in the music and entertainment industry.

Previous clients he's has worked with include T-Mobile, Xbox, Sencha Touch, Montage Studio, jQuery Mobile, Sony, Warner Bros, Geffen, Tooth And Nail, Lindsey Buckingham, Billy Idol, Thrice and Madonna. He’s a recent graduate of two University of Washington certificates in iOS & Mac Application Development and Ruby Programming. He’s also a co-host of the monthly meetup FramerJS Seattle Prototyping for Designers where he helps mentor those new to prototyping.

http://JordanDobson.com

**Comment by hamoore** [comment]
Awesome! We are working on getting a schedule set up for talks and will let
you know as soon as we have an approximate date in mind! Thanks!

On Tue, Jan 12, 2016 at 12:33 AM Jordan Dobson <notifications@github.com>
wrote:

> Hello!
>
> I'd love to do another talk / live demo with SeattleJS. My last one was
> about *5 years ago* and was about building mobile web HTML5 applications
> and what you can do with CSS motion and animation, including where JS fits
> into it all: http://jrdn.io/3H350O2l462M
>
> Lately I've transitioned to be more of a designer and producer of custom
> web frameworks and design / prototype / develop componets for the web and
> iOS. I do a lot of prototyping with FramerJS and want to talk / share with
> you all what I'm learning through this... I also run a Prototying for
> Designers FramerJS meetup where we mentor, collaborate and teach people how
> they can be better designers and team mates. [image: :smile:]
>
> Here's an abstract on a talk I did at Refresh Seattle this past October
> 2015 and I would love to do later this spring (April / May / June). It was
> a 1hour 15min talk and we discussed for about 45min afterwards as well.
> Pretty fun and new for people...
> Abstract
>
> Should designers learn to code?
>
> The design landscape has become so dependent on motion, data, user input
> and context that the role of a designer has changed. It’s no longer about
> how a design looks but how it feels and reacts to input. Validation of
> interaction designs and concepts often need to be realized, tested and
> documented before visual design is finalized and development begins. Code
> as a design tool can give you the super power to do these things.
>
> Jordan Dobson will take us through how he switched to designing with code
> over 10 years ago, what he does today, how to be a future thinking design
> leader and prepare yourself for the design landscape of today. He’ll also
> talk about how to save time in your design process, approaches for testing,
> recommended prototype tools, local meetups / mentors and how to get started
> using code in your workflow simply and gradually. We'll also talk about
> ways as a designer you better interface with your engineer
>
> As companies like Facebook have begun to require every designer to take a
> crash course in prototyping with code to validate their ideas, it won’t be
> long before others follow. It’s not just for small startups anymore.
>
> Code is a very powerful design tool. A designer learning a beginner to
> intermediate level of coding won’t make a great developer, instead it will
> increase their abilities tremendously.
> My Bio
>
> Jordan Dobson lives in Tacoma, Washington and is currently a Designer /
> Prototyper for the OneNote Experience Design team at Microsoft lead by Sean
> Wolcott. Prior to that he was the sole Design / Developer for iOS & a
> member of the Office Fabric UI Front End Framework Team shipping code to
> millions of OneDrive users. Other roles include Lead Prototyper / Designer
> for Sway at Microsoft, Design Prototyper for Groupon’s recent rebrand and
> Lead Mobile Designer / Front End Developer for Expedia’s first mobile web
> experience for over 20 Global markets. Before that Jordan was the Owner /
> Designer of the Creative Design & Development agency, Squad, for 10 years
> where he did everything from self funding two mobile focused startups to
> 100s of projects in branding, motion, animation, programming and print
> design for clients in the music and entertainment industry.
>
> Previous clients he's has worked with include T-Mobile, Xbox, Sencha
> Touch, Montage Studio, jQuery Mobile, Sony, Warner Bros, Geffen, Tooth And
> Nail, Lindsey Buckingham, Billy Idol, Thrice and Madonna. He’s a recent
> graduate of two University of Washington certificates in iOS & Mac
> Application Development and Ruby Programming. He’s also a co-host of the
> monthly meetup FramerJS Seattle Prototyping for Designers where he helps
> mentor those new to prototyping.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/56>.
>
-- 
Heather Moore
Office Manager

*Formidable*

**Comment by jordandobson** [comment]
Sounds great! Thanks.

**Comment by jefflembeck** [comment]
Hey @jordandobson, is there any chance this talk is something you can give on March 10th?

**Comment by jefflembeck** [comment]
Oop. Looks like March is booked. How's June sound?

**Comment by jordandobson** [comment]
Sorry for the late reply. June isn't the best I'll be traveling quite a
bit. What's available after that?

**Comment by hamoore** [comment]
Would you be interested in July 14?

**Comment by jordandobson** [comment]
Boo... Just learned Family reunion that week. :) Okay. Sorry anything
should be good. :|

**Comment by jordandobson** [comment]
Ahem... Anything after that should be good.

**Comment by hamoore** [comment]
Haha how about we shoot for August 11?

**Comment by jordandobson** [comment]
That works for me. Thanks!

**Comment by hamoore** [comment]
@jordandobson Would it be possible to get a headshot from you for the meetup page? I'm just about to get it announced! :)

**Comment by jordandobson** [comment]
How is this?

![black-and-white](https://cloud.githubusercontent.com/assets/39778/17148179/e5b5fb36-531a-11e6-9a2b-ba92fcb6fafb.png)

**Comment by jordandobson** [comment]
I have yet to get a solid photo of myself. :/

If you'd rather have a photo... let me know and I'll try to dig some up / crop some decent ones... I'm  trying to find a good flip phone for my upcoming headshots. :P

**Comment by hamoore** [comment]
That will do! Thanks! :) Maybe next time we're doing new-hire headshots up here at Formidable, you can pop in. ;)

**Comment by jordandobson** [comment]
That would be awesome. 

Also, can you give me an idea of the approximate time I'll have to talk?

**Comment by hamoore** [comment]
You'll be on around 7pm and you'll have about 30 minutes. :)

**Comment by hamoore** [comment]
It's updated and posted! :) http://www.meetup.com/seattlejs/events/224633801/

**Comment by jordandobson** [comment]
Thanks for having me!

**Comment by divmain** [comment]
Thanks again @jordandobson!
