### ISSUE TITLE
DeltaDB: Data Syncing for the Write-Once-Run-Everywhere HTML5 App

### ISSUE THREAD

**Issue by redgeoff** [seattlejs/seattlejs#57]
# Talk Proposal: DeltaDB: Data Syncing for the Write-Once-Run-Everywhere HTML5 App

Since the days of the first smartphones, there have been people describing a future where we can write a single app in HTML5 that runs on all devices. Cordova allows us to package our HTML5 and build a native app that can be submitted to the different app stores. Ionic allows us to implement native-like UIs. The plethora of JS frameworks like AngularJS, EmberJS, React, etc… allow us to structure our apps using the latest MVC constructs. And, Firebase, PouchDB and Meteor provide powerful browser-side databases that sync, but unfortunately, all these data sync technologies have significant limitations.

My solution to the missing data sync portion of the JS-full-stact vision is DeltaDB, an open-source offline-first NoSQL database written in JavaScript. DeltaDB is meant to be used in a front-end only design where the only backend needed is DeltaDB. The client writes to a local database and whenever the app is online it will sync with the database cloud.

We’ll cover the [reasons why DeltaDB was created]((https://medium.com/@redgeoff/introducing-deltadb-finally-there-is-hope-for-the-write-once-run-everywhere-html5-app-afd5c59baa5b#.y0oiv5910)) and briefly cover [how to get started with DeltaDB](https://medium.com/@redgeoff/getting-started-with-deltadb-137359111282#.4wk6d1jiz).

Geoff Cox
---

[https://github.com/redgeoff](https://github.com/redgeoff)
[https://github.com/delta-db/deltadb](https://github.com/delta-db/deltadb)
[http://twitter.com/redgeoff7](http://twitter.com/redgeoff7)

Geoff Cox is an entrepreneur and software developer that is fascinated with the possibilities of using JavaScript to power the full stack. Geoff has been developing software most of his life and has worked on everything from legacy mainframe systems to modern day web apps. Fresh out of college, he started a company called urshelf.com, which was like an Ebay for textbooks, and it was a modest success. He then spent several years abroad, living in San Salvador and Berlin, taking advantage of the work-from-home lifestyle. During this time, he co-founded a trade show management software company called GoExpo that was purchased by Core-apps in 2013. He now serves as the VP of GoExpo Dev for Core-apps and spends his free time coding fun open-source JavaScript projects like DeltaDB. When Geoff isn’t coding, you can find him traveling, jamming on his guitar or enjoying a beer in a hammock.

**Comment by hamoore** [comment]
Thank you for your interest! As we are planning out the year, we will get back to you about the best timing for your talk! :)

**Comment by redgeoff** [comment]
I recently did a more in depth analysis of the new constructs in
PouchDB/CouchDB and it appears that PouchDB/CouchDB are a lot more
performant than they used to be a year so ago. Therefore, I am going to be
discontinuing my efforts on DeltaDB at this time and will unfortunately
have to withdraw my request to talk. Thanks.
