### ISSUE TITLE
Talk proposal: Native apps with Tabris.js

### ISSUE THREAD

**Issue by cookieguru** [seattlejs/seattlejs#58]
# Native Apps with Tabris.js

Tabris.js is a mobile framework that lets you develop native iOS and Android apps from a single code base written entirely in JavaScript.  Tabris.js does not use WebViews for rendering and allows you to use existing JavaScript libraries, node modules and Cordova plugins to build your apps.  Tabris.js also has an online build service eliminating the need to set up SDKs to generate packages for mobile devices.

I'm a full stack PHP developer that has discovered this framework.  I've built one app and have several more on the way.  I'd love to share my experience and help spread the word about this amazing platform.
- Tim Bond
- [Twitter](https://twitter.com/TimB0nd)
- [Github](https://github.com/cookieguru)

**Comment by hamoore** [comment]
We'd love to have you share! As we are setting up our schedule for the
year, we'll get back to you about what timing works best!

On Wed, Jan 13, 2016 at 4:43 PM Tim <notifications@github.com> wrote:

> Native apps with Tabrisjs
>
> Tabrisjs is a mobile framework that lets you develop native iOS and
> Android apps from a single code base written entirely in JavaScript
> Tabrisjs does not use WebViews for rendering and allows you to use existing
> JavaScript libraries, node modules and Cordova plugins to build your apps
> Tabrisjs also has an online build service eliminating the need to set up
> SDKs to generate packages for mobile devices
>
> I'm a full stack PHP developer that has discovered this framework I've
> built one app and have several more on the way I'd love to share my
> experience and help spread the word about this amazing platform
>
>    - Tim Bond
>    - Twitter <https://twittercom/TimB0nd>
>    - Github <https://githubcom/cookieguru>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/58>.
>
-- 
Heather Moore
Office Manager

*Formidable*

**Comment by codefoster** [comment]
@cookieguru, would this be a lightning (~10 min) or a feature (~25 min) presentation?

**Comment by cookieguru** [comment]
@codefoster I could do either but a feature would be more suitable

**Comment by codefoster** [comment]
@cookieguru, how about a feature on May 11?

**Comment by cookieguru** [comment]
Sounds great @codefoster!

**Comment by codefoster** [comment]
@cookieguru, can you take a look at our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and confirm that you agree?

**Comment by cookieguru** [comment]
Agree to the code of conduct.

**Comment by codefoster** [comment]
Got it. Thanks. We're all set.

**Comment by tmero** [comment]
Tim! I'm traveling on May 11th. So sad to miss your talk. I want to see you speak again :)

**Comment by cookieguru** [comment]
@tmero I'm hoping I can record it.  Because I'm sure the folks at @eclipsesource would love to see it as well!

**Comment by cookieguru** [comment]
That was fun!  Here's the video:

https://www.youtube.com/watch?v=bwF3uPyq50w

**Comment by codefoster** [comment]
Just [tweeted it](https://twitter.com/codefoster/status/866526994535555072), @cookieguru.

**Comment by cookieguru** [comment]
@codefoster Missed the link and got the wrong handle

**Comment by codefoster** [comment]
Doh! Which handle is wrong?

**Comment by cookieguru** [comment]
@codefoster I'm [TimB0nd](https://twitter.com/TimB0nd) on Twitter

**Comment by codefoster** [comment]
Oh weird. I did the ol' GitHub/twitter switcheroo. Tweet deleted. New one coming soon.

**Comment by codefoster** [comment]
Done
