### ISSUE TITLE
Talk Proposal: Exploring the future of visual programming

### ISSUE THREAD

**Issue by jgebhardt** [seattlejs/seattlejs#59]
(I updated the talk topic from the original issue)
# Combine: Exploring the future of visual programming

Decades ago, machines forced us to learn text-based programming languages in order to talk to them. It’s time to rethink antiquated programming models.

I will present my side project Combine, a prototype for a browser-based visual programming environment, which makes data more tangible, programming more accessible, and enables rapid prototyping of JS apps, or crazier stuff like turning API endpoints into music or visual art pieces.

I’ll also dive more deeply into the tech of what makes this possible– from new-ish browser tech like SVG/CSS3 to Observables, Web Workers, as well as static typing and much more. 

Join me for a wild ride through browser APIs and programming paradigms, from CSS hacks to JS compilers, in search of a new, intuitive programming model that prioritizes people over machines.

### Author
- Jonas Gebhardt
- Front-end Engineer at Facebook Seattle, primarily working on Nuclide, an open-source, cross-stack IDE built with JavaScript.
- [Twitter](https://twitter.com/jonasgebhardt)
- [Github](https://github.com/jgebhardt)
- [Website](http://jonasgebhardt.com/)

**Comment by hamoore** [comment]
Awesome! Thanks for the proposal! We'll get back to you as soon as we have
a better idea of when your talk would best fit!

On Tue, Jan 19, 2016 at 11:10 PM Jonas Gebhardt <notifications@github.com>
wrote:

> Nuclide and the state of JS at Facebook
>
> Over the past 1-2 years, JavaScript has seen an explosion not only in
> popularity and size of the ecosystem, but also in language features and
> tooling. Facebook focuses heavily on improving developer efficiency, by
> building tools that not only make developers more productive, but
> ultimately make them better engineers.
>
> Flow, Babel, React (Native), Flux, Relay, Immutable.js, Jest, and
> jscodeshift are just a few of the tools that enable an effective workflow
> in a large, collaborative code base. Many of these tools are being
> consolidated in Nuclide <http://nuclide.io/>, an open-source,
> cross-stack, web+mobile IDE written in JavaScript (and yes, we use Nuclide
> to develop Nuclide!). In this talk, I'd like to show a glimpse of how we
> write JavaScript at Facebook, and how Nuclide provides a great platform for
> improving and evolving your own JS toolchain.
> Author
>
>    - Jonas Gebhardt
>    - Front-end Engineer at Facebook Seattle, working on Nuclide, an
>    open-source, cross-stack IDE built with JavaScript.
>    - Twitter <https://twitter.com/jonasgebhardt>
>    - Github <https://github.com/jgebhardt>
>    - Website <http://jonasgebhardt.com/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlejs/seattlejs/issues/59>.
>
-- 
Heather Moore
Office Manager

*Formidable*

**Comment by davidchang** [comment]
+1, would want to see this!

**Comment by jefflembeck** [comment]
@jgebhardt sounds fun! I bet some things have changed a bit since you originally suggested this (sorry). Would you still be willing to give it? Maybe in January?

Also, 10 min or 25 minute?

**Comment by jefflembeck** [comment]
@jgebhardt following up, any interest in still giving this?

**Comment by jgebhardt** [comment]
Sorry @jefflembeck for missing this. The contents might change slightly from the original proposal, but I'm still interested in giving a Nuclide / JS@FB talk. The ideal length would be closer to 25m. 

Do you already have a date for the January meetup?

**Comment by jefflembeck** [comment]
Hey @jgebhardt, we've actually filled the January slots, but haven't filled February yet. Our events are always on the second Thursday of the month, so February's is set for the 9th. Does that work for you?

**Comment by jgebhardt** [comment]
@jefflembeck Feb 9 could work! Let me know what materials you need by when.

**Comment by jefflembeck** [comment]
I just need a thumbs up from you on http://seattlejs.com/code-of-conduct
and you're good to go. We'll reach out again in January. Thank you!

**Comment by eliseworthy** [comment]
Feb's meetup is now live! Looking forward to your talk, and let me know if there are any changes I should make to the meetup page.

https://www.meetup.com/seattlejs/events/235567120/

**Comment by eliseworthy** [comment]
Changed the meetup to your new talk, @jgebhardt. Thanks!
