### ISSUE TITLE
Request to Host: 2016.12.8 @ Zillow!

### ISSUE THREAD

**Issue by robatron** [seattlejs/seattlejs#60]
## Company Info
- [Zillow Group HQ](http://www.zillowgroup.com/)
- [1301 2nd Ave, Floor 30, Seattle, WA 98101](https://goo.gl/maps/BpMDqdYZ6Xr)
- [Downtown District](http://www.seattle.gov/neighborhoods/neighborhood-districts/downtown)

Zillow understands the importance of support and involvement in the local software engineering community. We have a long history of [meetup involvement](https://www.google.com/search?q=zillow+inurl%3Ameetup.com) of all kinds, and have our own [Speaker Series](http://www.zillow.com/blog/tag/zillow-speaker-series/). We are always hiring, and love meeting engineers who are involved in the local community as well.
## Contact Info

Rob McGuire-Dale
Sr. Front-End Software Engineer
robmc@zillow.com

**Comment by robatron** [comment]
I'm not seeing a way to add labels or set milestones per the [request-to-host document](https://github.com/seattlejs/seattlejs/blob/master/request-to-host.md#submitting-a-hosting-request). Do I have appropriate permissions to do so?

**Comment by doolittle** [comment]
@robatron we've looked at Zillow in the past; the event space capacity was around 100. We usually have more than 200 attendees. Is there a larger space available?

**Comment by robatron** [comment]
Yes, we just hosted a [Python meetup last week](http://www.meetup.com/PSPPython/events/227337808/) in our main cafeteria, where there were ~180 attendees + employee drop-ins.

**Comment by hamoore** [comment]
@robatron Thank you! Zillow is interested in hosting for July, is that correct? We have generally been trying to be at the same location for three months to build more consistency (and brand recognition for the hosts!). Would Zillow be interested in taking on Q3 of this year (July-Sept)?

**Comment by robatron** [comment]
@hamoore , I will ask.

**Comment by hamoore** [comment]
@robatron Thank you! Also, since we haven't been in the space before, would it be possible for me or one of our organizers to come by and take a look just to verify that it will suit the needs of the meet-up?

**Comment by robatron** [comment]
@hamoore , sure thing :) Shoot me an email, and we can set up a time.

**Comment by robatron** [comment]
It sounds like we can host all of the Q3 (July-Sept.) monthly meetups! Let me know when you all would like to stop by for a visit to check out the space.

**Comment by hamoore** [comment]
That's fantastic! I'm am speaking with the organizers right now about setting up a time! Thank you!

**Comment by robatron** [comment]
Hi all, any updates on this after Wale visited on Feb. 2nd? Are we on for hosting for Q3?

**Comment by robatron** [comment]
Hi all, I understand from @hamoore that @doolittle would like to stop by to check out our space. When can we expect to hear back from you all about that? We'd like to know soon so we can plan accordingly.

**Comment by robatron** [comment]
Hello, I haven't heard from you all in about a month. When can we expect an update?

**Comment by hamoore** [comment]
Hi Rob! I've just pinged Brad and we'll hopefully have an answer for you soon! Sorry for the delay!

**Comment by robatron** [comment]
Are there questions we can answer and/or concerns we can resolve? When can we expect to hear back from you all?

**Comment by doolittle** [comment]
Responded via email.

**Comment by robatron** [comment]
It was great meeting you yesterday, @doolittle . To answer your questions:

> Due to the large attendance of SeattleJS during the summer, and the size of Zillow's meeting area, could Zillow host November and/or December instead, when attendance is lower?

Yes, we can host both months

> How many *seats* does Zillow have?

We have 120 stadium-style seats + 20 bar stools + ~10 bench seats. (Plus standing room for ~50.)

> Can Zillow provide food and drinks?

Yes, we can provide food and drinks.

What do you all think?

**Comment by hamoore** [comment]
Hello @robatron! I just wanted to check in and verify that we would love to be at Zillow for November and December if the option is still open?

**Comment by robatron** [comment]
Heya, we can probably do December, but not November. What's the target date for December?

**Comment by hamoore** [comment]
December's date is 12/8. Is that available?

Thank you so much for your patience with us and I'm sorry this whole process has ended up being so round-about! We really appreciate your involvement!

**Comment by robatron** [comment]
December 8th should work for us! Please pencil us in.

**Comment by robatron** [comment]
Hi all, there's just under one month until the December 8th meetup! We just wanted to confirm that you all are still planning on hosting at Zillow. Thanks :)

**Comment by robatron** [comment]
Ping. What's the plan for Dec. 8th?

**Comment by hamoore** [comment]
@robatron Thanks for pinging again- I thought I'd responded via email, but it clearly didn't go through! Yes, we'd love to still be at Zillow in December!

**Comment by robatron** [comment]
Oops, I forgot to mention that my email address domain changed since we last spoke: robmc@zillowgroup.com
