### ISSUE TITLE
Talk Proposal: Accessibility and Performance 

### ISSUE THREAD

**Issue by marcysutton** [seattlejs/seattlejs#63]
# Accessibility and Performance

How do slow performing JavaScript applications impact user experience for people with disabilities–are there certain aspects of the web rendering process that create barriers when you're relying on a screen reader? By studying the limitations of browsers with assistive technologies and establishing developer best practices, we can we make faster, more accessible experiences for our users. We'll frame Web Performance with an Accessibility lens, looking at progressive enhancement in detail with server- and client-rendered apps built with Angular 2, React or Ember FastBoot; always remembering our friend, static HTML.

Bio: Marcy Sutton is a Senior Front-End Engineer at Deque Systems, where she works on the axe-core team with a focus on integration into developer tooling. Marcy is passionate about improving the web for people with disabilities and she loves contributing to Angular as a core team member with an accessibility focus. Her blog, Accessibility Wins, highlights accessible user interfaces and tools, contributing a positive voice to the web development space. Marcy also co-organizes the Seattle chapter of Girl Develop It, a nonprofit encouraging women to learn about software.

* Marcy Sutton
* [Twitter](https://twitter.com/marcysutton)
* [Github](https://github.com/marcysutton)
* [Website](http://marcysutton.com)

**Comment by hamoore** [comment]
Thank you for your proposal! As we are getting our schedule set up for the year, we'll let you know an approximate date for when your talk would best fit as soon as we can!

**Comment by jefflembeck** [comment]
@marcysutton April work?

**Comment by marcysutton** [comment]
@jefflembeck I think so, but do you know what the date will be yet?

**Comment by hamoore** [comment]
@marcysutton The date will be April 14.

**Comment by marcysutton** [comment]
Perfect! Thank you :ok_hand:

**Comment by hamoore** [comment]
@marcysutton Do you have a headshot that I can put on the meet-up site? Additionally, what websites would you like me to link to?

**Comment by hamoore** [comment]
Oh wait, I just realized the websites are listed in the issue. Sorry!

**Comment by marcysutton** [comment]
Here is a bio photo: http://marcysutton.com/images/marcy-max-headshot-sq.jpg

Let me know if you need anything else!

**Comment by hamoore** [comment]
Perfect! Thank you! If you would like, Adobe can get you your own wireless log-in. If you are interested, I just need an email address?

**Comment by marcysutton** [comment]
Ha, I used to work there...I know the wifi system well. You can use marcy.sutton@deque.com. Thanks!

**Comment by hamoore** [comment]
Got it! :)
