### ISSUE TITLE
Talk Proposal -  Adding 3D Functionality to Your Web Applications

### ISSUE THREAD

**Issue by Wayne-Brill** [seattlejs/seattlejs#64]
Adding 3D Functionality to Your Web Applications

Most of the web is very flat but it doesn’t have to be. Having 3D content on your site makes it much more appealing. This presentation will show a mix of 3D on the web technologies and how easy it is nowadays to add 3D to your websites. The underlying technology that makes this possible is WebGL which is supported by most browsers and devices. Using WebGL directly allows you to add 3D content but learning WebGL would take a lot of time. I will be demoing server/client samples of a View & Data web service that makes it very easy to add 3D content to your web page and you don’t have to be an expert in WebGL, only the basics of JavaScript and HTML5 is required . 
 
Wayne Brill is a developer consulting engineer. His current specialty is Autodesk Inventor and Fusion 360 software customization and programming. Within the past few years, he has also been polishing his web development skills and exploring areas in WebGL and Three.js, along with the new Autodesk Forge platform. 

Twitter: ‏  @wayne_brill
GitHub:    https://github.com/Developer-Autodesk
Website:  https://developer.autodesk.com/api/view-and-data-api/
Email:  wayne.brill@autodesk.com

**Comment by hamoore** [comment]
Thank you Wayne! As we are curating and organizing talks, we will get back to you when we have a better idea as to when your talk would best fit!

**Comment by jefflembeck** [comment]
I dig this one. @Wayne-Brill - Any chance you'd be interested in giving this talk in May?

**Comment by Wayne-Brill** [comment]
Hi Jeff,
Yes May will be fine. 
Thanks!

**Comment by hamoore** [comment]
Hello @Wayne-Brill! As we are getting prepared for the upcoming May meet-up happening on the 12th, I was wondering if I could get a photo from you for the website, as well as any sites you'd like us to link to (twitter, blog, website, etc). Thanks!

**Comment by Wayne-Brill** [comment]
Hi,
Please let me know if the attached picture will be good.

Here are the sites.

http://webglfundamentals.org/
http://learningwebgl.com/blog/?p=28
http://www.udacity.com/course/interactive-3d-graphics--cs291
http://lmv.rocks/
http://developer.autodesk.com/api/view-and-data-api/
http://developer-autodesk.github.io/
 
![pic_for_seattlejs_wb](https://cloud.githubusercontent.com/assets/4193104/14933022/93bbb164-0e36-11e6-8aa1-a335128f98ec.jpg)

Thanks,
Wayne

**Comment by hamoore** [comment]
Looks good! Thanks!
