### ISSUE TITLE
Talk Proposal - Wrangling lots of JavaScript Projects with Builder

### ISSUE THREAD

**Issue by ryan-roemer** [seattlejs/seattlejs#65]
Modern JavaScript is awesome! And _complicated_. And a logistical nightmare, especially as the number of repositories in your organization grows.

We have so many tools: ES-next, Babel, Eslint, Istanbul, Mocha, Chai, etc. And if you're using [npm workflows](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/), you have lots of `scripts` tasks, `dependencies`, and `devDependencies` proliferating across your projects.

We have [JavaScript fatigue](https://medium.com/@ericclemmons/javascript-fatigue-48d4011b6fc4#.ob19mz7ht).

In this talk, we'll discuss the fundamental build and development issues facing modern JavaScript. And we'll examine options for managing multiple repositories and development, production and publishing workflows, with a focus on a new tool: `builder`.

The [`builder`](https://github.com/FormidableLabs/builder) project attempts to wrangle one aspect of this chaos - keeping tasks for many, nearly identical projects in sync. Basically, it moves all the build, test, and dev `scripts` tasks from a project's `package.json` files and to a central source of control. Builder's tight focus is on:

* Providing a **single point of control** for your projects.
* Capable of bootstrapping new projects with verified templates and layouts.
* Being **flexible** enough for deviations in projects and going "off script".
* Being so close to `npm` workflows that you can easily _give up_ on builder in a straightforward manner.

Using `builder`, we've been able to coordinate dev, test, and workflows for the ~15 [Victory React component](http://victory.formidable.com/) repositories we maintain at [Formidable](http://formidable.com/). At Walmart Labs, builder controls over 50 repositories, with builder "archetypes" managing Walmart's react components, hapi plugins, Node.js servers, and more.

Ultimately, we've found that you cannot stop the complexity of modern JS, but you can manage and focus it.

---

Ryan is the CTO and co-founder of [Formidable](http://formidable.com/), a boutique JavaScript development shop. He organizes the [Seattle Node.js Meetup](http://www.meetup.com/Seattle-Node-js/) and is the author of ["Backbone.js Testing"](http://www.amazon.com/Backbone-js-Testing-Ryan-Roemer/dp/178216524X), a comprehensive test development guide for modern JavaScript web applications.

Ryan architects full-stack JavaScript applications and backend Node.js services, and leads frontend development groups ranging from small startups to Fortune 500 engineering teams. Previously, Ryan was a distributed systems engineer, and in his deep, dark past was a patent attorney, although it has been a long time since he has put on his "lawyer" hat.

* Ryan Roemer
* [Twitter](https://twitter.com/ryan_roemer)
* [GitHub](https://github.com/ryan-roemer)
* [Website](http://formidable.com/)

**Comment by hamoore** [comment]
Thanks, Ryan!

**Comment by jefflembeck** [comment]
Hey @ryan-roemer, this sounds neat. Can you do this March 10?

**Comment by ryan-roemer** [comment]
@jefflembeck -- Great! Yep, March 10th works for me.

**Comment by codefoster** [comment]
@ryan-roemer what video adapter do you need for your laptop?

**Comment by ryan-roemer** [comment]
@codefoster -- I've got the "Seattle standard issue macbook", so display port and HDMI. I can bring adapters if needed, but if memory serves from last time Seattle Node hosted at EMC, they had HDMI when I plugged in my laptop to MC the introduction.

**Comment by codefoster** [comment]
Thanks, Ryan. I was asking for the guys that are going to hook into the video feed to record screens for the on-demand. We'll be ready for ya.

**Comment by ryan-roemer** [comment]
Great. Thanks Jeremy!
