### ISSUE TITLE
Build Amazing Single Page Applications with DoneJS

### ISSUE THREAD

**Issue by joe-crick** [seattlejs/seattlejs#66]
# Build Amazing Single Page Applications with DoneJS

In this talk we'll learn about how DoneJS, the successor of JavaScriptMVC - one of the first client side JavaScript frameworks - can be used to build real-time high-performance web, desktop and mobile applications. Utilizing the latest tooling, and awesome integration, DoneJS makes it easy for you to get your apps built fast.

We'll build a fast, real-time single page chat application with DoneJS and talk about: 
• Server side rendering/Isomorphic JS 
• Progressively loading optimized bundles 
• Use of content delivery networks (CDNs) 
• Desktop and mobile application builds 

BIO:
David Luecke, a Canadian by way of Germany, is the lead maintainer of CanJS and a core contributor to DoneJS.
- David Luecke
- [Github](https://github.com/daffl)
- [Twitter](https://twitter.com/daffl)

**Comment by hamoore** [comment]
Thanks for your submission! We'll get back to you as soon as we can with an approximate date... we are working on curating events around similar topics.

**Comment by jefflembeck** [comment]
Hey @joe-crick, how long is this talk? We're putting together the next couple of months and balancing out times (10ish or 25ish minutes)

**Comment by joe-crick** [comment]
Hi Jeff,

I’ve done the talk in 5 minutes before! However, ~20 minutes is a good time.

Thanks!

Joe

**Comment by jefflembeck** [comment]
@joe-crick I'll let you make the call. ~10min or ~25min. January 12th work?

**Comment by joe-crick** [comment]
Hi Jeff,

January 12th works. Please schedule us for 25 minutes.

Thanks!

Joe

**Comment by jefflembeck** [comment]
@joe-crick Perfect! please see our Code of Conduct http://seattlejs.com/code-of-conduct and let me know if you agree with it before you speak. Thanks!

**Comment by joe-crick** [comment]
Hi Jeff,

David Leuke will be the speaker for the event. I’ve cc:’d him on this email. 

DAVID:

Jeff has asked

Please see our Code of Conduct http://seattlejs.com/code-of-conduct <http://seattlejs.com/code-of-conduct> and let me know if you agree with it before you speak. Thanks!

—

Joe Crick

Development | Training | Support
Bitovi.com <http://www.bitovi.com/> | Twitter: @Bitovi <http://twitter.com/bitovi>

**Comment by jefflembeck** [comment]
@joe-crick Following up for next month.

David hasn't replied on here and I want to make sure he agrees with the Code of Conduct and also am wondering what picture he would like us to use for the website.

**Comment by daffl** [comment]
Sorry, I must've missed this. I do agree with the COC and also have an alternative talk proposal. Not  trying to change it up at the last minute and can still follow the old proposal but I feel it might fit better into 25 minutes.

## A Brief History of Single Page Applications

JavaScript applications have come a long way the past 8 years. In this talk I'd like to revisit the history of single page applications and how JavaScriptMVC - and now DoneJS - are dealing with this ever changing landscape.

BIO:

David Luecke, a Canadian by way of Germany, is the lead maintainer of CanJS and a core contributor to DoneJS.

David Luecke
[Github](https://github.com/daffl)
[Twitter](https://twitter.com/daffl)

**Comment by eliseworthy** [comment]
Hey @daffl, we're posting the meetup with your details right now. Looking forward to your talk on the 12th, and we've got you down for 25 minutes.

**Comment by codefoster** [comment]
Closing this off. Thanks for the presentation, @daffl
