### ISSUE TITLE
Sponsor Request: Amazon

### ISSUE THREAD

**Issue by virajsanghvi** [seattlejs/seattlejs#67]
# Company name: Amazon

We're running a web development conference in late April, with speakers from Amazon and other companies, and are opening it to the public. We think it'll be a great opportunity to learn and interact, and are looking to get the word out to the greater Seattle developer community by sponsoring drinks for the March meetup.

## Contact Info

Viraj Sanghvi
virajs@amazon.com

**Comment by hamoore** [comment]
@virajsanghvi I have tagged this for March & April, so you do not need to make another request for April. :)

**Comment by hamoore** [comment]
@virajsanghvi I take that back... I was unable to add two milestones. Have now tagged it just for April, with the understanding that it is for both. :)
