### ISSUE TITLE
Talk Proposal - Rise of the Workers

### ISSUE THREAD

**Issue by axemclion** [seattlejs/seattlejs#68]
Modern web applications are awesome. And complicated. The Javascript libraries that power them today do a lot of work to abstract away the hard parts. Whether using constructs like Virtual DOM, or fancy change detection algorithms, the amount of work that the Javascript library does is only increasing. 

Unfortunately, all this work now competes for the same resources that the browser needs, to do things like render a page, or apply styles. In many cases, this makes the browser slow, preventing the web application from attaining its full, smooth experience. 

Web workers have been in the browser for a while, but they have mostly been used for engaging demos like adding mustaches in a cat video :) 

In this talk, we will explore how mainstream Javascript libraries like React or Angular use Web Workers to get great performance. We will look at quantitative numbers from hundreds of test runs that conclusively show how Web Workers can make apps faster.

Finally, we will also look at practical examples to convert existing examples, and the potential limitations of this approach.

---

## About the speaker
Parashuram is a front end developer and web performance enthusiast and author of tools like [browser-perf](http://github.com/axemclion/browser-perf). He has created the [Web Worker based render for ReactJS](http://blog.nparashuram.com/2016/02/using-webworkers-to-make-react-faster.html) and runs "science-like" experiments to explore ways to make web applications faster.

He is also an open source contributor, a committer in the Apache Cordova project and works as a Program Manager in Microsoft.

**Comment by hamoore** [comment]
Thank you for your proposal! As we continue to fill in our schedule for the upcoming meet-ups, we'll ping you about timing for your talk!

**Comment by jefflembeck** [comment]
@axemclion does June 9th work for you?

**Comment by axemclion** [comment]
I may not be able to do it in June, can we do it in July ?

**Comment by jefflembeck** [comment]
Sure thing. Let's do it.

**Comment by axemclion** [comment]
Thanks - let me know of a date that would work.

**Comment by jefflembeck** [comment]
That would be July 14th

**Comment by hamoore** [comment]
@axemclion, would you be able to give me a high-res headshot image to use on the meetup site? Additionally, would you like us to link to your blog and do you have a twitter that you'd like us to link to?

**Comment by hamoore** [comment]
@axemclion I'm working on getting the meet-up page updated currently, so I will update with the information currently available. Please let me know if you'd like me to change anything re: links/pictures! :)

**Comment by axemclion** [comment]
@hamoore Here are some links 
twitter - http://twitter.com/nparashuram/
blog - http://blog.nparashuram.com (i see that this is already linked)

I think the other content looks good - thanks.
