### ISSUE TITLE
Talk Proposal - Hello TypeScript!

### ISSUE THREAD

**Issue by bowdenk7** [seattlejs/seattlejs#69]
TypeScript is no longer the new kid on the block. Today, it is used to build several popular frameworks like Angular 2, Ionic 2, and NativeScript as well as massive applications such as Visual Studio Code, Office Web Applications, and more. But why are JavaScript developers flocking to TypeScript? In this talk, we'll examine how TypeScript enables you to spend more time writing code and less time maintaining it. We will show how TypeScript builds on top of JavaScript's excellent foundation with an optional type system and access to ES6+ features in order to supercharge development productivity. We'll also show a few quick demos to show how easy it is to get started with TypeScript regardless of your existing JavaScript environment. 

Bowden is a program manager at Microsoft working on the JavaScript editing experience and the TypeScript language. 

Twitter: @bowdenk7
GitHub: http://github.com/microsoft/typescript
Website: http://typescriptlang.org
Email: wilkelly@microsoft.com

**Comment by hamoore** [comment]
Thank you for your talk proposal! We will get back to you as soon as we can about scheduling!

**Comment by jefflembeck** [comment]
Hi @bowdenk7, how do you feel about giving this at our October meetup? It is on October 13th.

**Comment by bowdenk7** [comment]
Works great! Let me know what else you need. Thanks!

**Comment by hamoore** [comment]
@bowdenk7 The only other thing I need is a headshot- I can pull it off github, but if you have a higher res photo, I'd love to use that instead! :)

**Comment by bowdenk7** [comment]
Does this work?
![pic2](https://cloud.githubusercontent.com/assets/820883/18898959/215764d0-84ea-11e6-8905-13cf109923d4.jpg)

**Comment by jefflembeck** [comment]
@bowdenk7  please see our Code of Conduct http://seattlejs.com/code-of-conduct and let me know if you agree with it before you speak. Thanks!

**Comment by bowdenk7** [comment]
@jefflembeck @hamoore Just to double check, how much time do I have?

**Comment by jefflembeck** [comment]
Shoot for 25 minutes. More or less is fine
