### ISSUE TITLE
Talk Proposal: Nom Nom: Consuming Rest API's

### ISSUE THREAD

**Issue by tmero** [seattlejs/seattlejs#70]
Feeling hungry? You’ve came to the right place! As APIs have become increasingly more important and popular in usage in the past few years in web development, it is important to understand the basics of what they are and why to use them. I will be going over the basics: The What’s, Why’s, Where’s, and When’s. You will learn the basics of REST APIs and I will show you how you can use POSTMAN to test making REST API calls. I will use Cisco’s Spark and Tropo as use case examples of working with APIs.

Tessa Mero is the Developer Evangelist for Cisco. She spends her extra time contributing on a leadership team for the Joomla! Project and has been involved with Joomla for the past 5 years. She runs the Seattle PHP Meetup and is the organizer of the Pacific Northwest PHP conference. On her free time, she likes to play video games, snowboard, and eat Korean food.

Twitter: @tessamero
Website: http://tessamero.com
Email: tmero@cisco.com

**Comment by jefflembeck** [comment]
@tmero how's September 8th sound?

**Comment by tessamero** [comment]
That's a week before my conference I'm running . I may be under a ton of stress and pressure. Can we move it out to November ? :-)

**Comment by jefflembeck** [comment]
@tessamero @tmero Hey Tessa, how long is this talk?

**Comment by tessamero** [comment]
Hmm it's 30-40 minutes. (Q&A takes 15 on top of that), sometimes no QandA).

Ahh you're going to be upset but as of last week I was assigned to sponsor a JavaScript Conference in December. I'm probably getting back the 6th or 7th and then crashing hard when I get home from timezone changes.

**Comment by jefflembeck** [comment]
All gravy. As you know, we don't do Q&A. We can likely push back until January/Feb/whenever works best for you...

**Comment by tmero** [comment]
Ahh okay :) Yes, it may be best to use me as a last resort in case someone cancels or can’t make it. And if I’m home that entire week I can make last minute arrangements. Could you keep me in mind for this too??

**Comment by ChrisRus** [comment]
If this talk is scheduled, I volunteer to do a lightning talk on Encapsule/hrequest - an isomorphic HTTP request library that wraps the popular Node.js request module (Node.js) and XMLHttpRequest (client) in a declaratively configured "filter" that provides data I/O message validation/normalization (i.e. default values), and normalized error handling. Allows you to write a little JSON document to declare acceptable I/O formats from your endpoint, and get 100% test coverage w/no extra work.

https://www.npmjs.com/package/hrequest

**Comment by tmero** [comment]
Hmm this talk is no longer scheduled as I did a talk on chat bots instead :)

**Comment by codefoster** [comment]
@tmero, do you still want to do this talk? If you can squeeze it into a lightning talk (~10 min), you can do it May 11.

**Comment by tessamero** [comment]
I spoke on this topic a couple months ago. I'll be in Italy during that day in May (i am a dev evangelist), but I'm definitely interested in doing a lightning talk!

**Comment by codefoster** [comment]
There's a slot on June 8 for a lightning talk if that works for you. Submit a new issue here and we'll get you scheduled. I'll close this one out.

**Comment by tmero** [comment]
Jeremy, I didn’t pay attention to the talk title in the subject and thought this whole conversation was on chat bots.

Can you clarify which talk you wanted a lightning talk? Did you want the REST API one?

**Comment by codefoster** [comment]
Yep. This conversation is in an issue called _Nom Nom: Consuming Rest API's_. Can you do that in 10 minutes?

**Comment by codefoster** [comment]
Actually, I see this comment is closed and there's a [new one](https://github.com/seattlejs/seattlejs/issues/92) open with the same title. We'll use that.

**Comment by tmero** [comment]
I have done this as a lightning talk before and actually have the slides for it.

 I did this one time at a javascript meetup in France about 4 months ago. Let me know what you think:

https://www.slideshare.net/Tessa99/understanding-rest-apis-in-5-simple-steps-69937208

I’m happy to make any changes necessary (making it shorter / taking out or adding sections)


Thanks!

**Comment by codefoster** [comment]
(left my reply in the [new issue](https://github.com/seattlejs/seattlejs/issues/92))
