### ISSUE TITLE
Talk Proposal: JavaScript Workshop for the Absolute Beginners

### ISSUE THREAD

**Issue by tmero** [seattlejs/seattlejs#71]
Did you join the meetup to browse and see what's going on? Do you feel some topics may be too advanced? After teaching web application development at a community college in Lynnwood, WA, I'd love to teach you the very basics of programming so you feel more confident going to future meetups. You will learn the foundations of programming with JavaScript, working with variables, arrays, looping, conditional statements, and all sorts of cool things! If there is time, I'll throw in some jQuery too!

Tessa Mero is the Developer Evangelist for Cisco. She spends her extra time contributing on a leadership team for the Joomla! Project and has been involved with Joomla for the past 5 years. She runs the Seattle PHP Meetup and is the organizer of the Pacific Northwest PHP conference. On her free time, she likes to play video games, snowboard, and eat Korean food.

Twitter: @tessamero
Website: http://tessamero.com
Email: tmero@cisco.com

**Comment by codefoster** [comment]
@tmero, I know you're talking about chatbots at the Feb meetup. Are you interested in doing this intro workshop in the future too?

**Comment by tessamero** [comment]
Yes definitely!

**Comment by codefoster** [comment]
Great. What would the format be. If you call it a workshop, I suspect folks will expect to work along. Does it fit in a "feature" presentation which is an all-eyes-forward 25 min preso, or should we talk about doing something more in-depth between monthly meetups where we can dedicate a big chunk of time?

**Comment by tmero** [comment]
I have done this presentation once at a hackathon last week. It was about 90 minutes long. For this meetup I may be running through it quickly since it’s a “follow along” type of presentation.

But the goal, for a short presentation, is so they can take a copy of the slides with them and they can also work on it at home. Very easy steps to build it :)

**Comment by codefoster** [comment]
Okay. Let's table this for now and I'll talk with the other organizers about it.

**Comment by tmero** [comment]
Also, if I’m going to do this again at the seattlejs meetup and make it a workshop, I can put some time into making the code way more fun than just a “hello world”. I can make it do some fancy stuff and have time to even go over the code! :) So I’m looking forward to a real workshop. :)

**Comment by tessamero** [comment]
That's a tough one. It depends if I take the time to help people follow along. If I'm stopping several times I can do this in 90 minutes.

I gave this talk at the seattle JS Meetup last week so maybe get feedback also from someone who attended :)

**Comment by tessamero** [comment]
Of course apple mail shows emails out of order. I just read your last message. Somehow the older message showed up as new, lol

**Comment by codefoster** [comment]
I accidentally closed this issue and reopened it. Pay no attention to the man behind the curtain :)

**Comment by tessamero** [comment]
Hahaha
