### ISSUE TITLE
Talk Proposal: Continuous Security

### ISSUE THREAD

**Issue by evilpacket** [seattlejs/seattlejs#73]
# Continuous Security

Adam's talk will discuss how to shift culture to give application security the attention that it needs and how to adopt a continuous security process for your team, one that isn't obstructive and annoying but enabling so you can write better, more secure software.

Bio:
Adam Baldwin is the Chief Security Officer at [&amp;yet](andyet.com) and the Team Lead at [^lift security](liftsecurity.io) where he helps developers secure all the web things! He is the Founder of the [Node Security Project](nodesecurity.io) &amp; talks about node security non-stop. In his free time Adam enjoys doing basically the exact same stuff he does for work, also raising chickens, and spending as much time as possible with his wife and 2 children.

* Adam Baldwin
* [Twitter](https://twitter.com/adam_baldwin)
* [Github](https://github.com/evilpacket)

**Comment by jefflembeck** [comment]
_YES_

July it is.

**Comment by hamoore** [comment]
Hi @evilpacket! Do you happen to have a high-res image I can put on the meetup page or would you prefer for me to pull your github profile image?

**Comment by evilpacket** [comment]
Github profile image is just fine with me :)
