### ISSUE TITLE
Talk: Contemporary API Design - Declarative Data, Graphql, Falcor and other buzzwords from 2016

### ISSUE THREAD

**Issue by baer** [seattlejs/seattlejs#76]
# Contemporary API Design - Declarative Data, Graphql, Falcor and other buzzwords from 2016

  `Contemporary API design` is an exploration of the past, preset and future of API design with a focus on the emerging trend towards tooling rich, declarative, filterable data. API design has come a long way since RPC in the 60s and now, nearly two decades after Fielding's seminal paper, REST is starting to creek under the weight of mobile development. Given the renewed demand to serve underpowered devices on unreliable networks this talk aims to shed light on some of the new client-server interaction models with ones more suited to these needs. Specifically, I plan to give into Falcor and GraphQL as well as give a short live coding demo to show, rather than tell, of some of the surprising simplicity in developing these new APIs.

---

Eric is a full-stack developer and has done everything from embedded systems to high traffic APIs. Over the last five years Eric has developed a deep specialization in JavaScript and the associated ecosystem. Currently Eric works as a lead engineer at Formidable in Seattle where he is driving large projects and writing OSS around Babel tooling, GraphQL and i18n.
- Eric Baer
- [Twitter](ebaerbaerbaer)
- [Github](https://github.com/baer)

**Comment by divmain** [comment]
Thanks for submitting @baer!  We have a slot open on November 10 - does that work for you?

**Comment by jefflembeck** [comment]
@baer following up with @divmain's comment - This talk sounds interesting. How long is it and would you like to give it in November?

**Comment by baer** [comment]
November works for me, yes. I have a 1h talk already prepared but I could cut it down to length. Happy to accommodate any time slot. The end section is more about GraphQL specifically so I'd probably scrap a lot of that including the live-code demo and the section on client side integration since there are plenty of other resources out there around getting up and running with GraphQL.

**Comment by jefflembeck** [comment]
@baer sorry for the slow response. How does 25 minutes work?

**Comment by baer** [comment]
I can work with 25 min but that is ~1/2 of the content. Luckily the talk is, more or less, in two parts: API design and GraphQL. Since you will have much more contet into the what the average audience is and what talks were well recieved, what part of the talk would you find most useful for this audience? 

The arc of the talk is as follows:

1. Brief history of API design, problems with each and lessons learned.
2. Given the history, what might a better client-server model look like?
3. GraphQL + live code of a GraphQL server.
4. GraphQL client implementations

**Comment by jefflembeck** [comment]
I think the second half would go over really well. GraphQL has been on the
mind of a lot of folks lately.

**Comment by baer** [comment]
I'll see what I can do. GraphQL without context is just another tool on the pile. Thanks for you help! I'll see you then.

**Comment by jefflembeck** [comment]
@baer to be honest with you. If you feel like you'd have a better talk with 2&3, I'm super into it. You make this compelling and if you want, I'll gladly help with narrative.

**Comment by jefflembeck** [comment]
@baer  please see our Code of Conduct http://seattlejs.com/code-of-conduct and let me know if you agree with it before you speak. Thanks!

**Comment by baer** [comment]
Thanks so much for the opportunity to present last week. I had a great time and I'm very appreciative of all the work you do to put these things together!
