### ISSUE TITLE
Talk Proposal: Getting Rich Off Snippets with Client-Side Rendering

### ISSUE THREAD

**Issue by cava23** [seattlejs/seattlejs#77]
Client-side rendered apps are easy to set up, fast, and prevalent. However, rendering your content client-side requires that crawlers be a little smarter and wait for all your content to load, including AJAX calls. A great example of this deficiency is when sharing rich snippets. Even if you add opengraph tags, your rich snippet will look like it's well below the poverty line because the client won't wait for your content to load. For a B2C company like TRED, that sucks.

In my talk I will discuss the possible solutions to this problem, switching to a server-side rendered architecture or serving prerendered content to certain user-agents, and how we solved it at TRED using a service called Prerender.io. I'll then progress beyond the initial implementation (that part is crazy simple) and describe the devops challenges we discovered, how our automated tests caught them, and how we solved those problems to finalize the project.

I'm currently the CTO of TRED.com and was previously CEO of my own startup, Variat.io. From a mixed background of Mechanical Engineering and Computer Science I've written software on a variety of platforms including embedded, web, and mobile. JavaScript has been my language of choice since 2013.

Andrew Crowell
https://www.linkedin.com/in/andrew-crowell-b49807aa
https://twitter.com/__drew___

**Comment by jefflembeck** [comment]
@cava23 how long of a talk is this?

**Comment by cava23** [comment]
I've never given it before, but I can probably fill 20-25 minutes on this topic.

**Comment by jefflembeck** [comment]
Perfect. Thanks!

December 8 work for you?

**Comment by cava23** [comment]
Yep, sounds like a plan.

**Comment by jefflembeck** [comment]
@cava23 please see our Code of Conduct http://seattlejs.com/code-of-conduct and let me know if you agree with it before you speak. Thanks!

**Comment by hamoore** [comment]
@cava23 in addition to Jeff's request above, do you have a headshot we can use to update the meetup page? :)

**Comment by cava23** [comment]
Sorry Jeff, didn’t see your note from before. This is tough, but yes, I agree not to be a terrible person.

Headshot attached:

**Comment by hamoore** [comment]
@cava23 Hmmm it doesn't seem to be attaching. Would you mind emailing it to me directly at heather.moore@formidable.com? :)
