### ISSUE TITLE
Talk Proposal: "The most popular browser" Lightning! 

### ISSUE THREAD

**Issue by nuria** [seattlejs/seattlejs#78]
# The most popular browser

 Wikipedia  projects reach hundreds of millions of unique devices every month and, as such, are a good barometer of browser popularity. For every pageview that comes into one of our projects, we note the browser and the OS of the device and report that data, aggregated weekly. Data is public and free to the world, in line with our values and privacy policy. 

In this lighting talk we will demo the browser dashboards where developers can get browser statistics for the internet at large for free. 
- Nuria Ruiz
- https://twitter.com/pantojacoder

**Comment by jefflembeck** [comment]
Ooooooo.

December 8th work for you?

**Comment by nuria** [comment]
December 8th would work, November 11th would be better though, if possible. Thank you.

**Comment by jefflembeck** [comment]
Awesome. Let's do November then!

**Comment by nuria** [comment]
Sorry, November 10th right? (2nd thursday?)

**Comment by jefflembeck** [comment]
Yes!

**Comment by jefflembeck** [comment]
@nuria please see our Code of Conduct http://seattlejs.com/code-of-conduct and let me know if you agree with it before you speak. Thanks!

**Comment by nuria** [comment]
Agree, thanks for having a code of conduct.

**Comment by hamoore** [comment]
Hello Nuria! Is it possible to get a short bio from you, as well as a large headshot file? :)

**Comment by nuria** [comment]
Hello! Does this work?
https://wikimediafoundation.org/wiki/User:NRuiz_(WMF)

**Comment by hamoore** [comment]
Two in one... perfect! :)
