### ISSUE TITLE
Talk Proposal: Why (not) build Progressive Web Apps

### ISSUE THREAD

**Issue by juniperbelmont** [seattlejs/seattlejs#79]
Progressive Web Apps (PWAs) are the new big thing in web development, but it’s a mistake to simply endorse or reject them. More than a set of technologies, PWAs are about reframing how we build apps for the web and mobile. They’re about building speed and security and responsiveness right into the app instead of relying on fast devices and connections. They’re about making web apps do everything native apps can do without rewriting your entire codebase for different platforms.
In this talk you’ll learn about building progressive web apps and decide why you might or might not want to.

(p.s. I might update the slides to bring the focus back more about what progressive web apps are.)

Juniper Belmont
Developer Advocate at Vaadin
- I'm passionate about the open web platform and using the features within the browser, and those features that are up and coming, to build better apps. I formerly worked on the Dart Project before taking this job where I do developer advocacy (talks, blog posts, conferences) about Web Components and Progressive Web Apps.

Twitter: @juniperbelmont
Email: juniper.belmont@gmail.com

Slides: https://speakerdeck.com/juniperbelmont/why-not-build-progressive-web-apps

**Comment by jefflembeck** [comment]
Hey @juniperbelmont! This talk looks great. How long does it normally take for you to give it?

**Comment by juniperbelmont** [comment]
It's built to fit a 20-25 min time slot, but I can make it slightly longer or shorter if need be.
There's a LOT of questions after it, though.

**Comment by jefflembeck** [comment]
@juniperbelmont 25 minutes is perfect and we actually don't have a Q&A session, so you can duck out if you want or talk with people after while we hang out :)

**Comment by juniperbelmont** [comment]
Sure. Just let me know what month the talk will be good in.

**Comment by jefflembeck** [comment]
December 8 work?

**Comment by juniperbelmont** [comment]
Yes! I'll be there.

**Comment by jefflembeck** [comment]
@juniperbelmont please see our Code of Conduct http://seattlejs.com/code-of-conduct and let me know if you agree with it before you speak. Thanks!

**Comment by juniperbelmont** [comment]
Definitely, and I'm really happy your code of conduct is so rigorous. I'm usually the one that asks groups to update their CoC from, "don't be a jerk," to something like yours. 👍
