### ISSUE TITLE
Talk Proposal: Viro Media: Enabling VR development for web and mobile developers using Javascript + React 

### ISSUE THREAD

**Issue by VikAdvani** [seattlejs/seattlejs#80]
Short Description
The Viro platform enables developers to easily build immersive **native** VR experiences using familiar web and mobile technologies.  If you are interested in building new VR applications or adding VR features into your existing mobile app, the Viro platform is perfect for you.

It’s as simple as coding <ViroText text=”I’m making a VR app!” /> 

Some examples of experiences you can build using Viro include:
- Interactive 360 photo tours for real estate and travel
- Media players for video/360 video in an immersive VR environment
- Rich immersive storytelling in 3D

Viro modifies React Native native to work on mobile VR platforms, so you can create native VR applications using just Javascript with the React framework. 

Bio
Vik Advani is the co-founder and CTO of Viro Media.  Previously, he co-founded UpNext, a 3D mapping startup, that was acquired by Amazon in 2012.  He spent 3 years at Amazon building out the Amazon Maps platform and the Amazon Local Search service.  Prior to UpNext, Vik spent 5 years in the video game industry.  His experience and personal interest in 3D and visualization, led him to start a VR company in Seattle with the goal of enabling VR development everywhere.

Name: Vik Advani
Twitter: @vikadvani
Github: https://github.com/VikAdvani
Website: www.viromedia.com
Viro Documentation: http://docs.viromedia.com/
Sample Viro VR App: https://github.com/viromedia/viro-code-samples

**Comment by jefflembeck** [comment]
Hey @VikAdvani,

How long is this talk?

**Comment by VikAdvani** [comment]
Hi @jefflembeck, the talk would be up to 15 minutes. Let me know if you need any more information. Thanks!

**Comment by codefoster** [comment]
Hey, @VikAdvani, how about March 9?

**Comment by VikAdvani** [comment]
Hi @codefoster, thanks for getting back to us! We'll be in a crunch mode during then, is there a spot in April that works? We'll have a lot more platforms up and running by April(including Google Daydream and Samsung Gear VR). Let me know, thanks!

**Comment by codefoster** [comment]
How about May 11? If this works, please read our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and express your agreement.

**Comment by codefoster** [comment]
Actually, April 13 works. I'll put you down for that. Agree to the code of conduct and we'll be all set.

**Comment by VikAdvani** [comment]
Hi @codefoster, thank you! April 13th is perfect. I read and agree with the code of conduct.

**Comment by codefoster** [comment]
@VikAdvani , I just wanted to make sure you saw that we had a change of venue for this event. We're now going to be at Simply Measured. The details are on the [meetup event page](https://www.meetup.com/seattlejs/events/230354991/). You're still on to deliver a ~10 minute lightning talk, right?

**Comment by VikAdvani** [comment]
@codefoster Thanks for the update! Yep, still on to deliver 10 minute lightning talk! Looking forward to it!
