### ISSUE TITLE
Develop Quick Applications with Google Apps Script 

### ISSUE THREAD

**Issue by terrywbrady** [seattlejs/seattlejs#81]
# Develop Quick Applications with Google Apps Script 

[Google Apps Script](https://developers.google.com/apps-script/) is a server-side JavaScript implementation with access to the API's for several Google Services.  If you are building an application for users who already have a Google account, you can use your JavaScript skills to create an application that can access a user's personal content on Google.  

A Google Script application can exist on its own, within a Google Document/Spreadsheet or as a standalone web service.  All you need to get started is a Google Drive account.  In this presentation, we will walk through the creation of each of these types of applications and discuss how each type of application can be useful.

At the Georgetown University Library, Terry has deployed a number of [simple applications](http://georgetown-university-libraries.github.io#google-sheets) for library staff using Google Apps Script.

Terry Brady is a software developer in Seattle working for the Georgetown University Library.  Terry is a committer for the [DSpace](http://dspace.org/) repository platform.  Terry has built applications for higher education, government, non-profit, and corporate institutions including LexisNexis and the National Archives and Records Administration.

* Terry Brady
* [Github](https://github.com/terrywbrady)
* [Website](http://georgetown-university-libraries.github.io/)

**Comment by jefflembeck** [comment]
Hey @terrywbrady,

This talk sounds like you could show how to solve some really interesting problems with this. Do you think you could have it ready for January 12th?

**Comment by terrywbrady** [comment]
@jefflembeck , Jan 12 sounds great to me.  I think a 25min session sounds good.  Thanks

**Comment by terrywbrady** [comment]
@jefflembeck , I was unable to attend yesterday's meeting, but I am looking forward to the Jan meeting.  I have a template slideshow at https://gitpitch.com/terrywbrady/UsingAppScript/master?grs=github&t=white which I will be refining for time.  Let me know if you need any additional info from me.

**Comment by eliseworthy** [comment]
Hey @terrywbrady! I'm posting your talk for our January meetup right now. We've got you down for 25 minutes - really looking forward to it!

**Comment by terrywbrady** [comment]
@eliseworthy , thank you for the note.  I am excited for the opportunity to present!  I will see you next month.

**Comment by terrywbrady** [comment]
@jefflembeck , @eliseworthy , my presentation is here. https://gitpitch.com/terrywbrady/UsingAppScript/SeattleJs?grs=github&t=white

I will have my laptop with me.  I will be planning to run a live demo as a part of the talk.

I look forward to seeing you all tomorrow.
