### ISSUE TITLE
Talk Proposal: Alt-Ctrl : Scream into this Arduino

### ISSUE THREAD

**Issue by rachelnicole** [seattlejs/seattlejs#82]
For February 9th Seattle JS

Abstract

When you think about nodebots, the first thing that pops into your mind is probably cute little robots (as it should be)-- but did you know there's a whole world out there of modules that can allow you to control items through various means of interaction? Accelerometers, capacitive touch, light, sound, and more! Learn about different modules that you may not have used before and see how easily they integrate with an Arduino through wiring diagrams and code examples. Experience live demos of how some of these work, try them out yourself through a little audience participation, and walk away with a new exciting perspective on fun ways you can get creative with your own node hardware projects. 

Audience

I will walk through the various module type and inform people on how they function, as well as how they are wired up to the arduino and code that makes them work. There will be various demos that show some different sensor modules. Ex: copper touch sensors to control a video game, yelling to control brightness of leds. It is mostly an experiment to get people to think outside of the box of their usual limitations and to encourage more creative coding. I will also discuss Microsofts IoT platform.

**Comment by jefflembeck** [comment]
Omg yessssss....

**Comment by eliseworthy** [comment]
Feb's meetup is now live! Looking forward to your talk, and let me know if there are any changes I should make to the meetup page.

https://www.meetup.com/seattlejs/events/235567120/
