### ISSUE TITLE
Talk Proposal: Building Chatbots using JavaScript

### ISSUE THREAD

**Issue by tmero** [seattlejs/seattlejs#84]
Chatbots and conversational agents have become very popular in the recent years and there is a huge research effort to automate conversations in several applications. What are Chatbots? How can it benefit you? How do you write the code for it?  These questions will be answered during the session with step by step directions using node.js so you can easily follow along. Come join me and build your first Hello World Chatbot!

**Comment by jefflembeck** [comment]
Sweet. We've talked and you're in for February :) Finally!

**Comment by tmero** [comment]
yay

**Comment by eliseworthy** [comment]
Feb's meetup is now live! Looking forward to your talk, and let me know if there are any changes I should make to the meetup page.

https://www.meetup.com/seattlejs/events/235567120/

**Comment by tmero** [comment]
Sounds good to me :)

Thanks!
