### ISSUE TITLE
Talk Proposal: Headless browser testing with Docker & Selenium

### ISSUE THREAD

**Issue by krotscheck** [seattlejs/seattlejs#86]
# Headless browser testing with Docker and Selenium

This lightning talk will cover how to start a "headless" (no attached display) local selenium grid that can be used for karma or protractor tests. This is useful if you want your tests run in real browsers, but don't have an available display. In short: Real browser testing with nothing but a commandline.

Michael Krotscheck is a Staff Engineer at VMWare, acting as UI lead for a major cross-cloud management platform. In his free time he changes diapers, tickles toddlers, runs, and occasionally implements RFC6749.

* Name: Michael Krotscheck
* [Twitter](https://twitter.com/krotscheck)
* [Github](https://github.com/krotscheck)
* [Website](https://krotscheck.net/)

(side note: I can't present in February, March will be the first opportunity I can)

**Comment by krotscheck** [comment]
Hrm. I can't seem to add the 'lighning' tag.

**Comment by codefoster** [comment]
@krotscheck, how about April 13? Please confirm.

**Comment by codefoster** [comment]
Actually, there's an opening March 9. Does that work? If so, also take a look at our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and express that you agree.

**Comment by codefoster** [comment]
@krotscheck, let me know right away if March 9 works for you. Thanks.

**Comment by krotscheck** [comment]
Heya! April works, March not so much. My wife needs at least a months notice to shift her patient schedule for daycare pickup.

**Comment by codefoster** [comment]
April and May are both booked. How about June 8? That's a good month because we have Dell EMC Isilon's venue confirmed, so it will be a big group.

**Comment by codefoster** [comment]
Can you take a look at our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md) and express that you agree.

**Comment by krotscheck** [comment]
Yep, I agree to the CoC. June 8th should be far enough out, I'll take it!

**Comment by codefoster** [comment]
Confirmed, agreed, and booked. This will be a lightning talk so the target time is 10 minutes. Let me know if you have any questions between now and show time. You can keep an eye on [this](https://github.com/seattlejs/seattlejs/blob/master/meetups.md) page to keep track of how details formulate.

**Comment by codefoster** [comment]
@krotscheck, just wanted to confirm that you're on for presenting a lightning (~10 min) talk at our June 8 meetup.

**Comment by krotscheck** [comment]
@codefoster, @eliseworthy : In the rush to get my son to daycare this morning, I forgot all my MacTax dongles. Do you know of anyone who'll have one I can borrow? Thunderbolt-or-HDMI, not the fancy new USB-C macs.

**Comment by codefoster** [comment]
@krotscheck, I do, but I will be showing up a bit late this evening. I'll ask the other organizers right now and get back to you.

**Comment by EmmaBroback** [comment]
@krotscheck I reached out to the venue and they said they're using a conference software to connect speakers' devices and should have no problem connecting your computer!

**Comment by krotscheck** [comment]
@EmmaBroback Thanks for looking into that! I... hope that won't result in too much technical overhead :D
