### ISSUE TITLE
Talk Proposal: WebKit applications, custom JavaScript extensions, and your TV.

### ISSUE THREAD

**Issue by estobbart** [seattlejs/seattlejs#87]
WebKit applications, custom JavaScript extensions, and your TV.

A quick walk through of a WebKitGTK application, how JavaScript extensions work with JavaScriptCore, and what your TV is doing with all this.

I'm an engineer at Comcast VIPER working on the JavaScript player on the set top box.

* Eric Stobbart
* [Github](https://github.com/estobbart/webkit_gtk_demo)

**Comment by codefoster** [comment]
@estobbart, would this be a lightning (~10 min) or a feature (~25 min)?

**Comment by estobbart** [comment]
Could be either, up to you guys if you like the idea and it's worthy of the time.

**Comment by codefoster** [comment]
How about a lightning talk on April 13? If that works for you, then can you confirm that you agree with our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)?

**Comment by estobbart** [comment]
Sounds good. Confirmed.

**Comment by codefoster** [comment]
@estobbart, I just wanted to make sure you saw that we had a change of venue for this event. We're now going to be at Simply Measured. The details are on the [meetup event page](https://www.meetup.com/seattlejs/events/230354991/). You're still on to deliver a ~10 minute lightning talk, right?

**Comment by estobbart** [comment]
@codefoster I did see that, thank you for following up. Will you be there? Or should I check in ahead of the event with someone?
