### ISSUE TITLE
Talk Proposal: Building w/ARCcore.filters & demo of Holism plug-in app server for Node.js

### ISSUE THREAD

**Issue by ChrisRus** [seattlejs/seattlejs#89]
# So you want to build an app server...

... because it's hard to plug-and-play with Express. And, nobody has time to test it if you try. 

![ARCcore.filter](https://encapsule.io/images/encapsule-arccore-filter-32x32.png)
This talk will briefly introduce the [ARCcore.filter](https://encapsule.io/docs/ARCcore/filter) library that uses  JSON-encoded declarations called [filter specifications](https://encapsule.io/docs/ARCcore/filter/specs) to automate the validation and normalization of JavaScript function input & output. This sounds kind of boring. But, filters can be used to build software factories that manufacture filters. And, this allows us to metaprogram at run-time to build useful things like API templates, and plug-in frameworks that document and test themselves.

![ARCcore.filter](https://encapsule.io/images/encapsule-holism-32x32.png)
 I'll then do a quick demo of [Holism](https://encapsule.io/docs/holism) - a new HTTP app server for Node.js that uses these patterns to implement a plug-in pipeline that bridges between the Node.js [http.ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest) and [http.ServerResponse](https://nodejs.org/api/http.html#http_class_http_serverresponse) stream classes. And, talk about wrapping React, Redis, and back-end features in filter-derived [services](https://encapsule.io/docs/holism/services) plug-ins to build the little app that is serving the docs for this project.

Still working on the docs but they'll be done by showtime. Hope you can make it out.

Thanks SeattleJS!

![Encapsule Project](https://encapsule.io/images/blue-burst-encapsule.io-icon-32x32.png)
Chris Russell
Encapsule Project: [Twitter](https://twitter.com/Encapsule) / [GitHub](https://github.com/Encapsule) / [Website](https://encapsule.io)

**Comment by smcclure879** [comment]
I would be interested to see a talk on this.

**Comment by ChrisRus** [comment]
This is more than an HTTP / REST server - it's the basis of an approach to software development called [software product line engineering](https://en.wikipedia.org/wiki/Software_product_line) that along with ML/AI is going to transform the software industry over the next decade.

**Comment by ChrisRus** [comment]
https://encapsule.io/articles/process

**Comment by ChrisRus** [comment]
https://encapsule.io/articles/notes/feature-add-part1

**Comment by codefoster** [comment]
@ChrisRus, sorry I haven't responded yet. I'll get back to you soon and get this scheduled.

**Comment by codefoster** [comment]
@ChrisRus, how about a lightning talk on June 8?

**Comment by ChrisRus** [comment]
@codefoster - that would be excellent. Sign me up and thanks!

**Comment by codefoster** [comment]
Actually, Chris, does May 11 work? We just had an opening.

**Comment by codefoster** [comment]
And also, can you confirm that you have read and agree with our [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)?

**Comment by ChrisRus** [comment]
@codefoster - 5/11 is great. Also, have read & agree w/code of conduct; good doc!

**Comment by ChrisRus** [comment]
Published docs for ARCcore.filter lib overnight https://encapsule.io/docs/ARCcore/filter

What's cool is that the docs are hosted on the new app server that's built almost entirely from Filters atop the Node.js HTTP API (no Express or other middleware involved). HTML rendering via server/client React. Storage via my favorite store, Redis :-)

**Comment by codefoster** [comment]
Confirmed. Thanks, @ChrisRus.

**Comment by ChrisRus** [comment]
Thanks. I updated the title and talk description. This will be just a quick intro. But, it should be fun :)

**Comment by EmmaBroback** [comment]
@ChrisRus If I could get a brief bio from you for the event page, that would be awesome. Thanks!

**Comment by ChrisRus** [comment]
Thanks.
