### ISSUE TITLE
Talk proposal: A Brief History of Failed Packaged Web App Schemes

### ISSUE THREAD

**Issue by thomaswilburn** [seattlejs/seattlejs#90]
In November 2016, Google disabled Chrome Apps on all platforms except Chrome OS. This change was a while in the making, but it represents the latest failure in "packaged apps" - web apps that are downloaded and run as if they were native, built on a common or system-wide runtime. Increasingly, if you want to build an offline web app, your choices have been reduced to only two: either limited privileges running on a Service Worker, or shipping a complete browser stack via Electron.

As the maintainer of a Chrome App with (at last glance) ~200k users, I could choose to be upset about this. But I think it's more interesting to look back at the packaged app dream: what is it that gives them such a recurring appeal? Why do they fail, time and time again? And how do they fit into a new vision of the web - its capabilities, limitations, and reach?

In this talk, I'll go way back into the history of packaged apps (IE4, baby!), then work forward to the current state of the art. I'll talk about what these apps could and couldn't do, and how those features have influenced the development of browser standards. And finally, I'll speculate wildly about how Service Worker (in conjunction with Web Bluetooth, Web USB, and god-only-knows what other Web Buzzwords are in development) may be evolving both toward and away from these weird web offshoots.

**Comment by codefoster** [comment]
This looks like good stuff, Thomas. I'm guessing this would more likely be a feature talk (~25 min) rather than a lightning talk (~10), right? How does **July 6** work for you? And can you read and state that you agree with the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)?

**Comment by thomaswilburn** [comment]
Yeah, I was aiming for about 25 minutes. July 6 sounds good! And I have read and agree with the code of conduct.

**Comment by codefoster** [comment]
Great. We're on.

**Comment by thomaswilburn** [comment]
Hey, was just noticing that the 6th is not the date of the Meetup according to the site. Am I speaking tomorrow or next week?

**Comment by codefoster** [comment]
Hmm. Not sure what was wrong with my head when I said the 6th. You're actually speaking next Thursday. Sorry for the inconvenience!! Hope that still works for you.

**Comment by thomaswilburn** [comment]
Sure, it turns out that's still clear. See you then!

**Comment by EmmaBroback** [comment]
@thomaswilburn Hello Thomas! 
We're excited for you to present this week. 
I'm in contact with the venue and they would like to know what machine you're presenting off of so they can be prepared with the appropriate adapters. 
Let me know-- see you Thursday!

**Comment by thomaswilburn** [comment]
Oh, great! I normally present off a Chromebook that has an HDMI out, so it's pretty easy. But my talk is also up on GDocs, so I can borrow a Mac from another presenter if that's more convenient.

**Comment by EmmaBroback** [comment]
That should be fine, thanks!
