### ISSUE TITLE
Talk Proposal: Learn to Code with JavaScript by Choosing Your Own Adventures!

### ISSUE THREAD

**Issue by tmero** [seattlejs/seattlejs#91]
New to JavaScript? Having troubles finding fun content to learn with? You can find fun ways to learn! In this presentation, you will learn how to use basic syntax of JavaScript, use variables and functions, conditional statements, and you will build a "Choose Your Own Adventure" application. Sit back in your seat and get ready for a dangerous adventure!

Will be forking this code: https://github.com/GalvanizeOpenSource/learn-to-code-javascript-2

**Comment by codefoster** [comment]
Can this fit in a feature presentation (~25 min)? It might not be a bad idea to give it a bit more time one month and not do lightning talks - sort of a back to the basics.

**Comment by tmero** [comment]
Sure I can do that. What month?

Disclosure: There may be a chance of cancelling if my manager has my travel last minute. Life of a developer evangelist!

I update my travel schedule every few days here: https://gist.github.com/tmero/64df812f238aed60420172bd830f0a28


Thanks!

**Comment by codefoster** [comment]
Feature presentations are currently scheduled quite a ways out. We're looking at something like October. Let's just sit on this idea for a while and see if it evolves before we schedule it. In the meantime, we'll try to get your other topic (the REST API's one) into an upcoming lightning slot.

**Comment by tmero** [comment]
Sounds good. I think my October travel schedule is pretty solid as I am going to push to not add anything more to it: 
https://gist.github.com/tmero/64df812f238aed60420172bd830f0a28

**Comment by tmero** [comment]
Link to the slides if anyone wants: https://www.slideshare.net/Tessa99/learn-to-code-with-javascript-choose-your-own-adventures-80720452
