### ISSUE TITLE
Talk Proposal: Learn REST APIs in 5 Simple Steps

### ISSUE THREAD

**Issue by tmero** [seattlejs/seattlejs#92]
Feeling hungry? You’ve came to the right place! As APIs have become increasingly more important and popular in usage in the past few years in web development, it is important to understand the basics of what they are and why to use them. I will be going over the basics: The What’s, Why’s, Where’s, and When’s. You will learn the basics of REST APIs and I will show you how you can use POSTMAN to test making REST API calls. I will use Cisco’s Spark and Tropo as use case examples of working with APIs.

Tessa Mero is the Developer Evangelist for Cisco. She spends her extra time contributing on a leadership team for the Joomla! Project and has been involved with Joomla for the past 5 years. She runs the Seattle PHP Meetup and is the organizer of the Pacific Northwest PHP conference. On her free time, she likes to play video games, snowboard, and eat Korean food.

Twitter: @tessamero
Website: http://tessamero.com
Email: tmero@cisco.com

**Comment by codefoster** [comment]
Does May 11 work for you?

**Comment by tmero** [comment]
I am in Italy on May 11th. Here is my travel schedule that I update every other day: 
https://gist.github.com/tmero/64df812f238aed60420172bd830f0a28

**Comment by tmero** [comment]
Update: I just changed the talk title to be more of a lightning talk style :)

**Comment by codefoster** [comment]
How does June 8 work? It's the evening before you're in CA, so I'm not sure how tight you want to book things.

**Comment by tmero** [comment]
June 8th works. I think that california trip may be cancelled as I haven’t heard anything about it, so I removed it off gist.

See you then!

**Comment by codefoster** [comment]
@tmero, just wanted to confirm that you're on for presenting a lightning (~10 min) talk on _Learn REST APIs in 5 Simple Steps_ at our June 8 meetup.
/cc @eliseworthy

**Comment by tessamero** [comment]
Confirm.

**Comment by codefoster** [comment]
@tessamero, do you want to do this July 13? We have an opening for a lightning presentation.

**Comment by tmero** [comment]
I will be in San Francisco during that day. Thanks for asking, I really appreciate it!

**Comment by codefoster** [comment]
How about Oct 12 or Nov 9?

**Comment by tmero** [comment]
October 12th I have nothing scheduled for my travel, so I will put that on my calendar :) Is it lightning talk that day?

**Comment by codefoster** [comment]
Let's put you down for a feature that day. That's about 25 min. We're confirmed. Thanks, @tmero.

**Comment by codefoster** [comment]
Let's put you down for a feature that day. That's about 25 min. We're confirmed. Thanks, @tmero.

**Comment by tmero** [comment]
Thanks!
