### ISSUE TITLE
Talk Proposal: Optimizing React/Redux Apps for TV at Facebook

### ISSUE THREAD

**Issue by davidchang** [seattlejs/seattlejs#93]
# Optimizing React/Redux Apps for TV at Facebook

Facebook recently launched an HTML5 based TV app on several [platforms](https://techcrunch.com/2017/02/27/facebooks-new-video-app-hits-samsung-smart-tvs/), a single page app built with React, Redux, and GraphQL. TVs are notorious for having lower end hardware, so we were forced to work through several performance bottlenecks (both computational and presentational) in JS and CSS.

This talk will discuss some of our learnings that can be applied to all single page React applications, especially those required to run on less powerful devices. Some of these learnings include having tighter control over React components' shouldComponentUpdate and lifecycle, delaying work until more opportune times, what belongs in Redux and what doesn't, and avoiding layout recalcs.

* David Chang
* [Twitter](https://twitter.com/davidchizzle)
* [Github](https://github.com/davidchang)
* [Website](http://davidandsuzi.com/)

**Comment by ChrisRus** [comment]
Very interested in this talk!

**Comment by codefoster** [comment]
@davidchang, sorry for the delay and thank you very much for the submission. This sounds to me like a feature (~25 min) more than a lightning talk (~10 min) right? Does September 14 work for you? If so, can you confirm that you accept the group's [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md)?

**Comment by davidchang** [comment]
Awesome - @codefoster, I can confirm the acceptance of the code of conduct, would love to give a ~25 minute talk on September 14.

**Comment by codefoster** [comment]
@davidchang, just wanted to let you know that you're confirmed for this. What would you like to use for the speaker image? Feel free to give a URL or upload an image here.

**Comment by davidchang** [comment]
@codefoster confirming - sorry for the delay, here's a URL! https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-9/1908003_10152430052552495_4738810497734973420_n.jpg?_nc_log=1&oh=a305471defaf2cfac7f9d4afe6d1527a&oe=59CDE98D

**Comment by codefoster** [comment]
Got it. Thanks.

**Comment by EmmaBroback** [comment]
@davidchang 
Hi David! I'm Emma and I'll be creating the meetup page. 
Could you type up a quick bio to be posted with your talk's abstract? Thanks!
