### ISSUE TITLE
Talk Proposal: Introducing CaffeineScript - Productivity by Design

### ISSUE THREAD

**Issue by shanebdavis** [seattlejs/seattlejs#95]
# Introducing CaffeineScript - Productivity by Design

CaffeineScript is a programming language that compiles to JavaScript. The goal is to minimize total effort, over a product's lifetime, for the entire team. Design thinking is essential for achieving that goal. That means user-experience and graphic design are as important as computer-science and software engineering. If done right, a well-designed language can make programming more wonderful, code more beautiful and programming more fun.

CaffeineScript is inspired by CoffeeScript, but it is a ground-up redesign, re-imagining what CoffeeScript or JavaScript might look like if it they were written today. The result is a lean, high-level language that empowers you to get the most out of JavaScript.

For more, visit [CaffeineScript.com](http://CaffeineScript.com)

### Bio

I've been the CTO and co-founder of [Imikimi.com](http://imikimi.com) for the last 10 years. During that time I've coded or led projects in: Ruby (rails), C++ (client-side and server-side graphics and UI), Objective-C (iOS), Java (Android), OpenGL (iOS/Android), Flash (ick!) and Client-side JavaScript & CoffeeScript (canvas-based graphics editor and more). Before that I spent approximately 10 years researching language design and programmer productivity.

* Shane Brinkman-Davis Delamore
* CTO and Co-founder [Imikimi.com](http://imikimi.com)
* [Email](shanebdavis@gmail.com)
* [Github](https://github.com/shanebdavis)
* [Blog](http://EssenceAndArtifact.com)

**Comment by codefoster** [comment]
@shanebdavis, normally I'm not this late in approving talks. Sorry. Do you want to do a lightning presentation (~10 min) on Sept 14? Let me know if that sounds good or if you'd rather do a feature presentation at a later date.

Also, please confirm that you agree with the [code of conduct](https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md).

**Comment by codefoster** [comment]
To be specific, there is an opening for a feature presentation for our October 12 meetup if you'd rather have about 25 minutes for your presentation.

**Comment by shanebdavis** [comment]
Great! Let's do the 10min talk. It'll be fun to see what is the most important and what fits in 10 minutes. On my calendar: 9/14/2017

**Comment by shanebdavis** [comment]
I agree to the code of conduct.

**Comment by codefoster** [comment]
Gotcha. Confirmed. Let us know what you want to use for an avatar for the meetup announcement when you get a chance.

**Comment by shanebdavis** [comment]
Avatar? Does this work? [profile photo](https://raw.githubusercontent.com/shanebdavis/profile-photos/master/shane%20at%20cedar%20lake%20square%20cropped.jpg)

**Comment by codefoster** [comment]
That works great. Thanks.
